// Restored from ref/webview/assets/diff-view-mode-C5urbSEm.js
// diff-view-mode-C5urbSEm chunk restored from the Codex webview bundle.
import {
  applyCssProperties,
  applyCodexThemeToElement,
  editorDiffViewModeSignal,
  fileSourceGitBlameSignal,
  getCodeThemeRegistration,
  hideDiffWhitespaceSignal,
  isCodeThemeId,
  listAllCodeThemeRegistrations,
  listCodeThemesForVariant,
  loadChromeThemeSeed,
  normalizeCodexChromeTheme,
  resolveCodeTheme,
  richPreviewSignal,
  scopedRichPreviewEnabledSignal,
  setThreadRichPreviewEnabled,
  wordDiffsEnabledSignal,
  wrapCodeDiffSignal,
} from "./diff-view-mode-impl";
export {
  applyCssProperties,
  scopedRichPreviewEnabledSignal,
  wrapCodeDiffSignal,
  listCodeThemesForVariant,
  getCodeThemeRegistration,
  normalizeCodexChromeTheme,
  applyCodexThemeToElement,
  richPreviewSignal,
  loadChromeThemeSeed,
  isCodeThemeId,
  fileSourceGitBlameSignal,
  setThreadRichPreviewEnabled,
  listAllCodeThemeRegistrations,
  hideDiffWhitespaceSignal,
  wordDiffsEnabledSignal,
  editorDiffViewModeSignal,
  resolveCodeTheme,
};
