// Restored from ref/webview/assets/automation-shared-g-EMxEEn.js
// automation-shared-g-EMxEEn chunk restored from the Codex webview bundle.
import {
  DEFAULT_AUTOMATION_DRAFT,
  applyAutomationDraftModelDefaults,
  applyAutomationScheduleDraft,
  applyHeartbeatTargetThread,
  automationDirectiveDialogOpenAtom,
  automationDirectiveResultAtom,
  automationDirectiveSeedAtom,
  createAutomationDraftFromAutomation,
  createAutomationDraftFromSeed,
  createAutomationSeedFromDirective,
  formatAutomationNextRunLabel,
  getAutomationDestinationOptions,
  getAutomationDirectiveActionMode,
  getAutomationDraftDestination,
  getAutomationDraftRrule,
  initAutomationDraftRuntimeChunk,
  initAutomationNextRunLabelChunk,
  isAutomationDraftUsingDefaultCwd,
  isDefaultAutomationDraft,
  setAutomationDraftCwds,
  setAutomationDraftDestination,
  setAutomationDraftKind,
  toAutomationCreatePayload,
  toAutomationUpdatePayload,
  validateAutomationDraft,
} from "./shared-impl";
export {
  formatAutomationNextRunLabel,
  initAutomationDraftRuntimeChunk,
  initAutomationNextRunLabelChunk,
  getAutomationDraftRrule,
  setAutomationDraftKind,
  automationDirectiveResultAtom,
  isDefaultAutomationDraft,
  createAutomationDraftFromAutomation,
  createAutomationSeedFromDirective,
  getAutomationDraftDestination,
  setAutomationDraftDestination,
  setAutomationDraftCwds,
  automationDirectiveDialogOpenAtom,
  createAutomationDraftFromSeed,
  getAutomationDestinationOptions,
  applyAutomationDraftModelDefaults,
  automationDirectiveSeedAtom,
  validateAutomationDraft,
  applyAutomationScheduleDraft,
  toAutomationCreatePayload,
  DEFAULT_AUTOMATION_DRAFT,
  toAutomationUpdatePayload,
  applyHeartbeatTargetThread,
  getAutomationDirectiveActionMode,
  isAutomationDraftUsingDefaultCwd,
};
