// Restored from ref/webview/assets/agent-settings-CE_EGsV1.js
// Semantic implementation module for agent settings runtime wiring.

import {
  once as rolldownRuntimeN,
  toEsModule as rolldownRuntimeS,
} from "../../runtime/commonjs-interop";
import {
  currentAppInitialSharedCompatSlotDollarLowerS as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  currentAppInitialSharedCompatSlotUpperD as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  currentAppInitialSharedCompatSlotUpperE as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  currentAppInitialSharedCompatSlotUpperELowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEo,
  currentAppInitialSharedCompatSlotUpperGLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGo,
  currentAppInitialSharedCompatSlotUpperKLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  currentAppInitialSharedCompatSlotUpperO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  currentAppInitialSharedCompatSlotUpperVLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  currentAppInitialSharedCompatSlotUnderscoreLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerALowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wAc,
  currentAppInitialSharedCompatSlotLowerC as _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerCLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  currentAppInitialSharedCompatSlotLowerGLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  currentAppInitialSharedCompatSlotLowerH as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH,
  currentAppInitialSharedCompatSlotLowerI as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  currentAppInitialSharedCompatSlotLowerJLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wJo,
  currentAppInitialSharedCompatSlotLowerLLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  currentAppInitialSharedCompatSlotLowerM as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wM,
  currentAppInitialSharedCompatSlotLowerQLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  currentAppInitialSharedCompatSlotLowerSLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wSo,
  currentAppInitialSharedCompatSlotLowerTLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
  currentAppInitialSharedCompatSlotLowerTLowerR as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTr,
  currentAppInitialSharedCompatSlotLowerU as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wU,
  currentAppInitialSharedCompatSlotLowerULowerR as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wUr,
} from "../../runtime/current-app-initial/current-app-initial-shared-runtime";
import {
  worktreeNewThreadOrchestratorCompatSlotUpperALowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAm,
  worktreeNewThreadOrchestratorCompatSlotUpperDLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsDr,
  worktreeNewThreadOrchestratorCompatSlotUpperTLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsTr,
  worktreeNewThreadOrchestratorCompatSlotLowerALowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAt,
  worktreeNewThreadOrchestratorCompatSlotLowerILowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsIt,
  worktreeNewThreadOrchestratorCompatSlotLowerJLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsJm,
} from "../../runtime/current-app-initial/worktree-new-thread-orchestrator-runtime";
import {
  worktreeNewThreadQueryCompatSlotUpperALowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn,
  worktreeNewThreadQueryCompatSlotUpperDLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDn,
  worktreeNewThreadQueryCompatSlotUpperELowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  worktreeNewThreadQueryCompatSlotUpperNLowerF as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNf,
  worktreeNewThreadQueryCompatSlotUpperNLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNn,
  worktreeNewThreadQueryCompatSlotUpperOLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOn,
  worktreeNewThreadQueryCompatSlotUpperOLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  worktreeNewThreadQueryCompatSlotUpperPLowerF as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwPf,
  worktreeNewThreadQueryCompatSlotUpperPLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwPn,
  worktreeNewThreadQueryCompatSlotUpperTLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  worktreeNewThreadQueryCompatSlotLowerCLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCl,
  worktreeNewThreadQueryCompatSlotLowerDLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDs,
  worktreeNewThreadQueryCompatSlotLowerELowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  worktreeNewThreadQueryCompatSlotLowerFLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwFs,
  worktreeNewThreadQueryCompatSlotLowerGLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  worktreeNewThreadQueryCompatSlotLowerILowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIs,
  worktreeNewThreadQueryCompatSlotLowerKLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKn,
  worktreeNewThreadQueryCompatSlotLowerKLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  worktreeNewThreadQueryCompatSlotLowerLLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLl,
  worktreeNewThreadQueryCompatSlotLowerLLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLo,
  worktreeNewThreadQueryCompatSlotLowerLLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLs,
  worktreeNewThreadQueryCompatSlotLowerMLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  worktreeNewThreadQueryCompatSlotLowerNLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  worktreeNewThreadQueryCompatSlotLowerNLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs,
  worktreeNewThreadQueryCompatSlotLowerOLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  worktreeNewThreadQueryCompatSlotLowerOLowerP as _appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  worktreeNewThreadQueryCompatSlotLowerSLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSl,
  worktreeNewThreadQueryCompatSlotLowerSLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSp,
  worktreeNewThreadQueryCompatSlotLowerULowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo,
  worktreeNewThreadQueryCompatSlotLowerULowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUs,
} from "../../runtime/current-app-initial/worktree-new-thread-query-runtime";
import {
  currentAppInitialSharedMember0011 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dP,
  imagePickerSchemaCapabilities as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBl,
  createScopedSignalAtom as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  intlFormatDateTimeRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  remoteControlRefreshSourceEnum as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dKp,
  useReactRouterLocationInvariant as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNa,
  currentAppInitialSharedDisplayRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  remoteConnectionRuntime0298 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRl,
  currentAppInitialSharedFunction0375 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  currentAppInitialSharedMember0481 as AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dAy,
  currentAppInitialSharedMember0486 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBf,
  currentAppInitialSharedRuntime0710 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNv,
  currentAppInitialSharedMember0781 as AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRy,
  currentAppInitialSharedMember0815 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTv,
  currentAppInitialSharedRuntime0816 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy,
  currentAppInitialSharedMember0839 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVf,
  currentAppInitialSharedRuntime0840 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg,
  openAiNativeAppDefinition as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  currentAppInitialSharedFunction0895 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYg,
  currentAppInitialSharedMember0924 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
} from "../../runtime/current-app-initial/remote-projects-app-shared-runtime";
import {
  pullRequestNewThreadCompatSlotUpperBLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkBt,
  pullRequestNewThreadCompatSlotUpperFLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkFt,
  pullRequestNewThreadCompatSlotUpperGLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkGt,
  pullRequestNewThreadCompatSlotUpperHLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkHt,
  pullRequestNewThreadCompatSlotUpperJLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkJt,
  pullRequestNewThreadCompatSlotUpperPLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkPt,
  pullRequestNewThreadCompatSlotUpperULowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkUt,
  pullRequestNewThreadCompatSlotUpperWLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkWt,
  pullRequestNewThreadCompatSlotUpperZLowerT as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkZt,
  pullRequestNewThreadCompatSlotLowerB as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkB,
  pullRequestNewThreadCompatSlotLowerDLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn,
  pullRequestNewThreadCompatSlotLowerRLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkRn,
  pullRequestNewThreadCompatSlotLowerY as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkY,
  pullRequestNewThreadCompatSlotLowerZLowerT as _appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkZt,
} from "../../runtime/current-app-initial/pull-request-new-thread-runtime";
import {
  appMainCurrentCompatSlotUpperALowerO as appInitialAppMainOnboardingPageAo,
  appMainCurrentCompatSlotUpperALowerU as AppInitialAppMainOnboardingPageAu,
  appMainCurrentCompatSlotUpperBLowerP as appInitialAppMainOnboardingPageBp,
  initPrimaryRuntimeInstallStatusMessageChunk as appInitialAppMainOnboardingPageEo,
  appMainCurrentCompatSlotUpperFLowerN as appInitialAppMainOnboardingPageFn,
  appMainCurrentCompatSlotUpperGLowerP as AppInitialAppMainOnboardingPageGp,
  appMainCurrentCompatSlotUpperGLowerT as AppInitialAppMainOnboardingPageGt,
  appMainCurrentCompatSlotUpperILowerN as AppInitialAppMainOnboardingPageIn,
  appMainCurrentCompatSlotUpperJLowerP as appInitialAppMainOnboardingPageJp,
  appMainCurrentCompatSlotUpperKLowerP as AppInitialAppMainOnboardingPageKp,
  appMainCurrentCompatSlotUpperLLowerO as appInitialAppMainOnboardingPageLo,
  appMainCurrentCompatSlotUpperMLowerU as appInitialAppMainOnboardingPageMu,
  appMainCurrentCompatSlotUpperNLowerP as appInitialAppMainOnboardingPageNp,
  appMainCurrentCompatSlotUpperOLowerO as appInitialAppMainOnboardingPageOo,
  appMainCurrentCompatSlotUpperPLowerP as appInitialAppMainOnboardingPagePp,
  appMainCurrentCompatSlotUpperRLowerO as appInitialAppMainOnboardingPageRo,
  appMainCurrentCompatSlotUpperRLowerP as appInitialAppMainOnboardingPageRp,
  initCodexLinksChunk as appInitialAppMainOnboardingPageSc,
  registerForkedConversation as appInitialAppMainOnboardingPageTo,
  appMainCurrentCompatSlotUpperVLowerP as appInitialAppMainOnboardingPageVp,
  appMainCurrentCompatSlotUpperWLowerT as appInitialAppMainOnboardingPageWt,
  appMainCurrentCompatSlotLowerDLowerC as appInitialAppMainOnboardingPageDc,
  appMainCurrentCompatSlotLowerDLowerR as appInitialAppMainOnboardingPageDr,
  appMainCurrentCompatSlotLowerILowerM as appInitialAppMainOnboardingPageIm,
  appMainCurrentCompatSlotLowerJLowerO as appInitialAppMainOnboardingPageJo,
  appMainCurrentCompatSlotLowerKLowerO as appInitialAppMainOnboardingPageKo,
  appMainCurrentCompatSlotLowerQLowerP as appInitialAppMainOnboardingPageQp,
  appMainCurrentCompatSlotLowerRLowerM as appInitialAppMainOnboardingPageRm,
  appMainCurrentCompatSlotLowerULowerR as appInitialAppMainOnboardingPageUr,
  appMainCurrentCompatSlotLowerWLowerO as appInitialAppMainOnboardingPageWo,
  appMainCurrentCompatSlotLowerZLowerP as appInitialAppMainOnboardingPageZp,
} from "../../vendor/app-main-current-runtime/index";
import {
  appgenLibraryHotDjo67r4nCompatSlotUpperH as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appgenLibraryHotDjo67r4nCompatSlotUpperR as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appgenLibraryHotDjo67r4nCompatSlotUpperV as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
} from "../../runtime/current-app-initial/appgen-library-hot-djo67r4n-runtime";
import {
  initCodexAppIdentityChunk as appInitialAppMainWorktreeInitV2PageAppgenSettingsPagePageAppgenPageRemoteConDi269h6jH,
  CODEX_APP_NAME as appInitialAppMainWorktreeInitV2PageAppgenSettingsPagePageAppgenPageRemoteConDi269h6jM,
} from "../../runtime/renderer-error-boundary-runtime";
import {
  generalAppearanceCurrentCompatSlotUpperJ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  generalAppearanceCurrentCompatSlotLowerD as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  generalAppearanceCurrentCompatSlotLowerF as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  generalAppearanceCurrentCompatSlotLowerQ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
} from "../../runtime/current-app-initial/general-appearance-current-runtime";
import {
  formatPrimaryRuntimeDiagnosticsFailedEvent as appInitialAppMainAgentSettingsA,
  cancelPrimaryRuntimeInstall as appInitialAppMainAgentSettingsD,
  formatPrimaryRuntimeDiagnosticsEvent as appInitialAppMainAgentSettingsI,
  PRIMARY_RUNTIME_SETTINGS_FEATURE_ID as appInitialAppMainAgentSettingsL,
  isPrimaryRuntimeInstallAbortError as appInitialAppMainAgentSettingsN,
  formatPrimaryRuntimeDependenciesResetEvent as appInitialAppMainAgentSettingsO,
  initPrimaryRuntimeInstallRequestStateChunk as appInitialAppMainAgentSettingsP,
  initPrimaryRuntimeInstallEventFormattersChunk as appInitialAppMainAgentSettingsS,
  initPrimaryRuntimeInstallActionChunk as appInitialAppMainAgentSettingsT,
  initPrimaryRuntimeFeatureFlagsChunk as appInitialAppMainAgentSettingsU,
} from "../../runtime/current-app-initial/agent-settings-diagnostics-runtime";
import {
  initSettingsContentLayoutChunk as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  SettingsContentLayout as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
} from "../../runtime/current-app-initial/settings-section-layout-runtime";
import {
  initPrimaryRuntimeConfigChunk as appInitialAppMainDebugWindowPageAgentSettingsDebugModalA,
  refreshPrimaryRuntimeConfigFromStatsig as appInitialAppMainDebugWindowPageAgentSettingsDebugModalN,
  primaryRuntimeDiagnosticsQueryKey as appInitialAppMainDebugWindowPageAgentSettingsDebugModalR,
  getPrimaryRuntimeConfigFromStatsig as appInitialAppMainDebugWindowPageAgentSettingsDebugModalS,
} from "../../runtime/primary-runtime-query-keys";
import {
  openInTargetsQuery as openInTargetsQueryN,
  initOpenInTargetsQueryChunk as openInTargetsQueryT,
} from "../../utils/open-in-targets-query";
import {
  isExperimentalFeatureVisible as experimentalFeatureVisibilityN,
  initExperimentalFeatureVisibilityChunk as experimentalFeatureVisibilityT,
} from "../../features/experimental-features/visibility";
var agentSettingsMessages,
  initAgentSettingsMessages = rolldownRuntimeN(() => {
    (appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      (agentSettingsMessages =
        appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy(
          {
            customConfig: {
              id: `settings.agent.customConfig.sectionTitle`,
              defaultMessage: `Custom config.toml settings`,
              description: `Heading for the custom config.toml settings section`,
            },
            projectConfig: {
              id: `settings.agent.configuration.scope.projectGroup`,
              defaultMessage: `Project config`,
              description: `Section label for project config scopes`,
            },
            globalConfig: {
              id: `settings.agent.configuration.scope.globalGroup`,
              defaultMessage: `Global config`,
              description: `Section label for user and admin config scopes`,
            },
            userConfig: {
              id: `settings.agent.configuration.scope.user`,
              defaultMessage: `User config`,
              description: `Label for the user config scope in configuration settings`,
            },
            adminConfig: {
              id: `settings.agent.configuration.scope.managed`,
              defaultMessage: `Admin config`,
              description: `Label for the admin config scope in configuration settings`,
            },
            approvalPolicy: {
              id: `settings.agent.configuration.approval.label`,
              defaultMessage: `Approval policy`,
              description: `Label for approval policy in configuration settings`,
            },
            untrusted: {
              id: `settings.agent.configuration.approval.option.untrusted`,
              defaultMessage: `Untrusted`,
              description: `Label for the untrusted approval policy option`,
            },
            onFailure: {
              id: `settings.agent.configuration.approval.option.onFailure`,
              defaultMessage: `On failure`,
              description: `Label for the on failure approval policy option`,
            },
            onRequest: {
              id: `settings.agent.configuration.approval.option.onRequest`,
              defaultMessage: `On request`,
              description: `Label for the on request approval policy option`,
            },
            never: {
              id: `settings.agent.configuration.approval.option.never`,
              defaultMessage: `Never`,
              description: `Label for the never approval policy option`,
            },
            sandboxSettings: {
              id: `settings.agent.configuration.sandbox.label`,
              defaultMessage: `Sandbox settings`,
              description: `Label for sandbox settings in configuration settings`,
            },
            readOnly: {
              id: `settings.agent.configuration.sandbox.option.readOnly`,
              defaultMessage: `Read only`,
              description: `Label for the read only sandbox option`,
            },
            workspaceWrite: {
              id: `settings.agent.configuration.sandbox.option.workspaceWrite`,
              defaultMessage: `Workspace write`,
              description: `Label for the workspace write sandbox option`,
            },
            fullAccess: {
              id: `settings.agent.configuration.sandbox.option.fullAccess`,
              defaultMessage: `Full access`,
              description: `Label for the full access sandbox option`,
            },
            networkAccess: {
              id: `settings.agent.configuration.network.label`,
              defaultMessage: `Allow network access`,
              description: `Label for network access in configuration settings`,
            },
            workspaceDependencies: {
              id: `settings.agent.dependencies.sectionTitle`,
              defaultMessage: `Workspace Dependencies`,
              description: `Heading for the Codex dependencies settings section`,
            },
            currentDependencyVersion: {
              id: `settings.agent.dependencies.bundleVersion.label`,
              defaultMessage: `Current version`,
              description: `Label for the installed Codex dependency bundle version`,
            },
            codexDependencies: {
              id: `settings.agent.dependencies.enabled.label`,
              defaultMessage: `Codex dependencies`,
              description: `Label for the Codex dependencies enabled toggle`,
            },
            diagnoseWorkspaceDependencies: {
              id: `settings.agent.dependencies.diagnose.label`,
              defaultMessage: `Diagnose issues in Codex Workspace`,
              description: `Label for dependency diagnostics in settings`,
            },
            resetWorkspaceDependencies: {
              id: `settings.agent.dependencies.reset.label`,
              defaultMessage: `Reset and install Workspace`,
              description: `Label for resetting and reinstalling dependencies in settings`,
            },
            experimentalFeatures: {
              id: `settings.general.experimentalFeatures`,
              defaultMessage: `Experimental features (Beta)`,
              description: `Heading for beta experimental features settings group`,
            },
          },
        )));
  });
var initConfigFileRuntime = rolldownRuntimeN(() => {
  _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC();
});
var experimentalFeatureRuntimeInit,
  experimentalFeatureReactRuntime,
  experimentalFeatureElementFactory,
  initExperimentalFeaturesSection = rolldownRuntimeN(() => {
    ((experimentalFeatureRuntimeInit =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
      (experimentalFeatureReactRuntime = rolldownRuntimeS(
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
        1,
      )),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      appInitialAppMainWorktreeInitV2PageAppgenSettingsPagePageAppgenPageRemoteConDi269h6jH(),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn(),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCl(),
      experimentalFeatureVisibilityT(),
      appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF(),
      AppInitialAppMainOnboardingPageIn(),
      appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ(),
      (experimentalFeatureElementFactory =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()));
  });
var modelFeatureRuntimeInit,
  modelFeatureElementFactory,
  reasoningEffortOptions,
  initReasoningEffortOptions = rolldownRuntimeN(() => {
    ((modelFeatureRuntimeInit =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo(),
      appInitialAppMainOnboardingPageDr(),
      appInitialAppMainOnboardingPageNp(),
      appInitialAppMainOnboardingPageBp(),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD(),
      appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF(),
      AppInitialAppMainOnboardingPageIn(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH(),
      appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ(),
      (modelFeatureElementFactory =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()),
      (reasoningEffortOptions = [`max`, `ultra`]));
  });
var locationStateSchema,
  initLocationStateSchema = rolldownRuntimeN(() => {
    (appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wSo(),
      (locationStateSchema =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEo(
          {
            workspaceRoot:
              appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wJo()
                .min(1)
                .nullable()
                .optional(),
          },
        ).passthrough()));
  });
var agentSettingsRuntimeInit,
  agentSettingsReactRuntime,
  agentSettingsElementFactory,
  approvalPolicyOptions,
  sandboxModeOptions;
rolldownRuntimeN(() => {
  ((agentSettingsRuntimeInit =
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dKp(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO(),
    (agentSettingsReactRuntime = rolldownRuntimeS(
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
      1,
    )),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkY(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg(),
    appInitialAppMainAgentSettingsS(),
    appInitialAppMainAgentSettingsT(),
    appInitialAppMainAgentSettingsU(),
    appInitialAppMainAgentSettingsP(),
    appInitialAppMainOnboardingPageOo(),
    appInitialAppMainOnboardingPageEo(),
    appInitialAppMainDebugWindowPageAgentSettingsDebugModalR(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwPn(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsTr(),
    AppInitialAppMainOnboardingPageKp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAt(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUs(),
    appInitialAppMainOnboardingPageSc(),
    openInTargetsQueryT(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNf(),
    AppInitialAppMainOnboardingPageGt(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOn(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwFs(),
    appInitialAppMainOnboardingPageRo(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo(),
    appInitialAppMainOnboardingPageIm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSp(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRl(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkWt(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCl(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNv(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn(),
    appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR(),
    initAgentSettingsMessages(),
    initConfigFileRuntime(),
    initExperimentalFeaturesSection(),
    initReasoningEffortOptions(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF(),
    AppInitialAppMainOnboardingPageAu(),
    initLocationStateSchema(),
    AppInitialAppMainOnboardingPageIn(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp(),
    appInitialAppMainDebugWindowPageAgentSettingsDebugModalA(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy(),
    appInitialAppMainOnboardingPageQp(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH(),
    _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
    (agentSettingsElementFactory =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()),
    (approvalPolicyOptions = [
      {
        value: `untrusted`,
        label: agentSettingsMessages.untrusted,
        description: `Always ask before taking action`,
      },
      {
        value: `on-failure`,
        label: agentSettingsMessages.onFailure,
        description: `Ask only when a command fails`,
      },
      {
        value: `on-request`,
        label: agentSettingsMessages.onRequest,
        description: `Ask when escalation is requested`,
      },
      {
        value: `never`,
        label: agentSettingsMessages.never,
        description: `Run without asking for approval`,
      },
    ]),
    (sandboxModeOptions = [
      {
        value: `read-only`,
        label: agentSettingsMessages.readOnly,
        description: `Can read files, but cannot edit them`,
      },
      {
        value: `workspace-write`,
        label: agentSettingsMessages.workspaceWrite,
        description: `Can edit files, but only in this workspace`,
      },
      {
        value: `danger-full-access`,
        label: agentSettingsMessages.fullAccess,
        description: `Can edit files outside this workspace`,
      },
    ]));
})();
const agentSettingsRuntime = {
  _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  _appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  _appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkZt,
  agentSettingsElementFactory,
  agentSettingsMessages,
  agentSettingsReactRuntime,
  agentSettingsRuntimeInit,
  appInitialAppMainAgentSettingsA,
  appInitialAppMainAgentSettingsD,
  appInitialAppMainAgentSettingsI,
  appInitialAppMainAgentSettingsL,
  appInitialAppMainAgentSettingsN,
  appInitialAppMainAgentSettingsO,
  appInitialAppMainAgentSettingsP,
  appInitialAppMainAgentSettingsS,
  appInitialAppMainAgentSettingsT,
  appInitialAppMainAgentSettingsU,
  appInitialAppMainDebugWindowPageAgentSettingsDebugModalA,
  appInitialAppMainDebugWindowPageAgentSettingsDebugModalN,
  appInitialAppMainDebugWindowPageAgentSettingsDebugModalR,
  appInitialAppMainDebugWindowPageAgentSettingsDebugModalS,
  appInitialAppMainOnboardingPageAo,
  AppInitialAppMainOnboardingPageAu,
  appInitialAppMainOnboardingPageBp,
  appInitialAppMainOnboardingPageDc,
  appInitialAppMainOnboardingPageDr,
  appInitialAppMainOnboardingPageEo,
  appInitialAppMainOnboardingPageFn,
  AppInitialAppMainOnboardingPageGp,
  AppInitialAppMainOnboardingPageGt,
  appInitialAppMainOnboardingPageIm,
  AppInitialAppMainOnboardingPageIn,
  appInitialAppMainOnboardingPageJo,
  appInitialAppMainOnboardingPageJp,
  appInitialAppMainOnboardingPageKo,
  AppInitialAppMainOnboardingPageKp,
  appInitialAppMainOnboardingPageLo,
  appInitialAppMainOnboardingPageMu,
  appInitialAppMainOnboardingPageNp,
  appInitialAppMainOnboardingPageOo,
  appInitialAppMainOnboardingPagePp,
  appInitialAppMainOnboardingPageQp,
  appInitialAppMainOnboardingPageRm,
  appInitialAppMainOnboardingPageRo,
  appInitialAppMainOnboardingPageRp,
  appInitialAppMainOnboardingPageSc,
  appInitialAppMainOnboardingPageTo,
  appInitialAppMainOnboardingPageUr,
  appInitialAppMainOnboardingPageVp,
  appInitialAppMainOnboardingPageWo,
  appInitialAppMainOnboardingPageWt,
  appInitialAppMainOnboardingPageZp,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wAc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wJo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wM,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wSo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTr,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wU,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wUr,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
  AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dAy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBf,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBl,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dKp,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNv,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dP,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRl,
  AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTv,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVf,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYg,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPagePageAppgenPageRemoteConDi269h6jH,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPagePageAppgenPageRemoteConDi269h6jM,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsAt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsDr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsIt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsJm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsTr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwFs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNf,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwPf,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwPn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkB,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkBt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkFt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkGt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkHt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkJt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkPt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkRn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkUt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkWt,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkY,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkZt,
  approvalPolicyOptions,
  experimentalFeatureElementFactory,
  experimentalFeatureReactRuntime,
  experimentalFeatureRuntimeInit,
  experimentalFeatureVisibilityN,
  experimentalFeatureVisibilityT,
  initAgentSettingsMessages,
  initConfigFileRuntime,
  initExperimentalFeaturesSection,
  initLocationStateSchema,
  initReasoningEffortOptions,
  locationStateSchema,
  modelFeatureElementFactory,
  modelFeatureRuntimeInit,
  openInTargetsQueryN,
  openInTargetsQueryT,
  reasoningEffortOptions,
  rolldownRuntimeN,
  rolldownRuntimeS,
  sandboxModeOptions,
};
export default agentSettingsRuntime;
