// Restored from ref/webview/assets/thread-context-inputs-B6tQCr7t.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 300 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */
import {
  _appScopeC as createComputedSignal,
  _appScopeG as createSignal,
  appScopeRoot,
  appScopeUnderscore,
} from "./app-scope";

const LOCAL_APP_SERVER_HOST_ID = "local";

export const $ = undefined as never;
export const $n = undefined as never;
export const $r = undefined as never;
export const $t = undefined as never;
export const A = undefined as never;
export const Aa = undefined as never;
export const Ai = undefined as never;
export const An = undefined as never;
export const Ar = undefined as never;
export const At = undefined as never;
export const B = undefined as never;
export const Bi = undefined as never;
export const Bn = undefined as never;
export const Br = undefined as never;
export const Bt = undefined as never;
export const Ca = undefined as never;
export const Ci = undefined as never;
export const Cn = undefined as never;
export const Cr = undefined as never;
export const Ct = undefined as never;
export const D = undefined as never;
export const Da = undefined as never;
export const Di = undefined as never;
export const Dn = undefined as never;
export const Dr = undefined as never;
export const Dt = undefined as never;
export const E = undefined as never;
export const Ea = undefined as never;
export const Ei = undefined as never;
export const En = undefined as never;
export const Er = undefined as never;
export const browserUseEnabledForConversationSignal = undefined as never;
export const Et = undefined as never;
export const F = undefined as never;
export const Fi = undefined as never;
export const Fn = undefined as never;
export const Fr = undefined as never;
export const Ft = undefined as never;
export const G = undefined as never;
export const Gi = undefined as never;
export const Gn = undefined as never;
export const Gr = undefined as never;
export const Gt = undefined as never;
export const Hi = undefined as never;
export const Hn = undefined as never;
export const Hr = undefined as never;
export const CHROME_NATIVE_APP_DISPLAY_NAME = undefined as never;
export const Ht = undefined as never;
export const I = undefined as never;
export const Ii = undefined as never;
export const In = undefined as never;
export const Ir = undefined as never;
export const It = undefined as never;
export const J = undefined as never;
export const Ji = undefined as never;
export const Jn = undefined as never;
export const Jr = undefined as never;
export const Jt = undefined as never;
export const K = undefined as never;
export const Ki = undefined as never;
export const Kn = undefined as never;
export const Kr = undefined as never;
export const Kt = undefined as never;
export const L = undefined as never;
export const Li = undefined as never;
export const Ln = undefined as never;
export const Lr = undefined as never;
export const Lt = undefined as never;
export const Mi = undefined as never;
export const Mn = undefined as never;
export const Mr = undefined as never;
export const Mt = undefined as never;
export const N = undefined as never;
export const Ni = undefined as never;
export const Nn = undefined as never;
export const Nr = undefined as never;
export const Nt = undefined as never;
export const O = undefined as never;
export const Oa = undefined as never;
export const Oi = undefined as never;
export const On = undefined as never;
export const Or = undefined as never;
export const Ot = undefined as never;
export const P = undefined as never;
export const Pi = undefined as never;
export const Pn = undefined as never;
export const Pr = undefined as never;
export const Pt = undefined as never;
export const Q = undefined as never;
export const Qn = undefined as never;
export const Qr = undefined as never;
export const Qt = undefined as never;
export const R = undefined as never;
export const Ri = undefined as never;
export const Rn = undefined as never;
export const Rr = undefined as never;
export const Rt = undefined as never;
export const S = undefined as never;
export const Sa = undefined as never;
export const Si = undefined as never;
export const Sn = undefined as never;
export const Sr = undefined as never;
export const St = undefined as never;
export const T = undefined as never;
export const Ti = undefined as never;
export const Tn = undefined as never;
export const Tr = undefined as never;
export const Tt = undefined as never;
export const U = undefined as never;
export const Ui = undefined as never;
export const Un = undefined as never;
export const Ur = undefined as never;
export const isChromeNativeApp = undefined as never;
export const Ut = undefined as never;
export const V = undefined as never;
export const Vi = undefined as never;
export const Vn = undefined as never;
export const Vr = undefined as never;
export const Vt = undefined as never;
export const W = undefined as never;
export const Wi = undefined as never;
export const Wn = undefined as never;
export const Wr = undefined as never;
export const Wt = undefined as never;
export const X = undefined as never;
export const Xi = undefined as never;
export const Xn = undefined as never;
export const Xr = undefined as never;
export const Xt = undefined as never;
export const Y = undefined as never;
export const Yi = undefined as never;
export const Yn = undefined as never;
export const Yr = undefined as never;
export const Yt = undefined as never;
export const Z = undefined as never;
export const Zi = undefined as never;
export const Zn = undefined as never;
export const Zr = undefined as never;
export const Zt = undefined as never;
export const _a = undefined as never;
export const _i = undefined as never;
export const _n = undefined as never;
export const _r = undefined as never;
export const _t = undefined as never;
export const a = undefined as never;
export const aa = undefined as never;
export const ai = undefined as never;
export const an = undefined as never;
export const ar = undefined as never;
export const at = undefined as never;
export const ba = undefined as never;
export const bi = undefined as never;
export const bn = undefined as never;
export const br = undefined as never;
export const bt = undefined as never;
export const ca = undefined as never;
export const ci = undefined as never;
export const cn = undefined as never;
export const cr = undefined as never;
export const ct = undefined as never;
export const d = undefined as never;
export const da = undefined as never;
export const di = undefined as never;
export const dr = undefined as never;
export const dt = undefined as never;
export const ei = undefined as never;
export const en = undefined as never;
export const er = undefined as never;
export const et = undefined as never;
export const f = undefined as never;
export const fa = undefined as never;
export const fi = undefined as never;
export const fn = undefined as never;
export const fr = undefined as never;
export const ft = undefined as never;
export const g = undefined as never;
export const ga = undefined as never;
export const gi = undefined as never;
export const gn = undefined as never;
export const gr = undefined as never;
export const ha = undefined as never;
export const hi = undefined as never;
export const hn = undefined as never;
export const hr = undefined as never;
export const ht = undefined as never;
export const i = undefined as never;
export const ia = undefined as never;
export const ii = undefined as never;
const in_: any = undefined as any;
export { in_ as in };
export const ir = undefined as never;
export const it = undefined as never;
export const ji = undefined as never;
export const jn = undefined as never;
export const jr = undefined as never;
export const jt = undefined as never;
export const k = undefined as never;
export const ka = undefined as never;
export const ki = undefined as never;
export const kn = undefined as never;
export const kr = undefined as never;
export const kt = undefined as never;
export const l = undefined as never;
export const la = undefined as never;
export const li = undefined as never;
export const ln = undefined as never;
export const lr = undefined as never;
export const lt = undefined as never;
export const ma = undefined as never;
export const mi = undefined as never;
export const mn = undefined as never;
export const mr = undefined as never;
export const mt = undefined as never;
export const na = undefined as never;
export const ni = undefined as never;
export const nn = undefined as never;
export const nr = undefined as never;
export const nt = undefined as never;
export const o = undefined as never;
export const oa = undefined as never;
export const oi = undefined as never;
export const on = undefined as never;
export const or = undefined as never;
export const ot = undefined as never;
export const pa = undefined as never;
export const pi = undefined as never;
export const pr = undefined as never;
export const pt = undefined as never;
export const q = undefined as never;
export const qi = undefined as never;
export const qn = undefined as never;
export const qr = undefined as never;
export const qt = undefined as never;
export const r = undefined as never;
export const ra = undefined as never;
export const ri = undefined as never;
export const rn = undefined as never;
export const rr = undefined as never;
export const rt = undefined as never;
export const sa = undefined as never;
export const si = undefined as never;
export const sn = undefined as never;
export const sr = undefined as never;
export const st = undefined as never;
export const t = undefined as never;
export const ti = undefined as never;
export const tn = undefined as never;
export const tr = undefined as never;
export const tt = undefined as never;
export const u = undefined as never;
export const ua = undefined as never;
export const ui = undefined as never;
export const un = undefined as never;
export const ur = undefined as never;
export const ut = undefined as never;
export const va = undefined as never;
export const vi = undefined as never;
export const vn = undefined as never;
export const vr = undefined as never;
export const vt = undefined as never;
export const w = undefined as never;
export const wa = undefined as never;
export const wi = undefined as never;
export const wn = undefined as never;
export const wr = undefined as never;
export const x = undefined as never;
export const xa = undefined as never;
export const xi = undefined as never;
export const xn = undefined as never;
export const xr = undefined as never;
export const xt = undefined as never;
export const ya = undefined as never;
export const yi = undefined as never;
export const yn = undefined as never;
export const yr = undefined as never;
export const yt = undefined as never;
export const z = undefined as never;
export const zi = undefined as never;
export const zn = undefined as never;
export const zr = undefined as never;
export const zt = undefined as never;

export function applyRemoteControlHostStatus(
  scope: AppScopeStoreLike,
  hostId: string,
  status: unknown,
): void {
  scope.set(remoteControlConnectionStatusSignal, hostId, status);
}
export const codexHomeQuery = undefined as never;
export const conversationPermissionConfigSignal = undefined as never;
export const conversationTitleSignal = undefined as never;
export const conversationTurnsSignal = undefined as never;
export const conversationVisibleTurnsSignal = undefined as never;
export const latestTurnByConversationIdSignal = undefined as never;
export const linkedConversationIdSignal = undefined as never;
export const remoteControlConnectionStatusSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const selectedHostIdSignal = createSignal(
  appScopeRoot,
  LOCAL_APP_SERVER_HOST_ID,
);
export {
  selectedHostIdSignal as M,
  remoteControlConnectionStatusSignal as dn,
  applyRemoteControlHostStatus as pn,
};
export const globalStateSignal = appScopeUnderscore(
  "global-state",
  () => undefined,
);
export { globalStateSignal as ea };
export const $i = globalStateSignal;
export const c = appScopeUnderscore("remote-projects", () => []);
export const s = appScopeUnderscore("remote-host-configs", () => []);
export const n = appScopeUnderscore("active-workspace-roots", () => ({
  roots: [],
}));
export function ta(store: any, key: string, value: unknown): void {
  store?.query?.setData?.(globalStateSignal, key, { value });
}
export const homeDirectoryQuery = undefined as never;
export const createGitQueryOptions = undefined as never;
export const disabledGitQueryResult = undefined as never;
export const gitRepositoryWatcherSignal = undefined as never;
export const gitStableMetadataQuery = undefined as never;
export const normalizeHostConfigForWorktreeKey = undefined as never;
export const pendingGitQueryResult = undefined as never;
export const resolveGitQueryOptions = undefined as never;
export const serviceClientForHost = undefined as never;
export const trackOnboardingWizardAction = undefined as never;
export const useGitRepositoryQuery = undefined as never;
type AppScopeStoreLike = {
  get<TValue = unknown>(signal: unknown, ...args: unknown[]): TValue;
  set(signal: unknown, ...args: unknown[]): void;
};
type AppServerConnectionUpdate = {
  appServerVersion?: unknown;
  error?: unknown;
  hostId: string;
  installedCodexVersion?: unknown;
  source?: string;
  state: unknown;
};

export const appServerConnectionErrorSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const appServerConnectionStateSignal = appScopeUnderscore(
  appScopeRoot,
  () => "disconnected",
);
export const appServerConnectionManagerSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const appServerVersionSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const installedCodexVersionSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const hostManagerStoreSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const conversationAppServerManagerOverrideSignal = appScopeUnderscore(
  appScopeRoot,
  () => null,
);
export const registeredAppServerHostIdsSignal = createSignal(
  appScopeRoot,
  [] as string[],
);
export const appServerRegistryVersionSignal = createSignal(appScopeRoot, 0);
export const allAppServerManagersSignal = createComputedSignal(
  appScopeRoot,
  ({
    get,
  }: {
    get: <TValue = unknown>(signal: unknown, key?: unknown) => TValue;
  }) =>
    (get<string[]>(registeredAppServerHostIdsSignal) ?? [])
      .map((hostId) => get(appServerConnectionManagerSignal, hostId))
      .filter(Boolean),
);
export const defaultAppServerManagerSignal = createComputedSignal(
  appScopeRoot,
  ({
    get,
  }: {
    get: <TValue = unknown>(signal: unknown, key?: unknown) => TValue;
  }) =>
    get(appServerConnectionManagerSignal, LOCAL_APP_SERVER_HOST_ID) ??
    (get<unknown[]>(allAppServerManagersSignal) ?? [])[0] ??
    null,
);
export function getAppServerConnectionStateForHost(
  scope: AppScopeStoreLike,
  hostId: string,
): {
  appServerVersion: unknown;
  error: any;
  installedCodexVersion: unknown;
  state: any;
} {
  return {
    appServerVersion: scope.get(appServerVersionSignal, hostId),
    error: scope.get(appServerConnectionErrorSignal, hostId),
    installedCodexVersion: scope.get(installedCodexVersionSignal, hostId),
    state: scope.get(appServerConnectionStateSignal, hostId),
  };
}
export function getAppServerManagerForConversationId(
  scope: AppScopeStoreLike,
  conversationId: string,
): unknown {
  return (
    scope.get(conversationAppServerManagerOverrideSignal, conversationId) ??
    scope.get(defaultAppServerManagerSignal)
  );
}
export function setAppServerConnectionState(
  scope: AppScopeStoreLike,
  update: AppServerConnectionUpdate,
): void {
  scope.set(appServerConnectionStateSignal, update.hostId, update.state);
  scope.set(
    appServerConnectionErrorSignal,
    update.hostId,
    update.error ?? null,
  );
  if ("appServerVersion" in update) {
    scope.set(appServerVersionSignal, update.hostId, update.appServerVersion);
  }
  if ("installedCodexVersion" in update) {
    scope.set(
      installedCodexVersionSignal,
      update.hostId,
      update.installedCodexVersion,
    );
  }
}
export function wrapAppServerManager<TManager>(manager: TManager): TManager {
  return manager;
}
export {
  appServerVersionSignal as C,
  installedCodexVersionSignal as H,
  wrapAppServerManager as Ta,
  conversationAppServerManagerOverrideSignal as _,
  appServerRegistryVersionSignal as b,
  registeredAppServerHostIdsSignal as gt,
  hostManagerStoreSignal as h,
  defaultAppServerManagerSignal as j,
  appServerConnectionStateSignal as m,
  appServerConnectionErrorSignal as p,
  appServerConnectionManagerSignal as v,
  setAppServerConnectionState as wt,
  allAppServerManagersSignal as y,
};
export const parseSkillPathMetadata = undefined as never;
export const conversationHostIdByConversationIdSignal = undefined as never;
export const latestCollaborationModeByConversationIdSignal = undefined as never;
export const localThreadSummaryByConversationIdSignal = undefined as never;
export const mcpLoginResultSignal = undefined as never;
export function getGlobalStateValue(
  get: (signal: unknown, key: string) => unknown,
  key: string,
  fallbackValue?: unknown,
): unknown {
  const storedValue = get(globalStateSignal, key);
  if (
    storedValue != null &&
    typeof storedValue === "object" &&
    "value" in storedValue
  ) {
    return (storedValue as { value: unknown }).value;
  }
  return storedValue ?? fallbackValue;
}
export { getGlobalStateValue as Qi };
export const useGitMetadataQuery = undefined as never;
export const workspaceRootOptionsQuery = undefined as never;
export const workspaceRootOptionsQueryForHost = undefined as never;
export const produceImmutableUpdate = undefined as never;
export const formatDebugParamsPreview = undefined as never;
export const applyActiveProfileConfigOverrides = undefined as never;
export const resolveRequestServiceTier = undefined as never;
export const resolveServiceTierPreferenceValue = undefined as never;
export const serviceTierPreferenceSignal = undefined as never;
