// Restored from ref/webview/assets/use-host-config-CiYpjHRj.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts). Large vendored/
// runtime module consumed by many local chunks via short export aliases.
// Every export token is exposed as `any`; replace with real types or
// semantic names (or pass --name-map) as the module is scoped. 133 export token(s).
/* eslint-disable @typescript-eslint/no-explicit-any */
import { callCodexVscodeApi } from "./vscode-api";

export const useHostConfigTn = undefined as never;
export const useHostConfigCn = undefined as never;
export const useHostConfigWn = undefined as never;
export const useHostConfigLn = undefined as never;
export const useHostConfigPn = undefined as never;
export const useHostConfigFn = undefined as never;
export const useHostConfigDn = undefined as never;
export const useHostConfigN = undefined as never;
export const _useHostConfigSn = undefined as never;
export const _useHostConfigTn = undefined as never;
export const useHostConfigRn = undefined as never;
export const useHostConfigNn = undefined as never;
export const useHostConfigIn = undefined as never;
export const useHostConfigEn = undefined as never;
export const useHostConfigAn = undefined as never;
export const useHostConfigGt = undefined as never;
export const useHostConfigWt = undefined as never;
export const useHostConfigKt = undefined as never;
export const useHostConfigNt = undefined as never;
export const _useHostConfigZt = undefined as never;
export const useHostConfigPt = undefined as never;
export const _useHostConfigWt = undefined as never;
export const useHostConfigTt = undefined as never;
export const useHostConfigDt = undefined as never;
export const useHostConfigMt = undefined as never;
export const useHostConfigCt = undefined as never;
export const _useHostConfigBt = undefined as never;
export const _useHostConfigYt = undefined as never;
export const _useHostConfigCt = undefined as never;
export const _useHostConfigOt = undefined as never;
export const _useHostConfigRt = undefined as never;
export const _useHostConfigNt = undefined as never;
export const _useHostConfigTt = undefined as never;
export const _useHostConfigEt = undefined as never;
export const useHostConfigX = undefined as never;
export const useHostConfigZ = undefined as never;
export const useHostConfigU = undefined as never;
export const useHostConfigH = undefined as never;
export const useHostConfigG = undefined as never;
export const useHostConfigM = undefined as never;
export const useHostConfigR = undefined as never;
export const _useHostConfigJ = undefined as never;
export const useHostConfigI = undefined as never;
export const _useHostConfigK = undefined as never;
export const __useHostConfigT = undefined as never;
export const useHostConfigO = undefined as never;
export const useHostConfigS = undefined as never;
export const _useHostConfigW = undefined as never;
export const useHostConfigC = undefined as never;
export const _useHostConfigV = undefined as never;
export const useHostConfigUnderscore = undefined as never;
export const _useHostConfigH = undefined as never;
export const _useHostConfigM = undefined as never;
export const _useHostConfigU = undefined as never;
export const _useHostConfigL = undefined as never;
export function _useHostConfigS(
  _get: (signal: unknown, key?: string) => unknown,
  _key: string,
): unknown {
  return undefined;
}
export { _useHostConfigS as Z, _useHostConfigS as s };
export const _useHostConfigI = undefined as never;
export const __useHostConfigN = undefined as never;
export const $ = undefined as never;
export const $t = undefined as never;
export const useHostConfigA = undefined as never;
export const useHostConfigAt = undefined as never;
export const useHostConfigB = undefined as never;
export const useHostConfigD = undefined as never;
export const useHostConfigE = undefined as never;
export const useHostConfigEt = undefined as never;
export const useHostConfigF = undefined as never;
export const useHostConfigFt = undefined as never;
export const useHostConfigHt = undefined as never;
export const useHostConfigIt = undefined as never;
export const useHostConfigJ = undefined as never;
export const useHostConfigJt = undefined as never;
export const useHostConfigK = undefined as never;
export const useHostConfigL = undefined as never;
export const useHostConfigLt = undefined as never;
export const _useHostConfigN = undefined as never;
export const useHostConfigOt = undefined as never;
export const useHostConfigP = undefined as never;
export const useHostConfigQ = undefined as never;
export const useHostConfigQt = undefined as never;
export const useHostConfigRt = undefined as never;
export const useHostConfigSn = undefined as never;
export const useHostConfigSt = undefined as never;
export const useHostConfigUt = undefined as never;
export const useHostConfigV = undefined as never;
export const useHostConfigVt = undefined as never;
export const useHostConfigW = undefined as never;
export const useHostConfigXt = undefined as never;
export const useHostConfigY = undefined as never;
export const useHostConfigYt = undefined as never;
export const useHostConfigZt = undefined as never;
export const _t = undefined as never;
export const _useHostConfigA = undefined as never;
export const at = undefined as never;
export const _useHostConfigB = undefined as never;
export const useHostConfigBn = undefined as never;
export const _useHostConfigC = undefined as never;
export const _useHostConfigCn = undefined as never;
export const _useHostConfigD = undefined as never;
export const _useHostConfigDt = undefined as never;
export const _useHostConfigF = undefined as never;
export const _useHostConfigFt = undefined as never;
export const _useHostConfigG = undefined as never;
export const useHostConfigGn = undefined as never;
export const _useHostConfigGt = undefined as never;
export const useHostConfigHn = undefined as never;
export const _useHostConfigHt = undefined as never;
export const _useHostConfigIt = undefined as never;
export const _useHostConfigJt = undefined as never;
export const _useHostConfigKt = undefined as never;
export const _useHostConfigLt = undefined as never;
export const useHostConfigMn = undefined as never;
export function _useHostConfigMt(
  hostConfigs: Array<{ id?: string; hostId?: string }> | null | undefined,
  hostId: string | null | undefined,
): unknown {
  if (hostId == null) return null;
  return (
    hostConfigs?.find((hostConfig) => {
      return hostConfig.id === hostId || hostConfig.hostId === hostId;
    }) ?? null
  );
}
export const _useHostConfigO = undefined as never;
export const on = undefined as never;
export const _useHostConfigP = undefined as never;
export const _useHostConfigPt = undefined as never;
export const _useHostConfigQ = undefined as never;
export const _useHostConfigQt = undefined as never;
export const _useHostConfigR = undefined as never;
export const _useHostConfigSt = undefined as never;
export const ___useHostConfigT = undefined as never;
export const useHostConfigUn = undefined as never;
export const _useHostConfigUt = undefined as never;
export const useHostConfigVn = undefined as never;
export const _useHostConfigVt = undefined as never;
export const _useHostConfigX = undefined as never;
export const useHostConfigXn = undefined as never;
export const _useHostConfigXt = undefined as never;
export const _useHostConfigY = undefined as never;
export const useHostConfigYn = undefined as never;

type AppServerRequestHandler = (
  method: string,
  params?: Record<string, unknown>,
) => Promise<unknown> | unknown;

let appServerRequestHandler: AppServerRequestHandler | null = null;

export function setAppServerRequestHandler(
  handler: AppServerRequestHandler | null,
): () => void {
  appServerRequestHandler = handler;
  return () => {
    if (appServerRequestHandler === handler) appServerRequestHandler = null;
  };
}

export async function sendAppServerRequest(
  method: string,
  params: Record<string, unknown> = {},
): Promise<unknown> {
  if (appServerRequestHandler != null) {
    return appServerRequestHandler(method, params);
  }
  return callCodexVscodeApi("handle-app-server-request-for-host", {
    method,
    params,
    hostId: params.hostId,
  });
}

export const useHostConfigBt = sendAppServerRequest;
export { sendAppServerRequest as Bt };
export const formatGoalObjectiveInput = undefined as never;
export const useRemoteHostConnections = undefined as never;
export const useHostConfigById = _useHostConfigMt;
export const isBrowserCommentAttachment = undefined as never;
export const LOCAL_HOST_ID = "local";
export const _useHostConfigZ = undefined as never;
export const getLatestTurn = undefined as never;
export const getLatestWaitingRequest = undefined as never;
export const getThreadTitle = undefined as never;
export const getThreadTurnCount = undefined as never;
export const getThreadTurns = undefined as never;
export const hasWaitingApprovalRequest = undefined as never;
export const isSubAgentThread = undefined as never;
export const shouldHideSubAgentThread = undefined as never;
export const markdownToSearchText = undefined as never;
export const parseHeartbeatMessage = undefined as never;
export const infiniteQueryBehavior = undefined as never;
export const getConversationPromptTitle = undefined as never;
export const getConversationTitleFromSnapshot = undefined as never;
export const useSharedObjectState = undefined as never;
export function getWorkspaceRelativePath(
  filePath: string,
  workspaceRoot?: string | null,
): string {
  if (workspaceRoot == null || workspaceRoot === "") return filePath;
  const normalizedFilePath = filePath.replaceAll("\\", "/");
  const normalizedWorkspaceRoot = workspaceRoot
    .replaceAll("\\", "/")
    .replace(/\/+$/, "");
  if (normalizedFilePath === normalizedWorkspaceRoot) return ".";
  const prefix = `${normalizedWorkspaceRoot}/`;
  return normalizedFilePath.startsWith(prefix)
    ? normalizedFilePath.slice(prefix.length)
    : filePath;
}

export const useHostConfigLegacyTt = __useHostConfigT;
export const useHostConfigLegacyUnderscore = __useHostConfigN;
export const useHostConfigLegacyW = ___useHostConfigT;
