// Restored from ref/webview/assets/workbook-C3Zy6Twd.js
//
// TYPED BOUNDARY FACADE (generated by scripts/make-facade.ts).
// Typed boundary facade for the bundled workbook runtime. The implementation is
// still parked in the original bundle; this file exposes the current minified
// export surface with broad callable/constructable types so downstream restored
// modules do not depend on untyped escape hatches.

export type WorkbookRuntimeRecord = {
  [key: string]: WorkbookRuntimeValue;
  [key: number]: WorkbookRuntimeValue;
};

export type WorkbookRuntimeValue =
  | WorkbookRuntimeRecord
  | string
  | number
  | boolean
  | bigint
  | symbol
  | null
  | undefined;

export type WorkbookRuntimeExport = {
  (...args: Array<unknown>): WorkbookRuntimeValue;
  new (...args: Array<unknown>): WorkbookRuntimeRecord;
  [key: string]: WorkbookRuntimeValue;
  [key: number]: WorkbookRuntimeValue;
};

export type WorkbookRuntimeInitializer = () => void;

export declare const $: WorkbookRuntimeExport;
export declare const A: WorkbookRuntimeExport;
export declare const B: WorkbookRuntimeExport;
export declare const C: WorkbookRuntimeExport;
export declare const Ct: WorkbookRuntimeExport;
export declare const D: WorkbookRuntimeExport;
export declare const Dt: WorkbookRuntimeExport;
export declare const E: WorkbookRuntimeExport;
export declare const Et: WorkbookRuntimeExport;
export declare const F: WorkbookRuntimeExport;
export declare const getAppServerConnectionStateForHost: WorkbookRuntimeExport;
export declare const G: WorkbookRuntimeExport;
export declare const H: WorkbookRuntimeExport;
export declare const I: WorkbookRuntimeExport;
export declare const getAppServerManagerForConversationId: WorkbookRuntimeExport;
export declare const J: WorkbookRuntimeExport;
export declare const K: WorkbookRuntimeExport;
export declare const L: WorkbookRuntimeExport;
export declare const M: WorkbookRuntimeExport;
export declare const N: WorkbookRuntimeExport;
export declare const O: WorkbookRuntimeExport;
export declare const P: WorkbookRuntimeExport;
export declare const Q: WorkbookRuntimeExport;
export declare const workbookQ: WorkbookRuntimeExport;
export declare const R: WorkbookRuntimeExport;
export declare const S: WorkbookRuntimeExport;
export declare const St: WorkbookRuntimeExport;
export declare const T: WorkbookRuntimeExport;
export declare const Tt: WorkbookRuntimeExport;
export declare const U: WorkbookRuntimeExport;
export declare const V: WorkbookRuntimeExport;
export declare const W: WorkbookRuntimeExport;
export declare const X: WorkbookRuntimeExport;
export declare const Y: WorkbookRuntimeExport;
export declare const Z: WorkbookRuntimeExport;
export declare const _: WorkbookRuntimeExport;
export declare const _t: WorkbookRuntimeExport;
export declare const a: WorkbookRuntimeExport;
export declare const at: WorkbookRuntimeExport;
export declare const b: WorkbookRuntimeExport;
export declare const bt: WorkbookRuntimeExport;
export declare const c: WorkbookRuntimeExport;
export declare const ct: WorkbookRuntimeExport;
export declare const d: WorkbookRuntimeExport;
export declare const dt: WorkbookRuntimeExport;
export declare const et: WorkbookRuntimeExport;
export declare const f: WorkbookRuntimeExport;
export declare const ft: WorkbookRuntimeExport;
export declare const g: WorkbookRuntimeExport;
export declare const gt: WorkbookRuntimeExport;
export declare const h: WorkbookRuntimeExport;
export declare const ht: WorkbookRuntimeExport;
export declare const i: WorkbookRuntimeExport;
export declare const it: WorkbookRuntimeExport;
export declare const j: WorkbookRuntimeExport;
export declare const k: WorkbookRuntimeExport;
export declare const l: WorkbookRuntimeExport;
export declare const lt: WorkbookRuntimeExport;
export declare const m: WorkbookRuntimeExport;
export declare const mt: WorkbookRuntimeExport;
export declare const n: WorkbookRuntimeInitializer;
export declare const nt: WorkbookRuntimeExport;
export declare const o: WorkbookRuntimeExport;
export declare const ot: WorkbookRuntimeExport;
export declare const p: WorkbookRuntimeExport;
export declare const pt: WorkbookRuntimeExport;
export declare const q: WorkbookRuntimeExport;
export declare const r: WorkbookRuntimeExport;
export declare const rt: WorkbookRuntimeExport;
export declare const s: WorkbookRuntimeExport;
export declare const st: WorkbookRuntimeExport;
export declare const t: WorkbookRuntimeExport;
export declare const tt: WorkbookRuntimeExport;
export declare const u: WorkbookRuntimeExport;
export declare const ut: WorkbookRuntimeExport;
export declare const v: WorkbookRuntimeExport;
export declare const vt: WorkbookRuntimeExport;
export declare const w: WorkbookRuntimeExport;
export declare const wt: WorkbookRuntimeExport;
export declare const x: WorkbookRuntimeExport;
export declare const xt: WorkbookRuntimeExport;
export declare const y: WorkbookRuntimeExport;
export declare const yt: WorkbookRuntimeExport;
export declare const z: WorkbookRuntimeExport;
