// Restored from ref/webview/assets/local-conversation-page-C379OsPf.js
// Local conversation page container runtime bindings and side-effect helpers.
import { initIntlMessageRuntime } from "../runtime/intl-message-runtime";

import { initMotionRuntime } from "../utils/motion-signal-runtime";

import { initGlobalStateQueryRuntime } from "../runtime/global-state-runtime";

import {
  initReactRuntime,
  getChunkModuleExports,
} from "../runtime/shared-utility-runtime";
import { backgroundAgentSnapshotSignal } from "../runtime/background-agent-state-runtime";
import {
  initAppServerRequestRuntime as initAppServerRequestBridge,
  sendAppServerRequest,
} from "../runtime/app-server-request";
import { normalizeConfigPath } from "../runtime/config-path-runtime";
import { useStatsigGate } from "../runtime/feature-gate-runtime";

import { initVscodeBridgeRuntime as initVscodeApiBridge } from "../runtime/platform-content-runtime";

import {
  normalizeConversationId as toConversationId,
  normalizeWorkspacePath,
} from "../boundaries/src-l0hb-mz-p";
import {
  appScope,
  createDerivedSignal,
  initAppScope,
  initScopeRuntime,
} from "../runtime/app-scope-runtime";
import {
  useScope,
  useScopedValue,
  useSignalValue,
} from "../runtime/app-scope-hooks";
import { initReactQueryRuntime } from "../runtime/app-server-mutation-runtime";
import {
  Sl as activeWorkspaceDiffSignal,
  nc as appShellIntlSignal,
  $r as clearRestoredWorkspaceRoot,
  fl as reviewSourceSignal,
  hl as resetReviewSource,
  Vn as initProjectsAppSharedRuntime,
  Gl as localConversationTitleSignal,
  ml as shouldRestoreReviewStateSignal,
  Kr as openWorkspaceDiffPanelTab,
  Yt as openWorkspaceFilePanelTab,
  pd as setRightPanelFullWidth,
  Tr as pendingClientLocalConversationSignal,
  pl as reviewSourceWorkspaceRootSignal,
  rd as rightPanelVisibleSignal,
  Yl as rightPanelController,
  nd as rightPanelOpenSignal,
  ql as rightPanelTabController,
  j as selectedSummaryPanelSignal,
  N as setSelectedSummarySource,
  md as summaryPanelPinnedSignal,
  Ll as targetWorkspaceRootSignal,
  Bn as ThreadAppShellLayout,
  ul as setReviewSourceFromLastTurn,
  zc as reviewPaneSnapshotMetricsSignal,
  zl as activeHostIdSignal,
  A_ as appShellTabIds,
  Em as conversationTurnsSignal,
  Gp as conversationReasoningEffortSignal,
  Hp as lastTurnCwdSignal,
  I_ as initRouteScope,
  Ip as localResponseInProgressSignal,
  M_ as localConversationRouteScope,
  O_ as initConversationRouteSourceHelpers,
  Rp as appServerNotificationSignal,
  T_ as getRouteConversationId,
  Tp as hasConversationSignal,
  Wp as conversationModelSignal,
  Xp as latestConversationTurnSignal,
  Vp as lastTurnDiffSignal,
  cm as conversationHostIdSignal,
  cv as sourceWorkspaceRootAfterRestoreSignal,
  gp as conversationCwdSignal,
  jm as conversationModeSignal,
  lm as conversationResumeStateSignal,
  mv as initCurrentRefViewRuntime,
  sm as conversationRequestsSignal,
  sv as pendingProjectlessLocalConversationSignal,
  um as rolloutPathSignal,
  vm as subagentParentThreadIdSignal,
  yv as Navigate,
} from "../vendor/projects-app-shared-runtime";
import { ea as ProjectAvatar } from "../vendor/worktree-new-thread-query-current-bundle";
import {
  AutomationTooltipSurface,
  ComposerDismissableLayer,
  initAutomationSurface,
} from "../automation/automation-surface";
import {
  clearSelectedSummarySource,
  getRenderableTurnItems,
  getTurnAgentItemGroups,
  isConversationItemInProgress,
  LocalConversationTurnRow,
  resolveRenderableAgentItems,
  WorkedForCollapsedAgentsLabel,
} from "./local-conversation-profile-runtime";
import {
  getProjectAppearance,
  initProjectAppearanceChunk,
} from "../projects/project-appearance";
import {
  AppgenProjectHeader,
  initAppgenProjectHeaderChunk,
} from "../appgen/project-header";
import {
  createDebugPanelSourceId,
  getEditedFilesFromTurns,
  getReferencedFilesFromTurns,
  initDebugPanelRuntime,
  initDebugPanelSourceRuntime,
  registerDebugPanelSource,
  unregisterDebugPanelSource,
  useIsDebugPanelEnabled,
} from "../debug/debug-panel";
import {
  initPendingWorktreeChunk,
  PendingWorktreeConversation,
} from "../worktree/pending-worktree-conversation-ui";
import {
  focusPendingReviewPanelTarget,
  initPullRequestThreadActionsChunk,
  openInitialReviewPanelTarget,
  pendingReviewPanelTargetSignal,
  resetReviewPanelEmptyState,
  revealChangedFilesInReviewPanel,
  scheduleReviewRestore,
  shouldExpandReviewPanelSignal,
  syncReviewPanelForRestoredSource,
} from "./pull-request-review-panel-actions";
import {
  initConnectorAppsRuntime as initConnectorAppsListQuery,
  useAppsQuery,
} from "../runtime/connector-apps-runtime";
import { useCommandRegistration } from "../runtime/command-registration-runtime";

export {
  activeHostIdSignal,
  activeWorkspaceDiffSignal,
  appScope,
  appServerNotificationSignal,
  appShellIntlSignal,
  appShellTabIds,
  AppgenProjectHeader,
  AutomationTooltipSurface,
  backgroundAgentSnapshotSignal,
  clearRestoredWorkspaceRoot,
  clearSelectedSummarySource,
  ComposerDismissableLayer,
  conversationCwdSignal,
  conversationHostIdSignal,
  conversationModeSignal,
  conversationModelSignal,
  conversationReasoningEffortSignal,
  conversationRequestsSignal,
  conversationResumeStateSignal,
  conversationTurnsSignal,
  createDebugPanelSourceId,
  createDerivedSignal,
  focusPendingReviewPanelTarget,
  getChunkModuleExports,
  getEditedFilesFromTurns,
  getProjectAppearance,
  getReferencedFilesFromTurns,
  getRenderableTurnItems,
  getRouteConversationId,
  getTurnAgentItemGroups,
  hasConversationSignal,
  initAppScope,
  initAppgenProjectHeaderChunk,
  initAppServerRequestBridge,
  initAutomationSurface,
  initConnectorAppsListQuery,
  initConversationRouteSourceHelpers,
  initCurrentRefViewRuntime,
  initDebugPanelRuntime,
  initDebugPanelSourceRuntime,
  initGlobalStateQueryRuntime,
  initIntlMessageRuntime,
  initMotionRuntime,
  initPendingWorktreeChunk,
  initProjectAppearanceChunk,
  initProjectsAppSharedRuntime,
  initPullRequestThreadActionsChunk,
  initReactQueryRuntime,
  initReactRuntime,
  initRouteScope,
  initScopeRuntime,
  initVscodeApiBridge,
  isConversationItemInProgress,
  lastTurnCwdSignal,
  lastTurnDiffSignal,
  latestConversationTurnSignal,
  localConversationRouteScope,
  localConversationTitleSignal,
  localResponseInProgressSignal,
  LocalConversationTurnRow,
  Navigate,
  normalizeConfigPath,
  normalizeWorkspacePath,
  openInitialReviewPanelTarget,
  openWorkspaceDiffPanelTab,
  openWorkspaceFilePanelTab,
  pendingClientLocalConversationSignal,
  pendingProjectlessLocalConversationSignal,
  pendingReviewPanelTargetSignal,
  PendingWorktreeConversation,
  ProjectAvatar,
  registerDebugPanelSource,
  resetReviewPanelEmptyState,
  resetReviewSource,
  resolveRenderableAgentItems,
  revealChangedFilesInReviewPanel,
  reviewPaneSnapshotMetricsSignal,
  reviewSourceSignal,
  reviewSourceWorkspaceRootSignal,
  rightPanelController,
  rightPanelOpenSignal,
  rightPanelTabController,
  rightPanelVisibleSignal,
  rolloutPathSignal,
  scheduleReviewRestore,
  selectedSummaryPanelSignal,
  sendAppServerRequest,
  setReviewSourceFromLastTurn,
  setRightPanelFullWidth,
  setSelectedSummarySource,
  shouldExpandReviewPanelSignal,
  shouldRestoreReviewStateSignal,
  sourceWorkspaceRootAfterRestoreSignal,
  subagentParentThreadIdSignal,
  summaryPanelPinnedSignal,
  syncReviewPanelForRestoredSource,
  targetWorkspaceRootSignal,
  ThreadAppShellLayout,
  toConversationId,
  unregisterDebugPanelSource,
  useAppsQuery,
  useCommandRegistration,
  useIsDebugPanelEnabled,
  useScope,
  useScopedValue,
  useSignalValue,
  useStatsigGate,
  WorkedForCollapsedAgentsLabel,
};
