// Restored from ref/webview/assets/config-queries-C2OQQYPH.js
// Host config, analytics, MCP server, and MCP resource query helpers.
import {
  ANALYTICS_CONFIG_QUERY_KEY,
  CONFIG_QUERY_STALE_TIME,
  CONFIG_REQUIREMENTS_QUERY_KEY,
  EFFECTIVE_CONFIG_QUERY_KEY,
  LAYERED_CONFIG_RESPONSE_QUERY_KEY,
  MCP_SERVERS_CONFIG_QUERY_KEY,
  MCP_SERVER_STATUS_QUERY_KEY,
  READ_CONFIG_RESPONSE_QUERY_KEY,
  USER_CONFIG_QUERY_KEY,
  configRequirementsQueryOptions,
  findConfigOrigin,
  getConfigLayerFilePath,
  getUserConfigWriteTargetFromQueryClient,
  isReadOnlyConfigLayer,
  mcpServerStatusFullQueryOptions,
  mcpServerStatusToolsAndAuthQueryOptions,
  readConfigForHost,
  useAnalyticsEnabledQuery,
  useEffectiveConfigQuery,
  useLocalCustomAgents,
  useMcpResourceQuery,
  useMcpServersConfigQuery,
  useToggleMcpServerEnabledMutation,
  useWriteMcpServerConfigMutation,
  userConfigQueryOptions,
} from "./public-api";
export {
  userConfigQueryOptions,
  useWriteMcpServerConfigMutation,
  useLocalCustomAgents,
  MCP_SERVERS_CONFIG_QUERY_KEY,
  useMcpResourceQuery,
  configRequirementsQueryOptions,
  getConfigLayerFilePath,
  isReadOnlyConfigLayer,
  useAnalyticsEnabledQuery,
  findConfigOrigin,
  CONFIG_QUERY_STALE_TIME,
  readConfigForHost,
  mcpServerStatusFullQueryOptions,
  USER_CONFIG_QUERY_KEY,
  MCP_SERVER_STATUS_QUERY_KEY,
  mcpServerStatusToolsAndAuthQueryOptions,
  LAYERED_CONFIG_RESPONSE_QUERY_KEY,
  ANALYTICS_CONFIG_QUERY_KEY,
  CONFIG_REQUIREMENTS_QUERY_KEY,
  getUserConfigWriteTargetFromQueryClient,
  useEffectiveConfigQuery,
  useToggleMcpServerEnabledMutation,
  EFFECTIVE_CONFIG_QUERY_KEY,
  useMcpServersConfigQuery,
};
