// Restored from ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js
// MCP app/tool activity label maps for app-specific tool registries.
import { buildToolLabels } from "./mcp-tool-label-registry-helper";

const githubToolKeys = [
  "add_comment_to_issue",
  "add_reaction_to_issue_comment",
  "add_reaction_to_pr",
  "add_reaction_to_pr_review_comment",
  "add_review_to_pr",
  "create_blob",
  "create_branch",
  "create_commit",
  "create_file",
  "create_pull_request",
  "create_tree",
  "enable_auto_merge",
  "label_pr",
  "remove_reaction_from_issue_comment",
  "remove_reaction_from_pr",
  "remove_reaction_from_pr_review_comment",
  "reply_to_review_comment",
  "update_issue_comment",
  "update_ref",
  "update_review_comment",
  "check_repo_initialized",
  "compare_commits",
  "download_user_content",
  "fetch",
  "fetch_blob",
  "fetch_commit",
  "fetch_file",
  "fetch_issue",
  "fetch_issue_comments",
  "fetch_pr",
  "fetch_pr_comments",
  "fetch_pr_file_patch",
  "fetch_pr_patch",
  "get_commit_combined_status",
  "get_issue_comment_reactions",
  "get_pr_diff",
  "get_pr_info",
  "get_pr_reactions",
  "get_pr_review_comment_reactions",
  "get_profile",
  "get_repo",
  "get_repo_collaborator_permission",
  "get_user_login",
  "get_users_recent_prs_in_repo",
  "list_installations",
  "list_installed_accounts",
  "list_pr_changed_filenames",
  "list_recent_issues",
  "list_repositories",
  "list_repositories_by_affiliation",
  "list_repositories_by_installation",
  "list_user_org_memberships",
  "list_user_orgs",
  "search",
  "search_branches",
  "search_commits",
  "search_installed_repositories_streaming",
  "search_installed_repositories_v2",
  "search_issues",
  "search_prs",
  "search_repositories",
] as const;

const gmailToolKeys = [
  "apply_labels_to_emails",
  "archive_emails",
  "batch_modify_email",
  "bulk_label_matching_emails",
  "create_draft",
  "create_label",
  "delete_emails",
  "forward_emails",
  "send_draft",
  "send_email",
  "update_draft",
  "batch_read_email",
  "get_profile",
  "get_recent_emails",
  "list_drafts",
  "list_labels",
  "read_attachment",
  "read_email",
  "read_email_thread",
  "search_email_ids",
  "search_emails",
] as const;

const googleCalendarToolKeys = [
  "create_event",
  "delete_event",
  "respond_event",
  "update_event",
  "batch_read_event",
  "fetch",
  "get_availability",
  "get_profile",
  "read_event",
  "read_event_all_fields",
  "search",
  "search_events",
  "search_events_all_fields",
] as const;

const googleDriveToolKeys = [
  "batch_update_document",
  "batch_update_presentation",
  "batch_update_spreadsheet",
  "copy_file",
  "create_file",
  "create_folder",
  "create_presentation_from_template",
  "delete_file",
  "duplicate_sheet_in_new_spreadsheet",
  "import_presentation",
  "share_file",
  "export_file",
  "fetch",
  "find_document_text_range",
  "get_document",
  "get_document_comments",
  "get_document_paragraph_range",
  "get_document_tables",
  "get_document_text",
  "get_file_metadata",
  "get_presentation",
  "get_presentation_comments",
  "get_presentation_outline",
  "get_presentation_tables",
  "get_presentation_text",
  "get_profile",
  "get_slide",
  "get_slide_thumbnail",
  "get_spreadsheet_cells",
  "get_spreadsheet_comments",
  "get_spreadsheet_metadata",
  "get_spreadsheet_range",
  "list_drives",
  "list_folder",
  "recent_documents",
  "search",
  "search_spreadsheet_rows",
] as const;

const linearToolKeys = [
  "create_attachment",
  "create_document",
  "create_issue_label",
  "delete_attachment",
  "delete_comment",
  "delete_customer",
  "delete_customer_need",
  "delete_status_update",
  "research",
  "save_comment",
  "save_customer",
  "save_customer_need",
  "save_initiative",
  "save_issue",
  "save_milestone",
  "save_project",
  "save_status_update",
  "update_document",
  "extract_images",
  "fetch",
  "get_attachment",
  "get_document",
  "get_initiative",
  "get_issue",
  "get_issue_status",
  "get_milestone",
  "get_project",
  "get_status_updates",
  "get_team",
  "get_user",
  "list_comments",
  "list_customers",
  "list_cycles",
  "list_documents",
  "list_initiatives",
  "list_issue_labels",
  "list_issue_statuses",
  "list_issues",
  "list_milestones",
  "list_project_labels",
  "list_projects",
  "list_teams",
  "list_users",
  "search",
  "search_documentation",
] as const;

export const browserMcpToolLabels = buildToolLabels({
  appId: "browser",
  aliases: ["browser"],
  descriptionApp: "Browser",
  overrides: {
    run_code_unsafe: {
      active: "Running JavaScript",
      completed: "Ran JavaScript",
    },
  },
  toolKeys: ["run_code_unsafe"],
});

export const figmaMcpToolLabels = buildToolLabels({
  appId: "figma",
  aliases: ["figma"],
  descriptionApp: "figma",
  overrides: {
    generate_diagram: {
      active: "Generating diagram",
      completed: "Generated diagram",
    },
    get_design_context: {
      active: "Getting design context",
      completed: "Got design context",
    },
    get_metadata: {
      active: "Getting metadata",
      completed: "Got metadata",
    },
    get_screenshot: {
      active: "Getting screenshot",
      completed: "Got screenshot",
    },
  },
  toolKeys: [
    "generate_diagram",
    "get_design_context",
    "get_metadata",
    "get_screenshot",
  ],
});

export const githubMcpToolLabels = buildToolLabels({
  appId: "github",
  aliases: ["github"],
  descriptionApp: "github",
  toolKeys: githubToolKeys,
});

export const gmailMcpToolLabels = buildToolLabels({
  appId: "gmail",
  aliases: ["gmail"],
  descriptionApp: "gmail",
  toolKeys: gmailToolKeys,
});

export const googleCalendarMcpToolLabels = buildToolLabels({
  appId: "googleCalendar",
  aliases: ["google_calendar", "googleCalendar"],
  descriptionApp: "googleCalendar",
  toolKeys: googleCalendarToolKeys,
});

export const googleDriveMcpToolLabels = buildToolLabels({
  appId: "googleDrive",
  aliases: ["google_drive", "googleDrive"],
  descriptionApp: "googleDrive",
  toolKeys: googleDriveToolKeys,
});

export const linearMcpToolLabels = buildToolLabels({
  appId: "linear",
  aliases: ["linear", "linear_mcp_server"],
  descriptionApp: "linear",
  toolKeys: linearToolKeys,
});
