// Restored from ref/webview/assets/mention-item-Cs3Au6lU.js
// mention-item-Cs3Au6lU chunk restored from the Codex webview bundle.
import {
  COMPUTER_USE_PLUGIN_NAME,
  classifyMentionHref,
  createAgentMentionItem,
  createAppMentionBaseItem,
  createAppMentionHref,
  createAppMentionItem,
  createMcpResourceMentionHref,
  createPluginMentionBaseItem,
  createPluginMentionHref,
  createPluginMentionItem,
  createSitesProjectHref,
  createSitesProjectMentionMarkdown,
  createSkillMentionBaseItem,
  createSkillMentionItem,
  createSubagentMentionItem,
  createThreadMentionHref,
  formatPluginMentionLabels,
  getMentionDescription,
  getPluginMentionIcon,
  getSkillOrPluginMentionKind,
  isAgentMentionHref,
  isAppMentionHref,
  isPluginMentionHref,
  isSubagentMentionHref,
  parseAgentConversationIdFromHref,
  parseChatGptConversationId,
  parseMcpResourceMentionHref,
  parsePluginMentionId,
  parseSubagentRoleNameFromHref,
  parseThreadIdFromHref,
  pluginMentionMessages,
  slugifyAppMentionName,
  stripMentionTriggerSyntax,
} from "./mention-item-impl";
export {
  isPluginMentionHref,
  createSitesProjectHref,
  isAgentMentionHref,
  createThreadMentionHref,
  getMentionDescription,
  pluginMentionMessages,
  isAppMentionHref,
  parseMcpResourceMentionHref,
  slugifyAppMentionName,
  parsePluginMentionId,
  createSubagentMentionItem,
  createPluginMentionHref,
  createSitesProjectHref as createSitesProjectHrefAlias,
  isAgentMentionHref as isAgentMentionHrefAlias,
  createAppMentionItem,
  stripMentionTriggerSyntax,
  getSkillOrPluginMentionKind,
  parseChatGptConversationId,
  COMPUTER_USE_PLUGIN_NAME,
  isSubagentMentionHref,
  createAppMentionBaseItem,
  getMentionDescription as getMentionDescriptionAlias,
  pluginMentionMessages as pluginMentionMessagesAlias,
  parseAgentConversationIdFromHref,
  createPluginMentionItem,
  createAppMentionHref,
  parseSubagentRoleNameFromHref,
  slugifyAppMentionName as slugifyAppMentionNameAlias,
  createPluginMentionBaseItem,
  getPluginMentionIcon,
  createSitesProjectMentionMarkdown,
  classifyMentionHref,
  formatPluginMentionLabels,
};
