// Restored from ref/webview/assets/app-initial~app-main~onboarding-page-CgNc-Bk2.js
// Generated product-analytics descriptors and enums for the conversational
// onboarding flow.
import type { ProductEventDescriptor } from "../analytics/product-logger";

function protobufEvent($type: string): ProductEventDescriptor {
  return { $type };
}

export const conversationalOnboardingLifecycleEvent = protobufEvent(
  "protobuf_analytics_events.v1.CodexConversationalOnboardingLifecycle",
);

export const conversationalOnboardingAccessEvent = protobufEvent(
  "protobuf_analytics_events.v1.CodexConversationalOnboardingAccess",
);

export const conversationalOnboardingExecutionEvent = protobufEvent(
  "protobuf_analytics_events.v1.CodexConversationalOnboardingExecution",
);

export const conversationalOnboardingRoleEvent = protobufEvent(
  "protobuf_analytics_events.v1.CodexConversationalOnboardingRole",
);

export const conversationalOnboardingTaskEvent = protobufEvent(
  "protobuf_analytics_events.v1.CodexConversationalOnboardingTask",
);

export const ConversationalOnboardingLifecycleAction = {
  COMPLETED: "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_COMPLETED",
  FAILED: "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_FAILED",
  SKIPPED: "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_SKIPPED",
  STARTED: "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_STARTED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_LIFECYCLE_ACTION_UNSPECIFIED",
} as const;

export const ConversationalOnboardingAccessAction = {
  COMPLETED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_COMPLETED",
  DENIED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_DENIED",
  FAILED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_FAILED",
  REQUESTED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_REQUESTED",
  STARTED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_STARTED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_ACTION_UNSPECIFIED",
} as const;

export const ConversationalOnboardingExecutionAction = {
  CANCELLED: "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_CANCELLED",
  COMPLETED: "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_COMPLETED",
  FAILED: "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_FAILED",
  STARTED: "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_STARTED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_EXECUTION_ACTION_UNSPECIFIED",
} as const;

export const ConversationalOnboardingRoleAction = {
  SELECTED: "CODEX_CONVERSATIONAL_ONBOARDING_ROLE_ACTION_SELECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_ROLE_ACTION_UNSPECIFIED",
} as const;

export const ConversationalOnboardingTaskAction = {
  SELECTED: "CODEX_CONVERSATIONAL_ONBOARDING_TASK_ACTION_SELECTED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_TASK_ACTION_UNSPECIFIED",
} as const;

export const ConversationalOnboardingAccessType = {
  CALENDAR_APP: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CALENDAR_APP",
  CSV_PICKER: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_CSV_PICKER",
  DESKTOP: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_DESKTOP",
  MESSAGING_APP: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_MESSAGING_APP",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_ACCESS_TYPE_UNSPECIFIED",
} as const;

export const ConversationalOnboardingTaskType = {
  CSV_CHART: "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_CSV_CHART",
  DESKTOP_NOTE: "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_DESKTOP_NOTE",
  HOLD_NEXT_FREE_HOUR:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_HOLD_NEXT_FREE_HOUR",
  SEND_MESSAGE_TO_SELF:
    "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_SEND_MESSAGE_TO_SELF",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_TASK_TYPE_UNSPECIFIED",
} as const;

export const ConversationalOnboardingFailureKind = {
  COMPLETION_MISSING:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_COMPLETION_MISSING",
  HOST_SERVICE_UNAVAILABLE:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_HOST_SERVICE_UNAVAILABLE",
  PLUGIN_UNAVAILABLE:
    "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_PLUGIN_UNAVAILABLE",
  START_FAILED: "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_START_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
  UNSPECIFIED: "CODEX_CONVERSATIONAL_ONBOARDING_FAILURE_KIND_UNSPECIFIED",
} as const;
