// Restored from ref/webview/assets/app-initial~app-main~onboarding-page-BUwCKIcU.js
// Maps a file path to a syntax-highlighting language id by matching the full
// lowercased basename first, then falling back to extension/suffix matches.

const LANGUAGE_BY_BASENAME = new Map<string, string>([
  [".babelrc", "jsonc"],
  [".babelrc.json", "jsonc"],
  [".devcontainer.json", "jsonc"],
  [".ember-cli", "jsonc"],
  [".envrc", "bash"],
  [".eslintrc", "jsonc"],
  [".eslintrc.json", "jsonc"],
  [".flaskenv", "dotenv"],
  [".hintrc", "jsonc"],
  [".hushlogin", "bash"],
  [".jsfmtrc", "jsonc"],
  [".jshintrc", "jsonc"],
  [".profile", "bash"],
  [".swcrc", "jsonc"],
  [".watchmanconfig", "json"],
  [".xprofile", "bash"],
  [".xsession", "bash"],
  [".xsessionrc", "bash"],
  [".zlogin", "bash"],
  [".zlogout", "bash"],
  [".zprofile", "bash"],
  [".zsh-theme", "bash"],
  [".zshenv", "bash"],
  [".zshrc", "bash"],
  ["apkbuild", "bash"],
  ["appfile", "ruby"],
  ["appraisals", "ruby"],
  ["argv.json", "jsonc"],
  ["babel.config.json", "jsonc"],
  ["bashrc_apple_terminal", "bash"],
  ["berksfile", "ruby"],
  ["berksfile.lock", "ruby"],
  ["brewfile", "ruby"],
  ["bun.lock", "jsonc"],
  ["capfile", "ruby"],
  ["cheffile", "ruby"],
  ["codeowners", "codeowners"],
  ["composer.lock", "json"],
  ["containerfile", "dockerfile"],
  ["dangerfile", "ruby"],
  ["deliverfile", "ruby"],
  ["devcontainer.json", "jsonc"],
  ["extensions.json", "jsonc"],
  ["fastfile", "ruby"],
  ["gemfile", "ruby"],
  ["git-rebase-todo", "git-rebase"],
  ["gnumakefile", "makefile"],
  ["guardfile", "ruby"],
  ["gymfile", "ruby"],
  ["jakefile", "javascript"],
  ["jenkinsfile", "groovy"],
  ["jsconfig.json", "jsonc"],
  ["keybindings.json", "jsonc"],
  ["language-configuration.json", "jsonc"],
  ["launch.json", "jsonc"],
  ["mcp.json", "jsonc"],
  ["merge_msg", "git-commit"],
  ["ocamlmakefile", "makefile"],
  ["pkgbuild", "bash"],
  ["podfile", "ruby"],
  ["profiles.json", "jsonc"],
  ["puppetfile", "ruby"],
  ["rakefile", "ruby"],
  ["rantfile", "ruby"],
  ["sconscript", "python"],
  ["sconstruct", "python"],
  ["settings.json", "jsonc"],
  ["snapfile", "ruby"],
  ["tasks.json", "jsonc"],
  ["thorfile", "ruby"],
  ["tsconfig.json", "jsonc"],
  ["typedoc.json", "jsonc"],
  ["user-dirs.dirs", "dotenv"],
  ["vagrantfile", "ruby"],
  ["zlogin", "bash"],
  ["zlogout", "bash"],
  ["zprofile", "bash"],
  ["zshenv", "bash"],
  ["zshrc", "bash"],
]);

const LANGUAGE_BY_SUFFIX = new Map<string, string>([
  [".agent.md", "markdown"],
  [".aspx", "html"],
  [".bash_aliases", "bash"],
  [".bash_login", "bash"],
  [".bash_logout", "bash"],
  [".bash_profile", "bash"],
  [".bashrc", "bash"],
  [".bowerrc", "json"],
  [".cake", "csharp"],
  [".ccm", "cpp"],
  [".chatmode.md", "markdown"],
  [".code-profile", "json"],
  [".code-snippets", "jsonc"],
  [".code-workspace", "jsonc"],
  [".containerfile", "dockerfile"],
  [".cpy", "python"],
  [".cppm", "cpp"],
  [".css.map", "json"],
  [".csx", "csharp"],
  [".cts", "typescript"],
  [".ctx", "tex"],
  [".cxxm", "cpp"],
  [".dsql", "sql"],
  [".ejs", "html"],
  [".es6", "javascript"],
  [".eyaml", "yaml"],
  [".eyml", "yaml"],
  [".geojson", "json"],
  [".gyp", "python"],
  [".gypi", "python"],
  [".h++", "cpp"],
  [".h.in", "cpp"],
  [".har", "json"],
  [".hpp.in", "cpp"],
  [".htm", "html"],
  [".ino", "cpp"],
  [".instructions.md", "markdown"],
  [".inl", "cpp"],
  [".ipy", "python"],
  [".ipp", "cpp"],
  [".ixx", "cpp"],
  [".js.map", "json"],
  [".jshtm", "html"],
  [".jsonld", "json"],
  [".litcoffee", "markdown"],
  [".mak", "makefile"],
  [".markdown", "markdown"],
  [".markdn", "markdown"],
  [".mdoc", "html"],
  [".mdown", "markdown"],
  [".mdtext", "markdown"],
  [".mdtxt", "markdown"],
  [".mdwn", "markdown"],
  [".mkd", "markdown"],
  [".mkdn", "markdown"],
  [".mts", "typescript"],
  [".ndjson", "jsonl"],
  [".pac", "javascript"],
  [".php4", "php"],
  [".php5", "php"],
  [".prompt.md", "markdown"],
  [".psrc", "powershell"],
  [".pssc", "powershell"],
  [".pyt", "python"],
  [".rbx", "ruby"],
  [".rhtml", "html"],
  [".rjs", "ruby"],
  [".ron", "markdown"],
  [".ronn", "markdown"],
  [".rpy", "python"],
  [".ru", "ruby"],
  [".shtml", "html"],
  [".ts.map", "json"],
  [".tpp", "cpp"],
  [".txx", "cpp"],
  [".vba", "vb"],
  [".volt", "html"],
  [".webmanifest", "json"],
  [".workbook", "markdown"],
  [".xht", "html"],
  [".xhtml", "html"],
]);

export function getLanguageFromFilename(path: string): string | undefined {
  const basename = path.split(/[\\/]/).pop()?.toLowerCase() ?? "";
  const exactMatch = LANGUAGE_BY_BASENAME.get(basename);
  if (exactMatch != null) return exactMatch;
  for (const [suffix, language] of LANGUAGE_BY_SUFFIX) {
    if (basename.endsWith(suffix)) return language;
  }
  return undefined;
}
