// Restored from ref/webview/assets/product-logger-ibAP2Yp2.js
// Product analytics event descriptors used by restored UI chunks.
export type ProductEventDescriptor = {
  $type?: string;
  eventName?: string;
};
export type ProductLogger = {
  logProductEvent(event: ProductEventDescriptor, payload?: unknown): void;
};
export type ProductLoggerScope = {
  get?(signal: unknown): ProductLogger | null | undefined;
  logProductEvent?(event: ProductEventDescriptor, payload?: unknown): void;
};

function event(eventName: string): ProductEventDescriptor {
  return { eventName };
}

export const __productLoggerR = {
  defaultValue: {
    logProductEvent(): void {},
  } satisfies ProductLogger,
  id: "productLogger",
};
export const _r = __productLoggerR;

export const codexThreadSwitchCompletedEvent = event(
  "codex_thread_switch_completed",
);
export const productLoggerX = event("codex_appshot_shortcut_changed");
export const productLoggerZn = event("codex_prompt_rail_navigation_clicked");
export const _productLoggerVr = event("codex_thread_side_panel_tab_viewed");
export const threadSidePanelOpenedEvent = {
  $type: "protobuf_analytics_events.v1.CodexThreadSidePanelOpened",
};
export const threadSidePanelClosedEvent = {
  $type: "protobuf_analytics_events.v1.CodexThreadSidePanelClosed",
};
export const codexThreadSwitchKind = {
  CODEX_THREAD_SWITCH_KIND_COLD: "CODEX_THREAD_SWITCH_KIND_COLD",
  CODEX_THREAD_SWITCH_KIND_HOT: "CODEX_THREAD_SWITCH_KIND_HOT",
  CODEX_THREAD_SWITCH_KIND_UNSPECIFIED: "CODEX_THREAD_SWITCH_KIND_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};
export const _productLoggerUr = codexThreadSwitchKind;
export const codexRemoteSshThreadActionKind = {
  CODEX_REMOTE_SSH_THREAD_ACTION_FORK: "CODEX_REMOTE_SSH_THREAD_ACTION_FORK",
  CODEX_REMOTE_SSH_THREAD_ACTION_START: "CODEX_REMOTE_SSH_THREAD_ACTION_START",
  CODEX_REMOTE_SSH_THREAD_ACTION_UNSPECIFIED:
    "CODEX_REMOTE_SSH_THREAD_ACTION_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const codexAutomationKind = {
  CODEX_AUTOMATION_KIND_CRON: "CODEX_AUTOMATION_KIND_CRON",
  CODEX_AUTOMATION_KIND_HEARTBEAT: "CODEX_AUTOMATION_KIND_HEARTBEAT",
  CODEX_AUTOMATION_KIND_UNSPECIFIED: "CODEX_AUTOMATION_KIND_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerI = {
  CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_LOCAL:
    "CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_LOCAL",
  CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_UNSPECIFIED:
    "CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_UNSPECIFIED",
  CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_WORKTREE:
    "CODEX_AUTOMATION_EXECUTION_ENVIRONMENT_WORKTREE",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerU = {
  CODEX_AUTOMATION_STATUS_ACTIVE: "CODEX_AUTOMATION_STATUS_ACTIVE",
  CODEX_AUTOMATION_STATUS_DELETED: "CODEX_AUTOMATION_STATUS_DELETED",
  CODEX_AUTOMATION_STATUS_PAUSED: "CODEX_AUTOMATION_STATUS_PAUSED",
  CODEX_AUTOMATION_STATUS_UNSPECIFIED: "CODEX_AUTOMATION_STATUS_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerV = {
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_DAILY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_DAILY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_HOURLY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_HOURLY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_MINUTELY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_MINUTELY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_MONTHLY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_MONTHLY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_SECONDLY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_SECONDLY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_UNSPECIFIED:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_UNSPECIFIED",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_WEEKLY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_WEEKLY",
  CODEX_AUTOMATION_SCHEDULE_FREQUENCY_YEARLY:
    "CODEX_AUTOMATION_SCHEDULE_FREQUENCY_YEARLY",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerZ = {
  CODEX_AUTOMATION_REASONING_EFFORT_HIGH:
    "CODEX_AUTOMATION_REASONING_EFFORT_HIGH",
  CODEX_AUTOMATION_REASONING_EFFORT_LOW:
    "CODEX_AUTOMATION_REASONING_EFFORT_LOW",
  CODEX_AUTOMATION_REASONING_EFFORT_MAX:
    "CODEX_AUTOMATION_REASONING_EFFORT_MAX",
  CODEX_AUTOMATION_REASONING_EFFORT_MEDIUM:
    "CODEX_AUTOMATION_REASONING_EFFORT_MEDIUM",
  CODEX_AUTOMATION_REASONING_EFFORT_MINIMAL:
    "CODEX_AUTOMATION_REASONING_EFFORT_MINIMAL",
  CODEX_AUTOMATION_REASONING_EFFORT_NONE:
    "CODEX_AUTOMATION_REASONING_EFFORT_NONE",
  CODEX_AUTOMATION_REASONING_EFFORT_UNSPECIFIED:
    "CODEX_AUTOMATION_REASONING_EFFORT_UNSPECIFIED",
  CODEX_AUTOMATION_REASONING_EFFORT_XHIGH:
    "CODEX_AUTOMATION_REASONING_EFFORT_XHIGH",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerEn = {
  $type: "protobuf_analytics_events.v1.CodexPrimaryRuntimeInstallResult",
};

export const productLoggerOn = {
  CODEX_PRIMARY_RUNTIME_RELEASE_LATEST: "CODEX_PRIMARY_RUNTIME_RELEASE_LATEST",
  CODEX_PRIMARY_RUNTIME_RELEASE_LATEST_ALPHA:
    "CODEX_PRIMARY_RUNTIME_RELEASE_LATEST_ALPHA",
  CODEX_PRIMARY_RUNTIME_RELEASE_UNSPECIFIED:
    "CODEX_PRIMARY_RUNTIME_RELEASE_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerDn = {
  CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_ALREADY_CURRENT:
    "CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_ALREADY_CURRENT",
  CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_CANCELED:
    "CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_CANCELED",
  CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_FAILED:
    "CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_FAILED",
  CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_INSTALLED:
    "CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_INSTALLED",
  CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_UNSPECIFIED:
    "CODEX_PRIMARY_RUNTIME_INSTALL_RESULT_STATUS_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerCn = {
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_FAILED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_FAILED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_OK:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_OK",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_PROBLEM:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_PROBLEM",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_UNSPECIFIED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_DIAGNOSE_STATUS_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerTn = {
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_ALREADY_CURRENT:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_ALREADY_CURRENT",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_CANCELED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_CANCELED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_FAILED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_FAILED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_INSTALLED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_INSTALLED",
  CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_UNSPECIFIED:
    "CODEX_PRIMARY_RUNTIME_DEPENDENCIES_RESET_STATUS_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerXn = event("codex_referral_invite_modal");

export const _productLoggerUn = {
  $type: "protobuf_analytics_events.v1.CodexRateLimitResetCreditRedeemed",
};

export const _productLoggerBn = {
  $type: "protobuf_analytics_events.v1.CodexPullRequestActionClicked",
};

export const _productLoggerHn = {
  $type: "protobuf_analytics_events.v1.CodexPullRequestSelected",
};

export const _productLoggerVn = {
  $type: "protobuf_analytics_events.v1.CodexPullRequestCommentPosted",
};

export const creditPurchaseModalOpenedEvent = {
  $type: "protobuf_analytics_events.v1.CodexCreditReloadModalShown",
};

export const addCreditsQuantitySelectedEvent = {
  $type: "protobuf_analytics_events.v1.CodexCreditReloadPurchaseCtaClicked",
};

export const creditCheckoutOpenedEvent = {
  $type: "protobuf_analytics_events.v1.CodexCreditPurchaseButtonClicked",
};

export const autoTopUpActionEvent = {
  $type:
    "protobuf_analytics_events.v1.CodexCreditReloadAutoReloadSettingsChanged",
};

export const productLoggerQn = {
  CODEX_REFERRAL_INVITE_MODAL_ACTION_BACKEND_ERROR:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_BACKEND_ERROR",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_CLOSE_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_CLOSE_CLICKED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_DONE_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_DONE_CLICKED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_CLICKED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_CLICKED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_SUCCEEDED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SEND_SUCCEEDED",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_SHOWN:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_SHOWN",
  CODEX_REFERRAL_INVITE_MODAL_ACTION_UNSPECIFIED:
    "CODEX_REFERRAL_INVITE_MODAL_ACTION_UNSPECIFIED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const _productLoggerJn = {
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_AUTHENTICATION_REQUIRED:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_AUTHENTICATION_REQUIRED",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_BACKEND_ISSUE:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_BACKEND_ISSUE",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_PERMISSION_DENIED:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_PERMISSION_DENIED",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_RATE_LIMITED:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_RATE_LIMITED",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_REFERRAL_ALREADY_EXISTS:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_REFERRAL_ALREADY_EXISTS",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_UNKNOWN_BACKEND_ERROR:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_UNKNOWN_BACKEND_ERROR",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_UNSPECIFIED:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_UNSPECIFIED",
  CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_VALIDATION_FAILED:
    "CODEX_REFERRAL_INVITE_MODAL_BACKEND_ERROR_TYPE_VALIDATION_FAILED",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const productLoggerYn = {
  CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_SYSTEM:
    "CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_SYSTEM",
  CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_UNSPECIFIED:
    "CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_UNSPECIFIED",
  CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_USER:
    "CODEX_REFERRAL_INVITE_MODAL_ERROR_RESPONSIBILITY_USER",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const CodexAvatarOverlayPetKind = {
  CODEX_AVATAR_OVERLAY_PET_KIND_UNSPECIFIED:
    "CODEX_AVATAR_OVERLAY_PET_KIND_UNSPECIFIED",
  CODEX_AVATAR_OVERLAY_PET_KIND_BUILT_IN:
    "CODEX_AVATAR_OVERLAY_PET_KIND_BUILT_IN",
  CODEX_AVATAR_OVERLAY_PET_KIND_CUSTOM: "CODEX_AVATAR_OVERLAY_PET_KIND_CUSTOM",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export const CodexAvatarOverlayNotificationSource = {
  CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_UNSPECIFIED:
    "CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_UNSPECIFIED",
  CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_LOCAL:
    "CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_LOCAL",
  CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_CLOUD:
    "CODEX_AVATAR_OVERLAY_NOTIFICATION_SOURCE_CLOUD",
  UNRECOGNIZED: "UNRECOGNIZED",
};

export function logProductEvent(
  scope: ProductLoggerScope,
  productEvent: ProductEventDescriptor,
  payload: unknown = {},
): void {
  const scopedLogger = scope.get?.(__productLoggerR);
  const logger = scopedLogger ?? scope;
  logger.logProductEvent?.(productEvent, payload);
}

export const productLoggerT = logProductEvent;
export const ___productLoggerT = logProductEvent;

export const productLoggerVt = {
  $type: "protobuf_analytics_events.v1.CodexLoginMethodSelected",
};
export const productLoggerUt = {
  $type: "protobuf_analytics_events.v1.CodexLoginSuccess",
};
export const productLoggerBt = {
  $type: "protobuf_analytics_events.v1.CodexLoginFailure",
};
