// Restored from ref/webview/assets/app-initial~app-main~remote-conversation-page~new-thread-panel-page~appgen-library-page~hot~fjhbmao5-BWbJojtu.js
// Semantic alias layer for current appgen library hot-path runtime.
const appgenLibraryHotCurrentRuntime = () =>
  "appgen-library-hot-current-runtime";

void appgenLibraryHotCurrentRuntime;

export {
  _ as hasAdditionalRateLimitNamed,
  $ as updateSubscriptionPlan,
  a as getHighestUsageWindow,
  A as getMobileBillingPlatform,
  at as usePlanPricingQuery,
  b as initProfessionalEmailDomainRuntime,
  B as formatCreditQuantityPrice,
  c as findRateLimitEntryByName,
  C as getPricingSurface,
  ct as useWorkspaceAdminRequestsQuery,
  d as getRateLimitBlockedReason,
  D as codexTeamPurchaseUrl,
  dt as initAutoTopUpApiRuntime,
  E as chatGptTeamPurchaseUrl,
  et as useSendAddCreditsNudgeEmailMutation,
  f as getRateLimitEntries,
  F as isPaidCodexPlan,
  ft as isAutoTopUpPaymentFailureStatus,
  g as isCoreCodexLimitName,
  G as initCustomCheckoutExperimentRuntime,
  gt as initPricingPlanRouteRuntime,
  h as initRateLimitStatusRuntime,
  H as formatCurrencyAmount,
  ht as pricingPlanRoutePath,
  i as initAppIllustrationAssetRuntime,
  I as initLoggedInPricingPageExperimentRuntime,
  it as useAutoTopUpSettingsQuery,
  j as getPlanChangeAction,
  J as openSubscriptionManagementUrl,
  k as isCreditSettingsEligiblePlan,
  K as getIsCustomCheckoutEnabled,
  l as getActiveRateLimitSnapshot,
  L as usePricingPagePathResolver,
  lt as useWorkspaceMonthlyUsageQuery,
  m as getActiveRateLimitName,
  M as getCodexDisplayPlan,
  mt as initPurchaseLoginHintRuntime,
  n as initRateLimitResetModalRuntime,
  N as getConsumerPlanPurchaseUrl,
  nt as useAutoTopUpPricingQuery,
  o as initUsageLimitWindowRuntime,
  O as iosCancelSubscriptionHelpUrl,
  ot as useAccountPurchaseOriginPlatformQuery,
  p as getRateLimitResetTime,
  P as initCodexPlanPurchaseUrlsRuntime,
  pt as addLoginHintToPurchaseUrl,
  q as logCheckoutStarted,
  Q as useSubscriptionUpdatePreviewQuery,
  r as appIllustrationImageUrl,
  R as initCreditPurchaseEntryRuntime,
  rt as useEnableAutoTopUpMutation,
  s as filterRateLimitEntriesForModel,
  S as useOpenPricingPageRoute,
  st as useSaveWorkspaceAdminRequestMutation,
  t as RateLimitResetModal,
  T as chatGptBillingSettingsUrl,
  tt as useBillingCurrencyQuery,
  u as pickPrimaryRateLimitEntry,
  U as initAutoTopUpCreditValidationRuntime,
  ut as useAccountSettingsQuery,
  v as hasModelSpecificRateLimit,
  V as initAutoTopUpCurrencyInputRuntime,
  w as androidCancelSubscriptionHelpUrl,
  W as trackWorkspaceCustomCheckoutExposure,
  x as useOpenPricingPageOrCheckout,
  X as cancelPendingSubscriptionUpdate,
  y as createUsageRateLimitSnapshot,
  Y as openCheckoutUrlInBrowser,
  z as useCreditPurchaseHandler,
  Z as initUsageSettingsBillingQueriesRuntime,
} from "../../appgen/library-hot-current-runtime-implementation";
