// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~appgen-settings-page~appgen-publication-terms-ro~g0k1g2bt-B6jrUW_u.js
// Semantic alias layer for appgen settings/publication runtime.
export {
  APPGEN_SETTINGS_PUBLICATION_GATE_ID,
  AppgenPublicationTermsFallbackIcon,
  AppgenSettingsChromeIcon,
  AppgenSettingsOpenAiIcon,
  AppgenSettingsPencilIcon,
  AppgenSettingsPublicationIcon,
  MICROSOFT_EXCEL_ALIAS,
  MICROSOFT_POWERPOINT_ALIAS,
  PRESENTATIONS_PLUGIN_NAME,
  SPREADSHEETS_PLUGIN_NAME,
  createAppgenPluginMentionItem,
  createOfficeAliasMentionItem,
  findAppgenPluginForMention,
  getAppgenPluginDescription,
  getAppgenPluginMentionIcon,
  getAppgenSettingsFilesystemMediaPath,
  getAppgenSettingsFilesystemMediaSrc,
  getAppgenSettingsPluginIcon,
  initAppgenPublicationTermsFallbackIconChunk,
  initAppgenSettingsChromeIconChunk,
  initAppgenSettingsFilesystemMediaChunk,
  initAppgenSettingsOpenAiIconChunk,
  initAppgenSettingsPencilIconChunk,
  initAppgenSettingsPluginIconChunk,
  initAppgenSettingsPublicationIconChunk,
  initAppgenSettingsPublicationRuntimeChunk,
  initOfficeNativeAppAliasChunk,
  initPrimaryRuntimeOfficePluginConstantsChunk,
  isPresentationPlugin,
  isSpreadsheetPlugin,
  nativeAppMatchesOfficeAlias,
  officeAliasMatchesQuery,
  resolveMentionedOfficeAliasLabel,
} from "../../appgen/settings-publication-runtime";
