// Restored from ref/webview/assets/app-initial~app-main~projects-index-page~local-conversation-page-HgUkvfGN.js
// Complete current-ref compatibility export surface for projectHoverCardCurrent.
import {
  buildRemoteHostGlobeColors,
  collapseHomeDirectoryInPath,
  formatAppServerConnectionErrorMessage,
  getRemoteConnectionStatusBadgeModel,
  initPinnedProjectRuntime,
  initProjectHoverCardChunk,
  initProjectHoverCardSourceHelpers,
  initProjectPinButtonChunk,
  initProjectSourceFolderIconChunk,
  initRemoteConnectionStatusMessagesChunk,
  initRemoteConnectionStatusModelChunk,
  initRemoteHostGlobeColorMath,
  initRemoteHostGlobeColorSignal,
  initRemoteHostGlobeIconChunk,
  ProjectHoverCard,
  ProjectPinButton,
  ProjectSourceFolderIcon,
  RemoteHostGlobeIcon,
  remoteHostGlobeColorByHostIdSignal,
  replacePinnedProjectOrder,
  setProjectPinned,
} from "../../sidebar/project-hover-card";
import {
  initRemoteProjectIconChunk,
  initWaitingStatusIconChunk,
  RemoteProjectIcon,
  WaitingStatusIcon,
} from "../../remote/remote-connection-runtime";

export {
  remoteHostGlobeColorByHostIdSignal as projectHoverCardCurrentCompatSlotUpperC,
  initRemoteHostGlobeColorSignal as projectHoverCardCurrentCompatSlotUpperS,
  initWaitingStatusIconChunk as projectHoverCardCurrentCompatSlotUpperT,
  initRemoteProjectIconChunk as projectHoverCardCurrentCompatSlotUnderscore,
  setProjectPinned as projectHoverCardCurrentCompatSlotLowerA,
  buildRemoteHostGlobeColors as projectHoverCardCurrentCompatSlotLowerB,
  ProjectSourceFolderIcon as projectHoverCardCurrentCompatSlotLowerC,
  initRemoteConnectionStatusMessagesChunk as projectHoverCardCurrentCompatSlotLowerD,
  formatAppServerConnectionErrorMessage as projectHoverCardCurrentCompatSlotLowerF,
  RemoteProjectIcon as projectHoverCardCurrentCompatSlotLowerG,
  initProjectPinButtonChunk as projectHoverCardCurrentCompatSlotLowerH,
  initPinnedProjectRuntime as projectHoverCardCurrentCompatSlotLowerI,
  initProjectSourceFolderIconChunk as projectHoverCardCurrentCompatSlotLowerL,
  ProjectPinButton as projectHoverCardCurrentCompatSlotLowerM,
  initProjectHoverCardChunk as projectHoverCardCurrentCompatSlotLowerN,
  collapseHomeDirectoryInPath as projectHoverCardCurrentCompatSlotLowerO,
  initRemoteConnectionStatusModelChunk as projectHoverCardCurrentCompatSlotLowerP,
  replacePinnedProjectOrder as projectHoverCardCurrentCompatSlotLowerR,
  initProjectHoverCardSourceHelpers as projectHoverCardCurrentCompatSlotLowerS,
  ProjectHoverCard as projectHoverCardCurrentCompatSlotLowerT,
  getRemoteConnectionStatusBadgeModel as projectHoverCardCurrentCompatSlotLowerU,
  RemoteHostGlobeIcon as projectHoverCardCurrentCompatSlotLowerV,
  WaitingStatusIcon as projectHoverCardCurrentCompatSlotLowerW,
  initRemoteHostGlobeColorMath as projectHoverCardCurrentCompatSlotLowerX,
  initRemoteHostGlobeIconChunk as projectHoverCardCurrentCompatSlotLowerY,
};

export {
  buildRemoteHostGlobeColors,
  collapseHomeDirectoryInPath,
  formatAppServerConnectionErrorMessage,
  getRemoteConnectionStatusBadgeModel,
  initPinnedProjectRuntime,
  initProjectHoverCardChunk,
  initProjectHoverCardSourceHelpers,
  initProjectPinButtonChunk,
  initProjectSourceFolderIconChunk,
  initRemoteConnectionStatusMessagesChunk,
  initRemoteConnectionStatusModelChunk,
  initRemoteHostGlobeColorMath,
  initRemoteHostGlobeColorSignal,
  initRemoteHostGlobeIconChunk,
  initRemoteProjectIconChunk,
  initWaitingStatusIconChunk,
  ProjectHoverCard,
  ProjectPinButton,
  ProjectSourceFolderIcon,
  RemoteHostGlobeIcon,
  remoteHostGlobeColorByHostIdSignal,
  RemoteProjectIcon,
  replacePinnedProjectOrder,
  setProjectPinned,
  WaitingStatusIcon,
};
