// Restored from ref/webview/assets/app-initial~app-main~remote-conversation-page~projects-index-page-px21igmO.js
// Current projects-index compatibility surface. Named slots that have stable
// semantic restorations are wired to project helpers; unresolved UI/runtime
// slots still delegate to the exact current-hash bundle.

import {
  applyPendingThreadDropsToContainer,
  createSidebarShortcutLabelMap,
  getProjectGroupCollapseAction,
  parsePullRequestNumberFromUrl,
  resolveProjectCreationFlow,
} from "../../projects/projects-index-current-app-main/helpers";
import {
  getProjectIndexPullRequestStatus,
  getProjectIndexTaskPullRequestStatus,
} from "../../projects/projects-index-current-app-main/current-pull-request-status";
import {
  applyProjectGroupCollapseAction,
  hideAddProjectMenu,
  navigateToAutomationsPage,
  navigateToLibraryPage,
  navigateToPluginDirectoryFromSidebar,
  navigateToPullRequestsPage,
  navigateToSitesPage,
  openAddProjectFlow,
  openLocalProjectCreationDialog,
  openProjectInHomeRoute,
  openRemoteProjectSelection,
  toggleRecentSidebarSection,
} from "../../projects/projects-index-current-app-main/navigation";
import * as projectsIndexCurrentRuntime from "../../vendor/projects-index-current-runtime";

export const projectsIndexCurrentCompatSlotDollar = projectsIndexCurrentRuntime.$;
export const projectsIndexCurrentCompatSlotDollarLowerT = projectsIndexCurrentRuntime.$t;
export const projectsIndexCurrentCompatSlotUpperA = projectsIndexCurrentRuntime.A;
export const projectsIndexCurrentCompatSlotUpperALowerT = projectsIndexCurrentRuntime.At;
export const projectsIndexCurrentCompatSlotUpperB = getProjectIndexPullRequestStatus;
export const projectsIndexCurrentCompatSlotUpperBLowerT = navigateToPluginDirectoryFromSidebar;
export const projectsIndexCurrentCompatSlotUpperC = projectsIndexCurrentRuntime.C;
export const projectsIndexCurrentCompatSlotUpperCLowerT = projectsIndexCurrentRuntime.Ct;
export const projectsIndexCurrentCompatSlotUpperD = projectsIndexCurrentRuntime.D;
export const projectsIndexCurrentCompatSlotUpperDLowerT = projectsIndexCurrentRuntime.Dt;
export const projectsIndexCurrentCompatSlotUpperE = projectsIndexCurrentRuntime.E;
export const projectsIndexCurrentCompatSlotUpperELowerT = applyPendingThreadDropsToContainer;
export const projectsIndexCurrentCompatSlotUpperF = getProjectIndexTaskPullRequestStatus;
export const projectsIndexCurrentCompatSlotUpperFLowerT = projectsIndexCurrentRuntime.Ft;
export const projectsIndexCurrentCompatSlotUpperG = projectsIndexCurrentRuntime.G;
export const projectsIndexCurrentCompatSlotUpperGLowerT = projectsIndexCurrentRuntime.Gt;
export const projectsIndexCurrentCompatSlotUpperH = projectsIndexCurrentRuntime.H;
export const projectsIndexCurrentCompatSlotUpperHLowerT = openRemoteProjectSelection;
export const projectsIndexCurrentCompatSlotUpperI = projectsIndexCurrentRuntime.I;
export const projectsIndexCurrentCompatSlotUpperILowerT = navigateToAutomationsPage;
export const projectsIndexCurrentCompatSlotUpperJ = projectsIndexCurrentRuntime.J;
export const projectsIndexCurrentCompatSlotUpperJLowerT = projectsIndexCurrentRuntime.Jt;
export const projectsIndexCurrentCompatSlotUpperK = projectsIndexCurrentRuntime.K;
export const projectsIndexCurrentCompatSlotUpperKLowerT = getProjectGroupCollapseAction;
export const projectsIndexCurrentCompatSlotUpperL = projectsIndexCurrentRuntime.L;
export const projectsIndexCurrentCompatSlotUpperLLowerT = navigateToLibraryPage;
export const projectsIndexCurrentCompatSlotUpperM = projectsIndexCurrentRuntime.M;
export const projectsIndexCurrentCompatSlotUpperMLowerT = projectsIndexCurrentRuntime.Mt;
export const projectsIndexCurrentCompatSlotUpperN = projectsIndexCurrentRuntime.N;
export const projectsIndexCurrentCompatSlotUpperNLowerT = applyProjectGroupCollapseAction;
export const projectsIndexCurrentCompatSlotUpperO = projectsIndexCurrentRuntime.O;
export const projectsIndexCurrentCompatSlotUpperOLowerT = projectsIndexCurrentRuntime.Ot;
export const projectsIndexCurrentCompatSlotUpperP = projectsIndexCurrentRuntime.P;
export const projectsIndexCurrentCompatSlotUpperPLowerT = hideAddProjectMenu;
export const projectsIndexCurrentCompatSlotUpperQ = projectsIndexCurrentRuntime.Q;
export const projectsIndexCurrentCompatSlotUpperQLowerT = projectsIndexCurrentRuntime.Qt;
export const projectsIndexCurrentCompatSlotUpperR = projectsIndexCurrentRuntime.R;
export const projectsIndexCurrentCompatSlotUpperRLowerT = navigateToPullRequestsPage;
export const projectsIndexCurrentCompatSlotUpperS = projectsIndexCurrentRuntime.S;
export const projectsIndexCurrentCompatSlotUpperSLowerT = projectsIndexCurrentRuntime.St;
export const projectsIndexCurrentCompatSlotUpperT = projectsIndexCurrentRuntime.T;
export const projectsIndexCurrentCompatSlotUpperTLowerT = projectsIndexCurrentRuntime.Tt;
export const projectsIndexCurrentCompatSlotUpperU = projectsIndexCurrentRuntime.U;
export const projectsIndexCurrentCompatSlotUpperULowerT = toggleRecentSidebarSection;
export const projectsIndexCurrentCompatSlotUpperV = projectsIndexCurrentRuntime.V;
export const projectsIndexCurrentCompatSlotUpperVLowerT = openLocalProjectCreationDialog;
export const projectsIndexCurrentCompatSlotUpperW = projectsIndexCurrentRuntime.W;
export const projectsIndexCurrentCompatSlotUpperWLowerT = openAddProjectFlow;
export const projectsIndexCurrentCompatSlotUpperX = projectsIndexCurrentRuntime.X;
export const projectsIndexCurrentCompatSlotUpperXLowerT = projectsIndexCurrentRuntime.Xt;
export const projectsIndexCurrentCompatSlotUpperY = projectsIndexCurrentRuntime.Y;
export const projectsIndexCurrentCompatSlotUpperYLowerT = projectsIndexCurrentRuntime.Yt;
export const projectsIndexCurrentCompatSlotUpperZ = projectsIndexCurrentRuntime.Z;
export const projectsIndexCurrentCompatSlotUpperZLowerT = projectsIndexCurrentRuntime.Zt;
export const projectsIndexCurrentCompatSlotUnderscore = projectsIndexCurrentRuntime._;
export const projectsIndexCurrentCompatSlotUnderscoreLowerT = projectsIndexCurrentRuntime._t;
export const projectsIndexCurrentCompatSlotLowerA = projectsIndexCurrentRuntime.a;
export const projectsIndexCurrentCompatSlotLowerALowerN = projectsIndexCurrentRuntime.an;
export const projectsIndexCurrentCompatSlotLowerALowerT = projectsIndexCurrentRuntime.at;
export const projectsIndexCurrentCompatSlotLowerB = projectsIndexCurrentRuntime.b;
export const projectsIndexCurrentCompatSlotLowerBLowerT = projectsIndexCurrentRuntime.bt;
export const projectsIndexCurrentCompatSlotLowerC = projectsIndexCurrentRuntime.c;
export const projectsIndexCurrentCompatSlotLowerCLowerN = projectsIndexCurrentRuntime.cn;
export const projectsIndexCurrentCompatSlotLowerCLowerT = projectsIndexCurrentRuntime.ct;
export const projectsIndexCurrentCompatSlotLowerD = openProjectInHomeRoute;
export const projectsIndexCurrentCompatSlotLowerDLowerN = projectsIndexCurrentRuntime.dn;
export const projectsIndexCurrentCompatSlotLowerDLowerT = projectsIndexCurrentRuntime.dt;
export const projectsIndexCurrentCompatSlotLowerELowerN = projectsIndexCurrentRuntime.en;
export const projectsIndexCurrentCompatSlotLowerELowerT = projectsIndexCurrentRuntime.et;
export const projectsIndexCurrentCompatSlotLowerF = projectsIndexCurrentRuntime.f;
export const projectsIndexCurrentCompatSlotLowerFLowerN = projectsIndexCurrentRuntime.fn;
export const projectsIndexCurrentCompatSlotLowerFLowerT = projectsIndexCurrentRuntime.ft;
export const projectsIndexCurrentCompatSlotLowerG = projectsIndexCurrentRuntime.g;
export const projectsIndexCurrentCompatSlotLowerGLowerT = projectsIndexCurrentRuntime.gt;
export const projectsIndexCurrentCompatSlotLowerH = projectsIndexCurrentRuntime.h;
export const projectsIndexCurrentCompatSlotLowerHLowerT = projectsIndexCurrentRuntime.ht;
export const projectsIndexCurrentCompatSlotLowerI = projectsIndexCurrentRuntime.i;
export const projectsIndexCurrentCompatSlotLowerILowerN = projectsIndexCurrentRuntime.in;
export const projectsIndexCurrentCompatSlotLowerILowerT = projectsIndexCurrentRuntime.it;
export const projectsIndexCurrentCompatSlotLowerJ = projectsIndexCurrentRuntime.j;
export const projectsIndexCurrentCompatSlotLowerJLowerT = projectsIndexCurrentRuntime.jt;
export const projectsIndexCurrentCompatSlotLowerK = projectsIndexCurrentRuntime.k;
export const projectsIndexCurrentCompatSlotLowerKLowerT = resolveProjectCreationFlow;
export const projectsIndexCurrentCompatSlotLowerL = projectsIndexCurrentRuntime.l;
export const projectsIndexCurrentCompatSlotLowerLLowerN = projectsIndexCurrentRuntime.ln;
export const projectsIndexCurrentCompatSlotLowerLLowerT = projectsIndexCurrentRuntime.lt;
export const projectsIndexCurrentCompatSlotLowerM = projectsIndexCurrentRuntime.m;
export const projectsIndexCurrentCompatSlotLowerMLowerT = projectsIndexCurrentRuntime.mt;
export const projectsIndexCurrentCompatSlotLowerN = projectsIndexCurrentRuntime.n;
export const projectsIndexCurrentCompatSlotLowerNLowerN = projectsIndexCurrentRuntime.nn;
export const projectsIndexCurrentCompatSlotLowerNLowerT = projectsIndexCurrentRuntime.nt;
export const projectsIndexCurrentCompatSlotLowerO = projectsIndexCurrentRuntime.o;
export const projectsIndexCurrentCompatSlotLowerOLowerN = projectsIndexCurrentRuntime.on;
export const projectsIndexCurrentCompatSlotLowerOLowerT = projectsIndexCurrentRuntime.ot;
export const projectsIndexCurrentCompatSlotLowerP = projectsIndexCurrentRuntime.p;
export const projectsIndexCurrentCompatSlotLowerPLowerN = projectsIndexCurrentRuntime.pn;
export const projectsIndexCurrentCompatSlotLowerPLowerT = projectsIndexCurrentRuntime.pt;
export const projectsIndexCurrentCompatSlotLowerQ = projectsIndexCurrentRuntime.q;
export const projectsIndexCurrentCompatSlotLowerQLowerT = projectsIndexCurrentRuntime.qt;
export const projectsIndexCurrentCompatSlotLowerR = projectsIndexCurrentRuntime.r;
export const projectsIndexCurrentCompatSlotLowerRLowerN = projectsIndexCurrentRuntime.rn;
export const projectsIndexCurrentCompatSlotLowerRLowerT = projectsIndexCurrentRuntime.rt;
export const projectsIndexCurrentCompatSlotLowerS = projectsIndexCurrentRuntime.s;
export const projectsIndexCurrentCompatSlotLowerSLowerN = projectsIndexCurrentRuntime.sn;
export const projectsIndexCurrentCompatSlotLowerSLowerT = projectsIndexCurrentRuntime.st;
export const projectsIndexCurrentCompatSlotLowerT = projectsIndexCurrentRuntime.t;
export const projectsIndexCurrentCompatSlotLowerTLowerN = projectsIndexCurrentRuntime.tn;
export const projectsIndexCurrentCompatSlotLowerTLowerT = projectsIndexCurrentRuntime.tt;
export const projectsIndexCurrentCompatSlotLowerU = projectsIndexCurrentRuntime.u;
export const projectsIndexCurrentCompatSlotLowerULowerN = projectsIndexCurrentRuntime.un;
export const projectsIndexCurrentCompatSlotLowerULowerT = projectsIndexCurrentRuntime.ut;
export const projectsIndexCurrentCompatSlotLowerV = projectsIndexCurrentRuntime.v;
export const projectsIndexCurrentCompatSlotLowerVLowerT = projectsIndexCurrentRuntime.vt;
export const projectsIndexCurrentCompatSlotLowerW = projectsIndexCurrentRuntime.w;
export const projectsIndexCurrentCompatSlotLowerWLowerT = projectsIndexCurrentRuntime.wt;
export const projectsIndexCurrentCompatSlotLowerX = createSidebarShortcutLabelMap;
export const projectsIndexCurrentCompatSlotLowerXLowerT = projectsIndexCurrentRuntime.xt;
export const projectsIndexCurrentCompatSlotLowerY = projectsIndexCurrentRuntime.y;
export const projectsIndexCurrentCompatSlotLowerYLowerT = projectsIndexCurrentRuntime.yt;
export const projectsIndexCurrentCompatSlotLowerZ = parsePullRequestNumberFromUrl;
export const projectsIndexCurrentCompatSlotLowerZLowerT = navigateToSitesPage;

// prettier-ignore
export {
  projectsIndexCurrentCompatSlotDollar as ArchiveThreadIcon, projectsIndexCurrentCompatSlotDollarLowerT as initStartProjectConversationRuntime, projectsIndexCurrentCompatSlotUpperA as initPinThreadIconChunk, projectsIndexCurrentCompatSlotUpperALowerT as initProjectCreationFlowRuntime, projectsIndexCurrentCompatSlotUpperB as getProjectIndexPullRequestStatus, projectsIndexCurrentCompatSlotUpperBLowerT as navigateToPluginDirectoryFromSidebar, projectsIndexCurrentCompatSlotUpperC as HexColorPicker, projectsIndexCurrentCompatSlotUpperCLowerT as SidebarDraggableThreadItem,
  projectsIndexCurrentCompatSlotUpperD as ArchiveThreadConfirmDialog, projectsIndexCurrentCompatSlotUpperDLowerT as initSidebarDropContextsRuntime, projectsIndexCurrentCompatSlotUpperE as useOpenThreadInNewWindow, projectsIndexCurrentCompatSlotUpperELowerT as applyPendingThreadDropsToContainer, projectsIndexCurrentCompatSlotUpperF as getProjectIndexTaskPullRequestStatus, projectsIndexCurrentCompatSlotUpperFLowerT as initSidebarNavigationActionsRuntime, projectsIndexCurrentCompatSlotUpperG as pinThreadMenuMessage, projectsIndexCurrentCompatSlotUpperGLowerT as startNewSidebarConversationFromState,
  projectsIndexCurrentCompatSlotUpperH as ProjectIconBadge, projectsIndexCurrentCompatSlotUpperHLowerT as openRemoteProjectSelection, projectsIndexCurrentCompatSlotUpperI as initTaskPullRequestBadgeRuntime, projectsIndexCurrentCompatSlotUpperILowerT as navigateToAutomationsPage, projectsIndexCurrentCompatSlotUpperJ as useProjectAppearance, projectsIndexCurrentCompatSlotUpperJLowerT as hasSeenRemoteConnectionsHomeAnnouncementSignal, projectsIndexCurrentCompatSlotUpperK as unpinThreadMenuMessage, projectsIndexCurrentCompatSlotUpperKLowerT as getProjectGroupCollapseAction,
  projectsIndexCurrentCompatSlotUpperL as localTaskPullRequestBadgeSignal, projectsIndexCurrentCompatSlotUpperLLowerT as navigateToLibraryPage, projectsIndexCurrentCompatSlotUpperM as initLocalConversationThreadRowRuntime, projectsIndexCurrentCompatSlotUpperMLowerT as initCreateProjectTypeDialogRuntime, projectsIndexCurrentCompatSlotUpperN as LOCAL_TASK_INPUT_SNOOZE_DURATION_MS, projectsIndexCurrentCompatSlotUpperNLowerT as applyProjectGroupCollapseAction, projectsIndexCurrentCompatSlotUpperO as initArchiveThreadConfirmDialogRuntime, projectsIndexCurrentCompatSlotUpperOLowerT as useSidebarThreadContainerDropTarget,
  projectsIndexCurrentCompatSlotUpperP as initLocalTaskInputSnoozeRuntime, projectsIndexCurrentCompatSlotUpperPLowerT as hideAddProjectMenu, projectsIndexCurrentCompatSlotUpperQ as initCloudTaskRowRuntime, projectsIndexCurrentCompatSlotUpperQLowerT as initDirectLocalProjectFeatureGateRuntime, projectsIndexCurrentCompatSlotUpperR as taskPullRequestBadgeSignal, projectsIndexCurrentCompatSlotUpperRLowerT as navigateToPullRequestsPage, projectsIndexCurrentCompatSlotUpperS as initSidebarShortcutLabelContext, projectsIndexCurrentCompatSlotUpperSLowerT as SidebarDragContainerProvider,
  projectsIndexCurrentCompatSlotUpperT as initOpenThreadInNewWindowRuntime, projectsIndexCurrentCompatSlotUpperTLowerT as pendingThreadDropsContext, projectsIndexCurrentCompatSlotUpperU as initProjectIconBadgeRuntime, projectsIndexCurrentCompatSlotUpperULowerT as toggleRecentSidebarSection, projectsIndexCurrentCompatSlotUpperV as initPullRequestStatusHelpers, projectsIndexCurrentCompatSlotUpperVLowerT as openLocalProjectCreationDialog, projectsIndexCurrentCompatSlotUpperW as initPinnedThreadActionsRuntime, projectsIndexCurrentCompatSlotUpperWLowerT as openAddProjectFlow,
  projectsIndexCurrentCompatSlotUpperX as initPendingWorktreeRowRuntime, projectsIndexCurrentCompatSlotUpperXLowerT as addProjectMenuStateSignal, projectsIndexCurrentCompatSlotUpperY as PendingWorktreeRow, projectsIndexCurrentCompatSlotUpperYLowerT as initSidebarAddProjectStateRuntime, projectsIndexCurrentCompatSlotUpperZ as CloudTaskRow, projectsIndexCurrentCompatSlotUpperZLowerT as DIRECT_LOCAL_PROJECT_FEATURE_GATE_ID, projectsIndexCurrentCompatSlotUnderscore as initRemoteConnectionStatusBadgeRuntime, projectsIndexCurrentCompatSlotUnderscoreLowerT as SidebarThreadStatusIndicator,
  projectsIndexCurrentCompatSlotLowerA as ProjectGroupList, projectsIndexCurrentCompatSlotLowerALowerN as initActiveSidebarThreadSelectionRuntime, projectsIndexCurrentCompatSlotLowerALowerT as initThreadListDragOrderingRuntime, projectsIndexCurrentCompatSlotLowerB as sidebarShortcutLabelContext, projectsIndexCurrentCompatSlotLowerBLowerT as SidebarSortableThreadItem, projectsIndexCurrentCompatSlotLowerC as ProjectHoverCard, projectsIndexCurrentCompatSlotLowerCLowerN as initSidebarThreadSwitchTrackerRuntime, projectsIndexCurrentCompatSlotLowerCLowerT as initCollapsibleSidebarSectionRuntime,
  projectsIndexCurrentCompatSlotLowerD as openProjectInHomeRoute, projectsIndexCurrentCompatSlotLowerDLowerN as restrictSidebarDragToScrollableAncestor, projectsIndexCurrentCompatSlotLowerDLowerT as initProjectThreadOrderPersistenceRuntime, projectsIndexCurrentCompatSlotLowerELowerN as useStartNewConversationInProject, projectsIndexCurrentCompatSlotLowerELowerT as initArchiveThreadIconChunk, projectsIndexCurrentCompatSlotLowerF as ProjectDisclosureChevronIcon, projectsIndexCurrentCompatSlotLowerFLowerN as restrictSidebarDragToHorizontalAxis, projectsIndexCurrentCompatSlotLowerFLowerT as savePinnedThreadOrder,
  projectsIndexCurrentCompatSlotLowerG as RemoteConnectionStatusBadge, projectsIndexCurrentCompatSlotLowerGLowerT as saveProjectThreadSortKey, projectsIndexCurrentCompatSlotLowerH as initProjectDisclosureIconRuntime, projectsIndexCurrentCompatSlotLowerHLowerT as removeThreadFromProjectOrders, projectsIndexCurrentCompatSlotLowerI as initProjectsSidebarRuntime, projectsIndexCurrentCompatSlotLowerILowerN as setActiveSidebarThread, projectsIndexCurrentCompatSlotLowerILowerT as initSidebarDropIndicatorRuntime, projectsIndexCurrentCompatSlotLowerJ as LocalConversationThreadRow,
  projectsIndexCurrentCompatSlotLowerJLowerT as CreateProjectTypeDialog, projectsIndexCurrentCompatSlotLowerK as PinThreadIcon, projectsIndexCurrentCompatSlotLowerKLowerT as resolveProjectCreationFlow, projectsIndexCurrentCompatSlotLowerL as composeRefs, projectsIndexCurrentCompatSlotLowerLLowerN as sidebarThreadSwitchTracker, projectsIndexCurrentCompatSlotLowerLLowerT as NewChatToolbarButton, projectsIndexCurrentCompatSlotLowerM as ProjectDisclosureIcon, projectsIndexCurrentCompatSlotLowerMLowerT as initProjectThreadOrderActionsRuntime,
  projectsIndexCurrentCompatSlotLowerN as ProjectsOrConnectionsSidebarSection, projectsIndexCurrentCompatSlotLowerNLowerN as CollapsibleSidebarSection, projectsIndexCurrentCompatSlotLowerNLowerT as initThreadEnvironmentIconRuntime, projectsIndexCurrentCompatSlotLowerO as SidebarProjectSortAndFilterMenu, projectsIndexCurrentCompatSlotLowerOLowerN as openSidebarThread, projectsIndexCurrentCompatSlotLowerOLowerT as useThreadListDragOrdering, projectsIndexCurrentCompatSlotLowerP as initProjectDisclosureChevronIconChunk, projectsIndexCurrentCompatSlotLowerPLowerN as restrictSidebarDragToVerticalAxis,
  projectsIndexCurrentCompatSlotLowerPLowerT as initPinnedThreadOrderPersistenceRuntime, projectsIndexCurrentCompatSlotLowerQ as initProjectAppearanceRuntime, projectsIndexCurrentCompatSlotLowerQLowerT as initProjectGroupCollapseHelpers, projectsIndexCurrentCompatSlotLowerR as AddProjectToolbarAction, projectsIndexCurrentCompatSlotLowerRLowerN as initOpenProjectRouteRuntime, projectsIndexCurrentCompatSlotLowerRLowerT as SidebarDropIndicatorLine, projectsIndexCurrentCompatSlotLowerS as initProjectsSidebarSurfaceRuntime, projectsIndexCurrentCompatSlotLowerSLowerN as recordSidebarThreadSwitchStarted,
  projectsIndexCurrentCompatSlotLowerSLowerT as CollapsibleSidebarSectionTitle, projectsIndexCurrentCompatSlotLowerT as ChatsSidebarSection, projectsIndexCurrentCompatSlotLowerTLowerN as SidebarNavigationRowButton, projectsIndexCurrentCompatSlotLowerTLowerT as ThreadEnvironmentIcon, projectsIndexCurrentCompatSlotLowerU as initOpenProjectInHomeRouteRuntime, projectsIndexCurrentCompatSlotLowerULowerN as initSidebarDragTransformModifiersChunk, projectsIndexCurrentCompatSlotLowerULowerT as initNewChatToolbarButtonRuntime, projectsIndexCurrentCompatSlotLowerV as SidebarThreadList,
  projectsIndexCurrentCompatSlotLowerVLowerT as initSidebarThreadStatusRuntime, projectsIndexCurrentCompatSlotLowerW as initHexColorPickerRuntime, projectsIndexCurrentCompatSlotLowerWLowerT as initSidebarDndContextRuntime, projectsIndexCurrentCompatSlotLowerX as createSidebarShortcutLabelMap, projectsIndexCurrentCompatSlotLowerXLowerT as SidebarThreadDropContainer, projectsIndexCurrentCompatSlotLowerY as initSidebarThreadListRuntime, projectsIndexCurrentCompatSlotLowerYLowerT as SidebarDndProvider, projectsIndexCurrentCompatSlotLowerZ as parsePullRequestNumberFromUrl,
  projectsIndexCurrentCompatSlotLowerZLowerT as navigateToSitesPage
};
