// Restored from ref/webview/assets/app-initial~app-main~worktree-init-v2-page~remote-conversation-page~pull-requests-page~new-~ozr5a6hk-DZC70s11.js
// Semantic and compatibility alias layer for pull request new-thread runtime.
// Current exact-hash semantic aliases used by IMPORT_MAP. Legacy compatibility
// slots remain below for restored consumers that still import them.
export {
  $ as sidebarSectionCollapsedSelector,
  $t as useMcpResourceQuery,
  A as collapsedProjectsByRootSelector,
  At as initChatGptAccountRuntime,
  B as setProjectlessChatsFirst,
  Bt as configRequirementsQueryFamily,
  C as useAppServerManagerForHost,
  Ct as remoteControlPairingQueryFamily,
  D as useRecentConversationsMetaQuery,
  Dt as RemoteControlAuthRequiredError,
  E as useRecentConversationsQuery,
  Et as revokeRemoteControlClient,
  F as sidebarImportedProjectRootsAtom,
  Ft as layeredConfigQueryKeyPrefix,
  G as setProjectGroupCollapsed,
  Gt as isManagedConfigLayer,
  H as applyImportedProjectRootsCollapse,
  Ht as getUserConfigWriteTarget,
  I as setSidebarActiveThreadTarget,
  It as mcpServerStatusGcTimeMs,
  J as sidebarModeSelector,
  Jt as getConfigOriginValue,
  K as setThreadSortKey,
  Kt as toolsAndAuthMcpServerStatusQueryFamily,
  L as setCollapsedSidebarSection,
  Lt as mcpServersConfigQueryKeyPrefix,
  M as initSidebarPreferencesRuntime,
  Mt as initAppServerRegistryRuntime,
  N as keepProjectsInRecentSelector,
  Nt as configRequirementsQueryKeyPrefix,
  O as activeSidebarThreadKeyAtom,
  Ot as gitStableMetadataQuery,
  P as projectlessChatsFirstSelector,
  Pt as effectiveConfigQueryKeyPrefix,
  Q as sidebarSectionCountsAtom,
  Qt as useMcpServersConfigQuery,
  R as setSidebarSectionVisibility,
  Rt as mcpServerStatusQueryKeyPrefix,
  S as getConversationAppServerManager,
  Sn as useStableCallback,
  St as remoteControlMfaRequirementQueryAtom,
  T as useAppServerRegistry,
  Tt as listRemoteControlClients,
  U as setSidebarOrganizeMode,
  Ut as getConfigLayerFilePath,
  V as updateImportedProjectRootExpansion,
  Vt as fetchReadConfigForHost,
  W as setProjectListExpanded,
  Wt as initMcpConfigRuntime,
  X as sidebarOrganizeModeAtom,
  Xt as useLocalCustomAgentsQuery,
  Y as sidebarOrganizeModeSelector,
  Yt as useAnalyticsConfigQuery,
  Z as projectListExpandedAtom,
  Zt as useEffectiveConfigQuery,
  _ as initPlatformInfoRuntime,
  _n as workspaceRootOptionsQuery,
  _t as codexMobileSetupResumeClientQueryAtom,
  a as lodashBaseRest,
  an as workspaceRootOptionsSelector,
  at as initRemoteConnectionsRuntime,
  b as useAppServerConfigNotices,
  bn as useQueryCacheInvalidator,
  bt as checkCodexMobileMfaSetupRequired,
  c as lodashBaseFlatten,
  cn as codexHomePathSelector,
  ct as useSlingshotEnabled,
  d as lodashDefineProperty,
  dn as initHostConfigRuntime,
  dt as remoteConnectionsSelector,
  en as useMcpServerEnabledMutation,
  et as activeSidebarThreadSelector,
  f as initPlatformModifierRuntime,
  fn as projectWritableRootsByRootSelector,
  ft as getUnaddedRemoteControlConnections,
  g as lodashBaseForOwn,
  gn as threadProjectAssignmentsSelector,
  gt as remoteControlMfaSuppressFeatureId,
  h as lodashBaseEach,
  hn as activeRemoteProjectSelector,
  ht as remoteControlPairingResumeFeatureId,
  i as lodashIsIterateeCall,
  in as activeWorkspaceRootOptionsLoadingSelector,
  it as toggleCodexProjectCollapsed,
  j as sidebarSectionVisibilityAtom,
  jt as AppServerRegistry,
  k as activeSidebarLocationIdAtom,
  kt as initRemoteControlClientApiRuntime,
  l as initFuzzyMatcherRuntime,
  ln as homeDirectoryQuery,
  lt as initRemoteConnectionSelectorsRuntime,
  m as lodashBaseOrderBy,
  mn as remoteProjectsSelector,
  mt as initRemoteControlConnectionFilteringRuntime,
  n as useFuzzyFileSearch,
  nn as userConfigQueryFamily,
  nt as sidebarSectionVisibleSelector,
  o as lodashSetToString,
  on as activeWorkspaceRootsQuery,
  ot as useRemoteConnections,
  p as usePlatformModifierKeys,
  pn as rawRemoteConnectionsSelector,
  pt as filterRemoteControlConnections,
  q as isProjectCollapsedSelector,
  qt as fullMcpServerStatusQueryFamily,
  r as lodashOrderBy,
  rn as activeWorkspaceRootSelector,
  rt as threadSortKeySelector,
  s as lodashOverRest,
  sn as codexHomeQuery,
  st as useRemoteConnectionsFeatureEnabled,
  t as initFuzzyFileSearchRuntime,
  tn as useMcpServerConfigMutation,
  tt as activeSidebarTargetSelector,
  u as scoreFuzzyFileMatch,
  un as hostConfigByHostIdSelector,
  ut as remoteConnectionsLoadingSelector,
  v as usePlatformInfoQuery,
  vn as localWorkspaceRootOptionsQuery,
  vt as useCodexMobileMfaSetupRequiredQuery,
  w as useRequiredAppServerManagerForHost,
  wt as initRemoteControlClientListRuntime,
  x as useConversationAppServerManager,
  xn as initStableCallbackRuntime,
  xt as remoteControlMfaEnabledQueryAtom,
  y as initAppServerRuntime,
  yn as initQueryCacheInvalidationRuntime,
  yt as initCodexMobileMfaSetupRuntime,
  z as setKeepProjectsInRecent,
  zt as userConfigQueryKeyPrefix,
} from "../../vendor/pull-request-new-thread-current-runtime";

// prettier-ignore
export {
  _ as pullRequestNewThreadCompatSlotUnderscore, _n as pullRequestNewThreadCompatSlotUnderscoreLowerN, _t as pullRequestNewThreadCompatSlotUnderscoreLowerT, $ as pullRequestNewThreadCompatSlotDollar,
  $t as pullRequestNewThreadCompatSlotDollarLowerT, a as pullRequestNewThreadCompatSlotLowerA, A as pullRequestNewThreadCompatSlotUpperA, an as pullRequestNewThreadCompatSlotLowerALowerN,
  at as pullRequestNewThreadCompatSlotLowerALowerT, At as pullRequestNewThreadCompatSlotUpperALowerT, b as pullRequestNewThreadCompatSlotLowerB, B as pullRequestNewThreadCompatSlotUpperB,
  bn as pullRequestNewThreadCompatSlotLowerBLowerN, bt as pullRequestNewThreadCompatSlotLowerBLowerT, Bt as pullRequestNewThreadCompatSlotUpperBLowerT, c as pullRequestNewThreadCompatSlotLowerC,
  C as pullRequestNewThreadCompatSlotUpperC, cn as pullRequestNewThreadCompatSlotLowerCLowerN, ct as pullRequestNewThreadCompatSlotLowerCLowerT, Ct as pullRequestNewThreadCompatSlotUpperCLowerT,
  d as pullRequestNewThreadCompatSlotLowerD, D as pullRequestNewThreadCompatSlotUpperD, dn as pullRequestNewThreadCompatSlotLowerDLowerN, dt as pullRequestNewThreadCompatSlotLowerDLowerT,
  Dt as pullRequestNewThreadCompatSlotUpperDLowerT, E as pullRequestNewThreadCompatSlotUpperE, en as pullRequestNewThreadCompatSlotLowerELowerN, et as pullRequestNewThreadCompatSlotLowerELowerT,
  Et as pullRequestNewThreadCompatSlotUpperELowerT, f as pullRequestNewThreadCompatSlotLowerF, F as pullRequestNewThreadCompatSlotUpperF, fn as pullRequestNewThreadCompatSlotLowerFLowerN,
  ft as pullRequestNewThreadCompatSlotLowerFLowerT, Ft as pullRequestNewThreadCompatSlotUpperFLowerT, g as pullRequestNewThreadCompatSlotLowerG, G as pullRequestNewThreadCompatSlotUpperG,
  gn as pullRequestNewThreadCompatSlotLowerGLowerN, gt as pullRequestNewThreadCompatSlotLowerGLowerT, Gt as pullRequestNewThreadCompatSlotUpperGLowerT, h as pullRequestNewThreadCompatSlotLowerH,
  H as pullRequestNewThreadCompatSlotUpperH, hn as pullRequestNewThreadCompatSlotLowerHLowerN, ht as pullRequestNewThreadCompatSlotLowerHLowerT, Ht as pullRequestNewThreadCompatSlotUpperHLowerT,
  i as pullRequestNewThreadCompatSlotLowerI, I as pullRequestNewThreadCompatSlotUpperI, in as pullRequestNewThreadCompatSlotLowerILowerN, it as pullRequestNewThreadCompatSlotLowerILowerT,
  It as pullRequestNewThreadCompatSlotUpperILowerT, j as pullRequestNewThreadCompatSlotLowerJ, J as pullRequestNewThreadCompatSlotUpperJ, jt as pullRequestNewThreadCompatSlotLowerJLowerT,
  Jt as pullRequestNewThreadCompatSlotUpperJLowerT, k as pullRequestNewThreadCompatSlotLowerK, K as pullRequestNewThreadCompatSlotUpperK, kt as pullRequestNewThreadCompatSlotLowerKLowerT,
  Kt as pullRequestNewThreadCompatSlotUpperKLowerT, l as pullRequestNewThreadCompatSlotLowerL, L as pullRequestNewThreadCompatSlotUpperL, ln as pullRequestNewThreadCompatSlotLowerLLowerN,
  lt as pullRequestNewThreadCompatSlotLowerLLowerT, Lt as pullRequestNewThreadCompatSlotUpperLLowerT, m as pullRequestNewThreadCompatSlotLowerM, M as pullRequestNewThreadCompatSlotUpperM,
  mn as pullRequestNewThreadCompatSlotLowerMLowerN, mt as pullRequestNewThreadCompatSlotLowerMLowerT, Mt as pullRequestNewThreadCompatSlotUpperMLowerT, n as pullRequestNewThreadCompatSlotLowerN,
  N as pullRequestNewThreadCompatSlotUpperN, nn as pullRequestNewThreadCompatSlotLowerNLowerN, nt as pullRequestNewThreadCompatSlotLowerNLowerT, Nt as pullRequestNewThreadCompatSlotUpperNLowerT,
  o as pullRequestNewThreadCompatSlotLowerO, O as pullRequestNewThreadCompatSlotUpperO, on as pullRequestNewThreadCompatSlotLowerOLowerN, ot as pullRequestNewThreadCompatSlotLowerOLowerT,
  Ot as pullRequestNewThreadCompatSlotUpperOLowerT, p as pullRequestNewThreadCompatSlotLowerP, P as pullRequestNewThreadCompatSlotUpperP, pn as pullRequestNewThreadCompatSlotLowerPLowerN,
  pt as pullRequestNewThreadCompatSlotLowerPLowerT, Pt as pullRequestNewThreadCompatSlotUpperPLowerT, q as pullRequestNewThreadCompatSlotLowerQ, Q as pullRequestNewThreadCompatSlotUpperQ,
  qt as pullRequestNewThreadCompatSlotLowerQLowerT, Qt as pullRequestNewThreadCompatSlotUpperQLowerT, r as pullRequestNewThreadCompatSlotLowerR, R as pullRequestNewThreadCompatSlotUpperR,
  rn as pullRequestNewThreadCompatSlotLowerRLowerN, rt as pullRequestNewThreadCompatSlotLowerRLowerT, Rt as pullRequestNewThreadCompatSlotUpperRLowerT, s as pullRequestNewThreadCompatSlotLowerS,
  S as pullRequestNewThreadCompatSlotUpperS, sn as pullRequestNewThreadCompatSlotLowerSLowerN, Sn as pullRequestNewThreadCompatSlotUpperSLowerN, st as pullRequestNewThreadCompatSlotLowerSLowerT,
  St as pullRequestNewThreadCompatSlotUpperSLowerT, t as pullRequestNewThreadCompatSlotLowerT, T as pullRequestNewThreadCompatSlotUpperT, tn as pullRequestNewThreadCompatSlotLowerTLowerN,
  tt as pullRequestNewThreadCompatSlotLowerTLowerT, Tt as pullRequestNewThreadCompatSlotUpperTLowerT, u as pullRequestNewThreadCompatSlotLowerU, U as pullRequestNewThreadCompatSlotUpperU,
  un as pullRequestNewThreadCompatSlotLowerULowerN, ut as pullRequestNewThreadCompatSlotLowerULowerT, Ut as pullRequestNewThreadCompatSlotUpperULowerT, v as pullRequestNewThreadCompatSlotLowerV,
  V as pullRequestNewThreadCompatSlotUpperV, vn as pullRequestNewThreadCompatSlotLowerVLowerN, vt as pullRequestNewThreadCompatSlotLowerVLowerT, Vt as pullRequestNewThreadCompatSlotUpperVLowerT,
  w as pullRequestNewThreadCompatSlotLowerW, W as pullRequestNewThreadCompatSlotUpperW, wt as pullRequestNewThreadCompatSlotLowerWLowerT, Wt as pullRequestNewThreadCompatSlotUpperWLowerT,
  x as pullRequestNewThreadCompatSlotLowerX, X as pullRequestNewThreadCompatSlotUpperX, xn as pullRequestNewThreadCompatSlotLowerXLowerN, xt as pullRequestNewThreadCompatSlotLowerXLowerT,
  Xt as pullRequestNewThreadCompatSlotUpperXLowerT, y as pullRequestNewThreadCompatSlotLowerY, Y as pullRequestNewThreadCompatSlotUpperY, yn as pullRequestNewThreadCompatSlotLowerYLowerN,
  yt as pullRequestNewThreadCompatSlotLowerYLowerT, Yt as pullRequestNewThreadCompatSlotUpperYLowerT, z as pullRequestNewThreadCompatSlotLowerZ, Z as pullRequestNewThreadCompatSlotUpperZ,
  zt as pullRequestNewThreadCompatSlotLowerZLowerT, Zt as pullRequestNewThreadCompatSlotUpperZLowerT
} from "../../vendor/pull-request-new-thread-current-runtime";
