// Restored from ref/webview/assets/app-initial~app-main~remote-conversation-page~new-thread-panel-page~projects-index-page~app~iy8s9c2d-BUvvfhQQ.js
// Semantic export map for the current app-initial remote/projects shared runtime chunk.
// Every minified public binding is exposed below with a stable restored name.

import {
  Bl as logProductEvent,
  Ea as Navigate,
  Fa as useWorkspaceNavigation,
  fn as initRemoteControlConnectionRuntime,
  Iy as initIntlFormattingRuntime,
  Kp as initRemoteControlRefreshSourceRuntime,
  La as useHotkeyRouteParams,
  mn as remoteControlStatusSignal,
  nv as initAppHostServicesRuntime,
  om as useLocalStorageSetting,
  pn as remoteControlHostEnabledSignal,
  Qf as codexMobileSetupStepViewedEvent,
  Qp as initCurrentSharedDisplayRuntime,
  Rl as initRemoteConnectionRuntime,
  ry as useFeatureFlag,
  tv as appHostServices,
  ty as initCurrentSharedRemoteRuntime,
  xa as initOpenAiNativeAppRuntime,
  Zf as codexMobileSetupActionEvent,
  zy as FormattedMessage,
  em as localRemoteControlHostId,
} from "../../vendor/remote-projects-app-shared-current-bundle";

export {
  appHostServices,
  codexMobileSetupActionEvent,
  codexMobileSetupStepViewedEvent,
  FormattedMessage,
  initAppHostServicesRuntime,
  initCurrentSharedDisplayRuntime,
  initCurrentSharedRemoteRuntime,
  initIntlFormattingRuntime,
  initOpenAiNativeAppRuntime,
  initRemoteConnectionRuntime,
  initRemoteControlConnectionRuntime,
  initRemoteControlRefreshSourceRuntime,
  localRemoteControlHostId,
  logProductEvent,
  Navigate,
  remoteControlHostEnabledSignal,
  remoteControlStatusSignal,
  useFeatureFlag,
  useHotkeyRouteParams,
  useLocalStorageSetting,
  useWorkspaceNavigation,
};

export function initRemoteProjectsAppSharedSemanticRuntime(): void {
  initAppHostServicesRuntime();
  initIntlFormattingRuntime();
  initOpenAiNativeAppRuntime();
  initRemoteControlConnectionRuntime();
  initRemoteControlRefreshSourceRuntime();
  initCurrentSharedDisplayRuntime();
  initRemoteConnectionRuntime();
  initCurrentSharedRemoteRuntime();
}

// App Host Services
// prettier-ignore
export { nv as initAppHostServicesRuntimeChunkRaw, rv as connectAppHostServicesRaw, tv as appHostServicesRaw } from "../../vendor/remote-projects-app-shared-current-bundle";

// Helpers
// prettier-ignore
export { Dp as markdownCodeBlockParserRuntime, H_ as coerceObjectLikeHelper, Iy as intlFormatDateTimeRuntime, Jy as copyObjectExcludingKeysHelper, Ky as extendClassPrototypeHelper, Ly as dateTimeNumberFormatters, R_ as symbolObjectCoercionHelper, Vc as usingDeclarationsRuntimeHelper, Wy as setPrototypeOfHelperBinding, Xy as initializeTypeScriptClassHelpers, Yy as appendArrayLikeHelper, Z_ as coercePrimitivePropertyKeyHelper, Zp as randomUuidBytesHelper, do as computerUseIntlMessages } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { km as jsonStringEscapeRuntime } from "../../vendor/remote-projects-app-shared-current-bundle";

// Persistence And Signals
// prettier-ignore
export { $i as currentAppInitialSharedStaleTimeQuery, Cc as threadWorkspaceStatePersistedAtom, Cy as clearPersistedAtomLocalStorage, Ec as loadThreadAssignmentFromCache, Ey as initPersistedAtomStorageRuntime, Fy as createScopedSignalAtom, Gc as terminalTerminalExitInitSignal, Gn as gitBranchDiffStatsQuery, Gs as memoryFeatureGateConfigSchema, Js as parseMemoryConfiguration, Ln as reactRouterGitMetadataAlwaysQuery, Lp as remoteConnectionStateSignals, My as createPersistedSignalAtom, N as appServerDisconnectedAppServerSignal } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Sc as getGlobalStateQueryRuntime, Ty as createSignalGetterAtom, Up as codexAnalyticsSignalRuntime, Vs as statsigFeatureOverrideSignalRuntime, Zn as automationIdleFetchFetchingQuery, _o as currentAppInitialSharedInfoStaleTimeQuery, en as reactRouterVscodeIpcClientSignal, gr as conversationRunStatusSignalRuntime, gy as currentAppInitialSharedSignalCacheScopeSignal, hm as createSharedObjectSignalAtom, hy as currentAppInitialSharedSignalSignal, ir as workspaceWatchRepoUnwatchSignal, la as osInfoQueryRuntime, ln as whamApiRateLimitWhamQuery } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ly as statsigMountSignal, nn as ipcBridgeIpcBroadcastIgnoringSignal, pa as osInfoSignalRuntime, py as statsigModuleStatsigProviderSchema, qc as threadTerminalSnapshotSignalRuntime, ra as currentAppInitialSharedOwlFeatureFeaturesRuntime, rs as appgenPublicationTermsDisclosureSignal, sr as workspaceMetadataMethodProcessQuery, wy as currentAppInitialSharedRemoveSubscribeCallbackSignal, xg as appServerRequestMessageHandlerAtom, xi as analyticsProtobufAnalyticsMemoryRuntime, xy as persistedAtomMember0889 } from "../../vendor/remote-projects-app-shared-current-bundle";

// App Actions And Desktop Context
// prettier-ignore
export { Ac as buildTerminalSteerContentItem, Fg as normalizeDiffLineRange, Fv as scrollAppActionEdgeIntoView, Gh as buildDesktopContextSection, Hv as scrollAppActionByPayload, Ig as mergeDiffLineRanges, Li as currentAppInitialSharedBrowserDiffMcpRuntime, Ph as parseCodexDelegationXml, Pv as scrollAppActionTargetIntoView, Sa as parseUnifiedDiffPatchHeader, Th as currentAppInitialSharedBrowserFunction, Uv as dispatchRegisteredAppAction, Uy as buildTextContentItem, Vg as parseReviewCommentBody } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ws as readDesktopContextSectionFlags, _g as buildIdeFileAttachmentList, bg as serializeIdeFileLocation, ch as buildNotebookRangeAnnotation, fg as formatIdeFilePreviewLabel, jh as buildCodexDelegationXml, kh as currentAppInitialSharedGoalRuntime, pv as appActionRegisterAppActionsFunction, qh as codeReviewPromptSections, qi as threadRuntimeBrowserTabConversationRuntime, vh as codeReviewFunction0841, wh as currentAppInitialSharedArtifactAnnotationBrowserFunction, zg as joinReviewCommentText } from "../../vendor/remote-projects-app-shared-current-bundle";

// Tools And Permissions
// prettier-ignore
export { $h as browserToolSourceName, $o as finalAnswerToolNameGuard, Do as loadWorkspaceDependenciesToolDefinition, Jo as appgenSiteToolSchemas, Ka as doesToolSurfaceSupportSleep, Mm as currentAppInitialSharedImagePickerIntegerFunction, Om as toolSuggestionAndConnectorSchema, Qo as callAppgenJsonRpcTool, Uo as whamApiWhamAppsToolsSchema, Wc as readThreadTerminalToolRuntime, Yc as readThreadTerminalToolDefinition, Yl as imagePickerToolSchema, Zl as normalizeToolSuggestionAction, Zt as permissionApprovalThreadProjectAssignmentMessages } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { _m as permissionApprovalRuntime0453, bo as browserGoogleChromeToolRuntime, co as currentAppInitialSharedAppsServerToolTool, dm as selectLatestDynamicElicitationRequest, fm as isApprovalRequestItem, go as filterComputerUseToolFunctions, jm as schemaImagePickerTitleSchema, ki as permissionApprovalProtobufAnalyticsComputerTool, mm as isApprovalOrElicitationRequestItem, mo as normalizeNativeAppToolSurface, qs as browserTabContextToolDefinition, so as computerUseToolSurfaceSchema, uh as interactiveOnboardingToolSchemas, yo as browserToolMember0901 } from "../../vendor/remote-projects-app-shared-current-bundle";

// Remote And App Server
// prettier-ignore
export { Au as remoteConnectionMember0032, Bp as getConnectionSourceAnalyticsMetadata, Ff as remoteConnectionMember0101, Fl as remoteConnectionDisconnectedConnectingRestartingFunction, Ip as logRemoteConnectionStateChanged, J_ as createWhamApiRequestClient, Jt as serviceTierPriorityServiceTierMessages, Kn as isKnownAppServerMethodError, Lh as currentAppInitialSharedTextElementsHostFunction, Ll as remoteConnectionRuntime0201, Nl as remoteConnectionConnectionAnalyticsFunction, Np as isTransientRemoteConnectionState, Pp as classifyRemoteConnectionFailureCode, Qt as ipcBridgeUnreadThreadHostRuntime } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Qu as remoteConnectionMember0289, Rl as remoteConnectionRuntime0298, Ud as remoteConnectionMember0348, Yn as workspaceCwdHostConfigFunction, _l as threadRuntimeNeedsResumeHostFunction, _p as remoteConnectionMember0456, am as remoteConnectionRuntime0472, cm as localRemoteConnectionDescriptorSchema, fn as currentAppInitialSharedControlConnectConnectionRuntime, ic as serializeRemoteHostConfigLayers, im as waitForRemoteConnectionsConfiguration, nc as requestRemoteHostConfigRead, pg as removePastedTextAttachmentForHost, sm as localRemoteConnectionKind } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { yc as ipcBridgeRuntime0893, zh as currentAppInitialSharedImageHostUrlFunction } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { S as appServerRegistryAtom } from "../../vendor/remote-projects-app-shared-current-bundle";

// Conversation And Threads
// prettier-ignore
export { $_ as currentAppInitialSharedRuntime0002, $a as currentAppInitialSharedRuntime0003, $c as threadRuntimeRuntime0004, $n as conversationResumeStateSchema, $t as currentAppInitialSharedRuntime0014, A_ as threadRuntimeCanonicalFunction, Ar as skillPathAgentsSkillsImportRuntime, As as forkedConversationMetadataSchema, B_ as currentAppInitialSharedRuntime0036, Ba as automationCronHeartbeatCreateMessages, Bh as goalSlashCommandRuntime, C_ as threadRuntimeRuntime0052, Cd as reduceCanonicalConversationHistory, Ch as currentAppInitialSharedRuntime0056 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Cr as canonicalConversationSummaryMapper, Cs as trackConversationPhaseAction, D_ as threadRuntimeCanonicalFunctionVariant02, Dc as collectRuntimeWorkspaceRoots, Dd as findCanonicalConversationHistoryEntry, Dg as appServerRuntime0070, E_ as threadRuntimeCanonicalFunctionVariant03, F_ as currentAppInitialSharedRuntime0100, Fd as getCanonicalThreadId, Fn as automationTaskStubCitationRuntime, G_ as helperSymbolRuntime, Ga as currentAppInitialSharedRuntime0115, Gg as currentAppInitialSharedRuntime0119, Hg as currentAppInitialSharedRuntime0134 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Hi as reactRouterRouteScopeParentRuntime, Hn as reactRouterInvalidateGitReadFunction, Ho as buildStartTurnWorkspaceContext, I_ as currentAppInitialSharedRuntime0147, In as reactRouterFunction0155, Ja as currentAppInitialSharedRuntime0164, Jg as currentAppInitialSharedRuntime0168, Jv as appActionWindowTargetRuntime, Ks as threadRuntimeMember0188, L_ as currentAppInitialSharedRuntime0193, Lg as currentAppInitialSharedRuntime0198, Lm as schemaRuntime0202, M_ as currentAppInitialSharedNotifyDontDecisionMessages, Mc as threadRuntimeFunction0212 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Mg as currentAppInitialSharedRuntime0214, Ml as createWorkerModuleRuntime, Ms as currentAppInitialSharedRuntime0222, N_ as currentAppInitialSharedRuntime0226, Na as useReactRouterLocationInvariant, Ng as currentAppInitialSharedRuntime0230, Nh as currentAppInitialSharedRuntime0231, O_ as threadRuntimeCanonicalFunctionVariant04, Oa as reactRouterRouteComponentInvariant, Or as threadRuntimeRuntime0254, P_ as currentAppInitialSharedRuntime0261, Pg as currentAppInitialSharedRuntime0266, Pi as threadRuntimeRuntime0267, Pr as currentAppInitialSharedRuntime0270 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Qa as currentAppInitialSharedRuntime0276, Qh as normalizeThreadPositionPayload, Qp as currentAppInitialSharedDisplayRuntime, Qr as appgenRuntime0286, Rc as unarchivedConversationLoadErrorSchema, Rh as delegationRuntime0296, Ri as reactRouterMember0297, Rn as reactRouterFunction0300, Rv as currentAppInitialSharedRuntime0307, Sr as threadRuntimeUpdateThreadGitFunction, Tl as schemaRuntime0334, Tm as currentAppInitialSharedImplementPlanImplementationRuntime, Tr as currentAppInitialSharedRuntime0339, Ts as threadRuntimeForkedConversationTitleFunction } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { U_ as currentAppInitialSharedRuntime0345, Ua as workspaceRuntime0346, Ug as currentAppInitialSharedRuntime0350, Ur as codexTextLinkTextLinkPromptRuntime, V_ as currentAppInitialSharedRuntime0362, Va as buildUserPromptSubmitMessage, Vi as threadRuntimeHomePanelThreadFunction, W_ as currentAppInitialSharedRuntime0377, Xa as currentAppInitialSharedRuntime0394, Xc as currentAppInitialSharedRuntime0395, Xg as currentAppInitialSharedRuntime0398, Yp as currentAppInitialSharedTitleAddressArticleRuntime, Yv as reactRouterWorkersModuleDisposeSchema, Zc as threadRuntimeFunction0430 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Zh as currentAppInitialSharedRuntime0434, _a as threadRuntimeClientThreadDraftFunction, _c as currentAppInitialSharedRuntime0447, _r as currentAppInitialSharedRuntime0457, al as threadRuntimeFunction0471, b_ as threadRuntimeFunction0483, ba as threadScopeConversationPanelRuntime, bc as threadRuntimeCwdPendingCoreFunction, bd as getCanonicalConversationGroupId, bh as currentAppInitialSharedRuntime0487, cg as currentAppInitialSharedDevRuntime, cl as threadRuntimeCanonicalFunctionVariant05, cn as threadRuntimeChatgptComCyberRuntime, cr as currentAppInitialSharedRuntime0512 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { cs as currentAppInitialSharedRuntime0513, cv as currentAppInitialSharedRuntime0516, di as markdownAvifJpegTiffRuntime, ds as ensureFollowerConversationAvailable, e_ as currentAppInitialSharedRuntime0533, el as currentAppInitialSharedRuntime0541, er as normalizeThreadRuntimeStatus, f_ as currentAppInitialSharedRuntime0552, fc as serviceTierRuntime0553, fl as currentAppInitialSharedTruncatedPreviewRuntime, fr as currentAppInitialSharedRuntime0561, fs as currentAppInitialSharedRuntime0562, gg as currentAppInitialSharedRuntime0573, gh as currentAppInitialSharedRuntime0574 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { gl as threadRuntimeNeedsResumeResumingFunction, gm as implementPlanPromptMessage, gs as currentAppInitialSharedRuntime0579, hc as threadRuntimeWorkspaceRootsFallbackFunction, hl as currentAppInitialSharedRuntime0592, ho as currentAppInitialSharedRuntime0594, hr as currentAppInitialSharedRuntime0596, hs as threadRuntimeFunction0597, ii as markdown7zipxAccdbAsarpackRuntime, il as threadRuntimeFunction0610, j_ as currentAppInitialSharedRuntime0621, ja as reactRouterCaseSensitiveParamSchema, jc as threadRuntimeFunction0623, jl as currentAppInitialSharedDisconnectedConnectingConnectedRuntime } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { jr as currentAppInitialSharedRuntime0633, js as currentAppInitialSharedRuntime0634, k_ as currentAppInitialSharedRuntime0640, kc as threadRuntimeRuntime0642, kg as currentAppInitialSharedRuntime0645, ks as currentAppInitialSharedRuntime0652, l_ as currentAppInitialSharedRuntime0658, lo as schemaRuntime0668, lr as gitRuntime0670, mc as currentAppInitialSharedRuntime0679, mh as threadRuntimeFunction0683, mi as currentAppInitialSharedRuntime0684, ml as currentAppInitialSharedRuntime0685, mr as truncatedPayloadPreviewMessage } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ms as currentAppInitialSharedRuntime0688, nm as currentAppInitialSharedRuntime0702, nv as currentAppInitialSharedRuntime0710, o_ as currentAppInitialSharedRuntime0713, or as workspaceRuntime0726, ov as currentAppInitialSharedRuntime0729, pl as threadRuntimeFunction0738, pm as currentAppInitialSharedRuntime0739, ps as startThreadFollowerTurn, qp as currentAppInitialSharedRuntime0757, qv as currentAppInitialSharedRuntime0761, rl as currentAppInitialSharedRuntime0772, rm as currentAppInitialSharedRuntime0773, sc as currentAppInitialSharedArcFlowSizeRuntime } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { sl as currentAppInitialSharedRuntime0791, ss as threadRuntimeRuntime0795, tn as currentAppInitialSharedRuntime0809, ty as currentAppInitialSharedRuntime0816, u_ as currentAppInitialSharedRuntime0818, ul as threadRuntimeStartedTimedOutSchema, us as currentAppInitialSharedRuntime0831, v_ as startedWindowConversationWarningMessage, vg as currentAppInitialSharedRuntime0840, vl as threadRuntimeRuntime0843, vs as reactRouterRuntime0849, w_ as threadRuntimeFunction0855, wo as currentAppInitialSharedRuntime0866, xr as findConversationRunStatusByValue } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { xv as currentAppInitialSharedPixelsPagesEdgeRuntime, y_ as currentAppInitialSharedRuntime0891, ya as threadScopeHomeEntrypointFunction, yd as getCanonicalConversationId, ym as currentAppInitialSharedFullPositionAccumulatedRuntime, yr as updateConversationRunStatusByValue, z_ as currentAppInitialSharedRuntime0908, zc as terminalSteerOutcomeMessages, zl as analyticsLogProductTrackRuntime, zn as gitUpstreamBranchBaseRuntime } from "../../vendor/remote-projects-app-shared-current-bundle";

// Workspace Terminal Git
// prettier-ignore
export { Fa as parseWorkspaceRootPathList, Is as workspaceSectionWorkspaceDependenciesSchema, Ps as isWorkspaceWritableRoot, ur as gitYouAgreedXcodeFunction, vn as workspaceCwdBranchUrlSchema, yn as workspaceCwdBranchUrlSchemaVariant02 } from "../../vendor/remote-projects-app-shared-current-bundle";

// Appgen Automation Computer Use
// prettier-ignore
export { oo as computerUseNativeAppChromeFunction, os as setAppgenPublicationTermsAudience, po as normalizeComputerUseAppReference, ta as googleChromeMacAppDefinition, ts as hasSeenAppgenPublicationTermsDisclosure, va as formatMacAppTitle, xa as openAiNativeAppDefinition } from "../../vendor/remote-projects-app-shared-current-bundle";

// Schemas And Descriptors
// prettier-ignore
export { Am as currentAppInitialSharedRequiredSchema, Bl as imagePickerSchemaCapabilities, Bs as desktopContextSectionFlagsSchema, Fc as collectPendingCoreUpdateState, Fs as workspaceDisableExposureLogSchema, Gv as appActionPayloadSchema, Ic as handleSetGlobalStateAppRequest, Im as currentAppInitialSharedEnumSchema, Jn as appServerErrorSchema, Kg as deletedFilePathSentinelSchema, Kp as remoteControlRefreshSourceEnum, Pl as formatJsonSchemaOptionLabels, Pm as currentAppInitialSharedEnumIntegerInvalidSchema, Po as automationDefinitionSchemas } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Sl as modelContextProtocolRelatedTaskSchema, Sm as resourceMetadataSchema, Us as memoryGenerateMemoriesDisableSchema, Vl as extractJsonSchemaRequiredFields, Wo as appgenProjectAccessSchemas, Xr as schemaAvifDocxJpegSchema, _s as arcFlowLayoutOptionsSchema, bl as schemaMethodFoundVariantSchema, eh as whamApiModelcontextprotocolRelatedTaskSchema, fv as schemaSchema0565, kl as describeInvalidSchemaField, my as currentAppInitialSharedModuleDiagnosticsLoggerSchema, xl as helperImmerNothingDraftableSchema, xm as normalizeTaskCompletionState } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { yl as schemaSchema0898 } from "../../vendor/remote-projects-app-shared-current-bundle";

// Current App Initial Shared Members
// prettier-ignore
export { $ as currentAppInitialSharedMember0001, $d as currentAppInitialSharedMember0005, $f as currentAppInitialSharedMember0006, $g as currentAppInitialSharedFunction0007, $l as currentAppInitialSharedMember0009, $m as currentAppInitialSharedMember0010, $p as currentAppInitialSharedMember0011, $r as workspaceCwdProjectlessDirectoryFunction, $s as currentAppInitialSharedMember0013, $u as currentAppInitialSharedMember0015, $v as statsigFunction0016, A as currentAppInitialSharedMember0017, Aa as currentAppInitialSharedMember0019, Ad as currentAppInitialSharedMember0020 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Af as currentAppInitialSharedMember0021, Ag as currentAppInitialSharedFunction0022, Ah as currentAppInitialSharedMember0023, Ai as currentAppInitialSharedLegacyFunction, Al as currentAppInitialSharedMember0025, An as currentAppInitialSharedMember0027, Ao as currentAppInitialSharedMember0028, Ap as currentAppInitialSharedMember0029, At as currentAppInitialSharedMember0031, Av as appActionMember0033, Ay as currentAppInitialSharedFunction0034, B as currentAppInitialSharedMember0035, Bc as currentAppInitialSharedMember0038, Bd as currentAppInitialSharedMember0039 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Bf as currentAppInitialSharedMember0040, Bg as currentAppInitialSharedPositionColumnFunction, Bi as currentAppInitialSharedMember0042, Bm as currentAppInitialSharedMember0043, Bn as currentAppInitialSharedMember0044, Bo as currentAppInitialSharedMember0045, Br as currentAppInitialSharedMember0046, Bt as serviceTierFastPriorityFunction, Bu as currentAppInitialSharedMember0048, Bv as currentAppInitialSharedFunction0049, By as currentAppInitialSharedMember0050, C as currentAppInitialSharedMember0051, Ca as currentAppInitialSharedMember0053, Cf as currentAppInitialSharedMember0054 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Cg as currentAppInitialSharedFunction0055, Ci as analyticsMember0057, Cl as schemaMember0058, Cm as currentAppInitialSharedInterruptedProgressFunction, Cn as currentAppInitialSharedMember0060, Co as currentAppInitialSharedFinalAnswerFunction, Cp as currentAppInitialSharedMember0062, Ct as currentAppInitialSharedMember0063, Cu as currentAppInitialSharedMember0064, Cv as currentAppInitialSharedEdgePixelsReversedFunction, D as currentAppInitialSharedMember0066, Da as currentAppInitialSharedMember0068, Df as currentAppInitialSharedMember0069, Dh as currentAppInitialSharedFunction0071 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Di as analyticsMember0072, Dl as currentAppInitialSharedMember0073, Dm as currentAppInitialSharedAcceptDeclineCancelFunction, Dn as currentAppInitialSharedMember0075, Dr as currentAppInitialSharedCommandExecutionFunction, Ds as currentAppInitialSharedMember0077, Dt as currentAppInitialSharedMember0078, Du as currentAppInitialSharedMember0079, Dv as currentAppInitialSharedMember0080, Dy as currentAppInitialSharedMember0081, E as currentAppInitialSharedProgressFunction, Ea as currentAppInitialSharedMember0084, Ed as currentAppInitialSharedMember0085, Ef as currentAppInitialSharedMember0086 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Eg as currentAppInitialSharedMember0087, Eh as writeHtmlDocumentToTarget, Ei as analyticsMember0088, El as schemaFunction0089, Em as currentAppInitialSharedMember0090, En as currentAppInitialSharedMember0091, Eo as workspaceMember0092, Ep as currentAppInitialSharedMember0093, Er as currentAppInitialSharedMember0094, Es as currentAppInitialSharedMember0095, Et as currentAppInitialSharedMember0096, Eu as currentAppInitialSharedMember0097, Ev as currentAppInitialSharedMember0098, F as currentAppInitialSharedMember0099 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Fh as currentAppInitialSharedMember0102, Fi as currentAppInitialSharedMember0103, Fm as currentAppInitialSharedMember0105, Fo as currentAppInitialSharedMember0107, Fp as currentAppInitialSharedMember0108, Fr as codexTextLinkMember0109, Ft as currentAppInitialSharedMember0111, Fu as currentAppInitialSharedMember0112, G as currentAppInitialSharedMember0113, Gd as currentAppInitialSharedMember0117, Gf as currentAppInitialSharedMember0118, Gi as currentAppInitialSharedMember0120, Gl as currentAppInitialSharedMember0121, Gm as currentAppInitialSharedMember0122 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Go as currentAppInitialSharedMember0124, Gp as currentAppInitialSharedMember0125, Gr as currentAppInitialSharedMember0126, Gt as currentAppInitialSharedMember0127, Gu as currentAppInitialSharedMember0128, Gy as createLocalStorageBackedAdapter, H as currentAppInitialSharedMember0129, Ha as workspaceRootFunction, Hc as currentAppInitialSharedTextFunction, Hd as currentAppInitialSharedMember0132, Hf as currentAppInitialSharedMember0133, Hh as currentAppInitialSharedMember0135, Hl as analyticsMember0137, Hm as currentAppInitialSharedMember0138 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Hp as currentAppInitialSharedMember0140, Hr as currentAppInitialSharedMember0141, Hs as currentAppInitialSharedMember0142, Ht as currentAppInitialSharedFunction0143, Hu as currentAppInitialSharedMember0144, Hy as currentAppInitialSharedMember0145, I as currentAppInitialSharedMember0146, Ia as currentAppInitialSharedMember0148, Id as currentAppInitialSharedMember0149, If as currentAppInitialSharedMember0150, Ih as currentAppInitialSharedFunction0151, Ii as currentAppInitialSharedMember0152, Il as currentAppInitialSharedMember0153, Io as currentAppInitialSharedMember0156 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ir as codexTextLinkMember0157, It as currentAppInitialSharedMember0159, Iu as currentAppInitialSharedMember0160, Iv as workspaceFunction0161, J as currentAppInitialSharedMember0163, Jc as terminalMember0165, Jd as currentAppInitialSharedMember0166, Jf as currentAppInitialSharedMember0167, Jh as currentAppInitialSharedMember0169, Ji as currentAppInitialSharedMember0170, Jl as currentAppInitialSharedMember0171, Jm as currentAppInitialSharedMember0172, Jp as currentAppInitialSharedRandomBytesLengthFunction, Jr as currentAppInitialSharedMember0174 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ju as currentAppInitialSharedMember0176, K as currentAppInitialSharedMember0177, K_ as currentAppInitialSharedMember0178, Kc as currentAppInitialSharedMember0179, Kd as currentAppInitialSharedMember0180, Kf as currentAppInitialSharedMember0181, Kh as currentAppInitialSharedMember0182, Ki as currentAppInitialSharedMember0183, Kl as currentAppInitialSharedMember0184, Km as currentAppInitialSharedMember0185, Ko as currentAppInitialSharedMember0186, Kr as currentAppInitialSharedMember0187, Kt as currentAppInitialSharedMember0189, Ku as currentAppInitialSharedMember0190 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Kv as currentAppInitialSharedFunction0191, L as currentAppInitialSharedMember0192, La as currentAppInitialSharedMember0194, Lc as currentAppInitialSharedMember0195, Ld as currentAppInitialSharedMember0196, Lf as currentAppInitialSharedMember0197, Lo as currentAppInitialSharedMember0204, Lr as codexTextLinkMember0205, Ls as currentAppInitialSharedMember0206, Lt as currentAppInitialSharedMember0207, Lu as currentAppInitialSharedMember0208, Lv as currentAppInitialSharedMember0209, M as currentAppInitialSharedMember0210, Ma as renderMarkdownBoldTextSegments } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Md as normalizeStringRecordValue, Mf as currentAppInitialSharedMember0213, Mh as currentAppInitialSharedMember0215, Mi as currentAppInitialSharedFunction0216, Mn as currentAppInitialSharedMember0218, Mo as currentAppInitialSharedMember0219, Mp as currentAppInitialSharedMember0220, Mr as currentAppInitialSharedFunction0221, Mt as currentAppInitialSharedMember0223, Mu as currentAppInitialSharedMember0224, Mv as appActionDomAttributeSelectors, Nc as currentAppInitialSharedMember0227, Nd as currentAppInitialSharedMember0228, Nf as currentAppInitialSharedMember0229 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ni as currentAppInitialSharedMember0232, Nm as currentAppInitialSharedMember0234, Nn as currentAppInitialSharedMember0235, No as createAbortError, Nr as currentAppInitialSharedFunction0236, Ns as currentAppInitialSharedFunction0237, Nt as currentAppInitialSharedMember0238, Nu as currentAppInitialSharedMember0239, Nv as currentAppInitialSharedMember0240, Ny as currentAppInitialSharedMember0241, O as currentAppInitialSharedFunction0242, Oc as currentAppInitialSharedMember0244, Od as currentAppInitialSharedMember0245, Of as currentAppInitialSharedMember0246 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Og as currentAppInitialSharedFunction0247, Oh as currentAppInitialSharedFunction0248, Oi as currentAppInitialSharedMember0249, Ol as currentAppInitialSharedMember0250, On as currentAppInitialSharedMember0251, Oo as currentAppInitialSharedMember0252, Op as currentAppInitialSharedMember0253, Os as currentAppInitialSharedMember0255, Ot as currentAppInitialSharedMember0256, Ou as currentAppInitialSharedMember0257, Ov as currentAppInitialSharedMember0258, Oy as currentAppInitialSharedMember0259, P as currentAppInitialSharedMember0260, Pa as currentAppInitialSharedMember0262 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Pc as currentAppInitialSharedMember0263, Pd as currentAppInitialSharedMember0264, Pf as currentAppInitialSharedMember0265, Pn as currentAppInitialSharedMember0269, Pt as currentAppInitialSharedMember0271, Pu as currentAppInitialSharedMember0272, Py as currentAppInitialSharedMember0273, Q as currentAppInitialSharedMember0274, Q_ as currentAppInitialSharedFunction0275, Qc as currentAppInitialSharedMember0277, Qd as currentAppInitialSharedMember0278, Qf as currentAppInitialSharedMember0279, Qg as currentAppInitialSharedMember0280, Qi as currentAppInitialSharedMember0281 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ql as currentAppInitialSharedMember0282, Qm as currentAppInitialSharedMember0283, Qn as currentAppInitialSharedMember0284, Qs as currentAppInitialSharedMember0287, Qv as statsigFunction0290, R as currentAppInitialSharedMember0291, Ra as currentAppInitialSharedMember0292, Rd as currentAppInitialSharedMember0293, Rf as currentAppInitialSharedMember0294, Rg as currentAppInitialSharedFunction0295, Rm as currentAppInitialSharedMember0299, Ro as currentAppInitialSharedMember0301, Rp as currentAppInitialSharedMember0302, Rr as markdownFunction0303 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Rs as statsigMember0304, Rt as serviceTierMember0305, Ru as currentAppInitialSharedMember0306, Ry as currentAppInitialSharedMember0308, S as currentAppInitialSharedMember0309, S_ as currentAppInitialSharedFunction0310, Sd as currentAppInitialSharedMember0311, Sf as currentAppInitialSharedMember0312, Sg as currentAppInitialSharedPreviewFunction, Sh as currentAppInitialSharedMember0314, Si as analyticsMember0315, Sn as currentAppInitialSharedMember0316, So as currentAppInitialSharedFunction0317, Sp as currentAppInitialSharedMember0318 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Ss as currentAppInitialSharedMember0320, St as currentAppInitialSharedMember0321, Su as currentAppInitialSharedMember0322, Sv as currentAppInitialSharedAutoPixelsPagesFunction, Sy as currentAppInitialSharedMember0324, T as currentAppInitialSharedFunction0325, T_ as currentAppInitialSharedCanonicalHistoryFunction, Ta as currentAppInitialSharedMember0327, Tc as currentAppInitialSharedMember0328, Td as currentAppInitialSharedMember0329, Tf as currentAppInitialSharedMember0330, Tg as currentAppInitialSharedMember0331, Ti as currentAppInitialSharedMember0333, Tn as currentAppInitialSharedMember0336 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { To as workspaceMember0337, Tp as currentAppInitialSharedMember0338, Tt as currentAppInitialSharedMember0341, Tu as currentAppInitialSharedMember0342, Tv as currentAppInitialSharedMember0343, U as currentAppInitialSharedMember0344, Uc as currentAppInitialSharedMember0347, Uf as currentAppInitialSharedMember0349, Uh as currentAppInitialSharedMember0351, Ui as currentAppInitialSharedMember0352, Ul as currentAppInitialSharedMember0353, Um as currentAppInitialSharedMember0354, Un as currentAppInitialSharedMember0355, Ut as currentAppInitialSharedMember0359 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Uu as currentAppInitialSharedMember0360, V as currentAppInitialSharedMember0361, Vd as currentAppInitialSharedMember0363, Vf as currentAppInitialSharedMember0364, Vh as currentAppInitialSharedMember0365, Vm as currentAppInitialSharedMember0367, Vn as currentAppInitialSharedMember0368, Vo as currentAppInitialSharedMember0369, Vp as currentAppInitialSharedMember0370, Vr as currentAppInitialSharedMember0371, Vt as currentAppInitialSharedMember0372, Vu as currentAppInitialSharedMember0373, Vv as currentAppInitialSharedFunction0374, Vy as currentAppInitialSharedFunction0375 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { W as currentAppInitialSharedMember0376, Wa as currentAppInitialSharedFunction0378, Wd as currentAppInitialSharedMember0379, Wf as currentAppInitialSharedMember0380, Wg as currentAppInitialSharedMember0381, Wh as currentAppInitialSharedMember0382, Wi as currentAppInitialSharedMember0383, Wl as currentAppInitialSharedMember0384, Wm as currentAppInitialSharedMember0385, Wn as currentAppInitialSharedMember0386, Wp as currentAppInitialSharedMember0387, Wr as markdownFunction0388, Wt as currentAppInitialSharedMember0389, Wu as currentAppInitialSharedMember0390 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Wv as currentAppInitialSharedFunction0391, X as currentAppInitialSharedMember0392, X_ as currentAppInitialSharedFunction0393, Xd as currentAppInitialSharedMember0396, Xf as currentAppInitialSharedMember0397, Xh as currentAppInitialSharedFunction0399, Xi as currentAppInitialSharedMember0400, Xl as currentAppInitialSharedMember0401, Xm as currentAppInitialSharedMember0402, Xn as currentAppInitialSharedMember0403, Xo as currentAppInitialSharedMember0404, Xp as currentAppInitialSharedFunction0405, Xs as currentAppInitialSharedMember0407, Xt as currentAppInitialSharedFunction0408 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Xu as currentAppInitialSharedMember0409, Xv as helperMember0410, Y as currentAppInitialSharedMember0411, Y_ as currentAppInitialSharedMember0412, Ya as currentAppInitialSharedMember0413, Yd as currentAppInitialSharedMember0414, Yf as currentAppInitialSharedMember0415, Yg as currentAppInitialSharedFunction0416, Yh as currentAppInitialSharedMember0417, Yi as currentAppInitialSharedMember0418, Ym as currentAppInitialSharedMember0419, Yo as currentAppInitialSharedMember0421, Yr as workspaceWebsiteAssistantProjectlessFunction, Ys as currentAppInitialSharedMember0424 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { Yt as currentAppInitialSharedMember0425, Yu as currentAppInitialSharedMember0426, Z as currentAppInitialSharedMember0428, Za as currentAppInitialSharedMember0429, Zd as currentAppInitialSharedMember0431, Zf as currentAppInitialSharedMember0432, Zg as currentAppInitialSharedMember0433, Zi as currentAppInitialSharedMember0435, Zm as currentAppInitialSharedMember0436, Zo as currentAppInitialSharedMember0438, Zr as currentAppInitialSharedMember0439, Zs as currentAppInitialSharedMember0440, Zu as currentAppInitialSharedMember0442, Zv as currentAppInitialSharedMember0443 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { _ as currentAppInitialSharedMember0444, __ as currentAppInitialSharedMember0445, _d as currentAppInitialSharedMember0448, _f as currentAppInitialSharedMember0449, _h as currentAppInitialSharedFunction0450, _i as analyticsMember0451, _n as currentAppInitialSharedMember0454, _t as currentAppInitialSharedMember0458, _u as currentAppInitialSharedMember0459, _v as currentAppInitialSharedMember0460, _y as currentAppInitialSharedFunction0461, a as currentAppInitialSharedMember0462, a_ as currentAppInitialSharedMember0463, aa as currentAppInitialSharedMember0464 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ac as currentAppInitialSharedMember0465, ad as currentAppInitialSharedMember0466, af as currentAppInitialSharedMember0467, ag as currentAppInitialSharedSideFunction, ah as currentAppInitialSharedMember0469, ai as currentAppInitialSharedFunction0470, an as currentAppInitialSharedMember0473, ao as computerUseComputerAppDisplayFunction, ap as currentAppInitialSharedMember0475, ar as workspaceFunction0476, as as appgenAudienceFunction, at as currentAppInitialSharedMember0478, au as currentAppInitialSharedMember0479, av as currentAppInitialSharedMember0480 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ay as currentAppInitialSharedMember0481, b as currentAppInitialSharedMember0482, bf as currentAppInitialSharedMember0486, bi as currentAppInitialSharedMember0488, bm as currentAppInitialSharedMember0490, bn as currentAppInitialSharedMember0491, bp as currentAppInitialSharedMember0493, br as currentAppInitialSharedEntriesFunction, bs as currentAppInitialSharedMember0495, bt as currentAppInitialSharedMember0496, bu as currentAppInitialSharedMember0497, bv as currentAppInitialSharedMember0498, by as currentAppInitialSharedMember0499, c as currentAppInitialSharedMember0500 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { c_ as currentAppInitialSharedFunction0501, ca as currentAppInitialSharedMember0502, cc as currentAppInitialSharedMember0503, cd as currentAppInitialSharedMember0504, cf as currentAppInitialSharedMember0505, ci as currentAppInitialSharedMember0507, cp as currentAppInitialSharedMember0511, ct as currentAppInitialSharedMember0514, cu as currentAppInitialSharedMember0515, cy as statsigFunction0517, d as currentAppInitialSharedMember0518, d_ as currentAppInitialSharedFunction0519, da as currentAppInitialSharedMember0520, dc as schemaFunction0521 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { dd as currentAppInitialSharedMember0522, df as currentAppInitialSharedMember0523, dg as currentAppInitialSharedMember0524, dh as onboardingMember0525, dl as currentAppInitialSharedUnserializablePayloadAncestorsFunction, dn as currentAppInitialSharedMember0528, dp as currentAppInitialSharedMember0529, dr as formatUnserializablePayloadPreview, dt as currentAppInitialSharedMember0530, du as currentAppInitialSharedMember0531, dv as encodeBytesToBase64, dy as currentAppInitialSharedMember0532, ea as currentAppInitialSharedMember0534, ec as currentAppInitialSharedMember0535 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ed as currentAppInitialSharedMember0536, ef as currentAppInitialSharedMember0537, eg as currentAppInitialSharedMember0538, ei as currentAppInitialSharedMember0540, em as currentAppInitialSharedMember0542, eo as currentAppInitialSharedSleepFunction, ep as currentAppInitialSharedMember0545, es as currentAppInitialSharedMember0546, et as currentAppInitialSharedMember0547, eu as currentAppInitialSharedMember0548, ev as currentAppInitialSharedMember0549, ey as statsigFunction0550, f as currentAppInitialSharedMember0551, fa as classifyHomeEntrypoint } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { fd as parseNotificationDecisionLine, ff as currentAppInitialSharedMember0554, fh as currentAppInitialSharedMember0555, fi as currentAppInitialSharedFunction0556, fo as currentAppInitialSharedTitleFunction, fp as currentAppInitialSharedMember0560, ft as currentAppInitialSharedMember0563, fu as currentAppInitialSharedMember0564, fy as currentAppInitialSharedMember0566, g as currentAppInitialSharedMember0567, g_ as currentAppInitialSharedMember0568, ga as currentAppInitialSharedMember0569, gc as currentAppInitialSharedAbortedAbortFunction, gd as currentAppInitialSharedMember0571 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { gf as currentAppInitialSharedMember0572, gi as currentAppInitialSharedMember0575, gn as currentAppInitialSharedConnectedFunction, gp as currentAppInitialSharedMember0578, gt as currentAppInitialSharedMember0580, gu as currentAppInitialSharedMember0581, gv as normalizeLocalImageAttachment, h as currentAppInitialSharedMember0583, h_ as currentAppInitialSharedMember0584, ha as currentAppInitialSharedMember0585, hd as currentAppInitialSharedMember0587, hf as currentAppInitialSharedMember0588, hg as currentAppInitialSharedFunction0589, hh as currentAppInitialSharedMember0590 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { hi as currentAppInitialSharedInt64Function, hn as currentAppInitialSharedMember0593, hp as currentAppInitialSharedMember0595, ht as currentAppInitialSharedMember0598, hu as currentAppInitialSharedMember0599, hv as currentAppInitialSharedMember0600, i as currentAppInitialSharedMember0602, i_ as currentAppInitialSharedMember0603, ia as currentAppInitialSharedMember0604, id as currentAppInitialSharedMember0605, if as currentAppInitialSharedMember0606, ig as currentAppInitialSharedAuthorLoginTextFunction, ih as currentAppInitialSharedMember0608, in as currentAppInitialSharedMember0611 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { io as currentAppInitialSharedMember0612, ip as currentAppInitialSharedMember0613, is as currentAppInitialSharedMember0615, it as currentAppInitialSharedMember0616, iu as currentAppInitialSharedMember0617, iv as currentAppInitialSharedMember0618, iy as statsigFunction0619, j as currentAppInitialSharedMember0620, jd as currentAppInitialSharedMember0624, jf as currentAppInitialSharedMember0625, jg as currentAppInitialSharedFunction0626, ji as currentAppInitialSharedMember0627, jn as gitMember0630, jo as currentAppInitialSharedMember0631 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { jp as currentAppInitialSharedMember0632, jt as currentAppInitialSharedMember0635, ju as currentAppInitialSharedMember0636, jv as appActionMember0637, jy as currentAppInitialSharedFunction0638, k as currentAppInitialSharedMember0639, ka as currentAppInitialSharedMember0641, kd as currentAppInitialSharedMember0643, kf as currentAppInitialSharedMember0644, kn as currentAppInitialSharedMember0648, ko as currentAppInitialSharedMember0649, kp as currentAppInitialSharedMember0650, kr as currentAppInitialSharedFunction0651, kt as currentAppInitialSharedMember0653 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ku as currentAppInitialSharedMember0654, kv as appActionMember0655, ky as currentAppInitialSharedMember0656, l as currentAppInitialSharedMember0657, lc as currentAppInitialSharedMember0659, ld as currentAppInitialSharedMember0660, lf as currentAppInitialSharedMember0661, lg as currentAppInitialSharedMember0662, lh as currentAppInitialSharedTextFunctionVariant02, li as currentAppInitialSharedMember0664, ll as currentAppInitialSharedMember0665, lm as currentAppInitialSharedFunction0666, lp as currentAppInitialSharedMember0669, ls as currentAppInitialSharedMember0671 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { lt as currentAppInitialSharedMember0672, lu as currentAppInitialSharedMember0673, lv as currentAppInitialSharedMember0674, m as currentAppInitialSharedMember0676, m_ as currentAppInitialSharedMember0677, ma as currentAppInitialSharedMember0678, md as currentAppInitialSharedMember0680, mf as currentAppInitialSharedMember0681, mg as currentAppInitialSharedFunction0682, mn as currentAppInitialSharedMember0686, mp as currentAppInitialSharedMember0687, mt as currentAppInitialSharedMember0689, mu as currentAppInitialSharedMember0690, mv as currentAppInitialSharedMember0691 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { n as currentAppInitialSharedMember0693, n_ as currentAppInitialSharedFunction0694, na as currentAppInitialSharedMember0695, nd as currentAppInitialSharedMember0696, nf as currentAppInitialSharedMember0697, ng as currentAppInitialSharedSideFunctionVariant02, nh as onboardingMember0699, ni as currentAppInitialSharedLocalhostFunction, nl as currentAppInitialSharedFunction0701, no as currentAppInitialSharedMember0704, np as currentAppInitialSharedMember0705, nr as currentAppInitialSharedMember0706, ns as appgenMember0707, nt as currentAppInitialSharedMember0708 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { nu as currentAppInitialSharedMember0709, ny as currentAppInitialSharedMember0711, o as currentAppInitialSharedMember0712, oa as currentAppInitialSharedMember0714, oc as currentAppInitialSharedFunction0715, od as currentAppInitialSharedMember0716, of as currentAppInitialSharedMember0717, og as currentAppInitialSharedTextFunctionVariant03, oh as currentAppInitialSharedMember0719, oi as currentAppInitialSharedColumnFunction, ol as currentAppInitialSharedFunction0721, om as currentAppInitialSharedFunction0722, on as currentAppInitialSharedMember0723, op as currentAppInitialSharedMember0725 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ot as currentAppInitialSharedMember0727, ou as currentAppInitialSharedMember0728, oy as currentAppInitialSharedMember0730, p as currentAppInitialSharedMember0731, p_ as currentAppInitialSharedFunction0732, pc as workspaceConfigReadIncludeFunction, pd as currentAppInitialSharedMember0734, pf as currentAppInitialSharedMember0735, ph as currentAppInitialSharedFunction0736, pi as currentAppInitialSharedFunction0737, pn as currentAppInitialSharedMember0740, pp as currentAppInitialSharedMember0741, pr as computerUseComputerCaptureFunction, pt as currentAppInitialSharedMember0743 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { pu as currentAppInitialSharedMember0744, q as currentAppInitialSharedMember0747, q_ as getCodexDesktopOriginator, qa as currentAppInitialSharedMember0748, qd as currentAppInitialSharedMember0749, qf as currentAppInitialSharedMember0750, qg as currentAppInitialSharedFunction0751, ql as currentAppInitialSharedMember0753, qm as currentAppInitialSharedMember0754, qn as currentAppInitialSharedMember0755, qo as currentAppInitialSharedMember0756, qr as currentAppInitialSharedFunction0758, qt as currentAppInitialSharedMember0759, qu as currentAppInitialSharedMember0760 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { qy as currentAppInitialSharedMember0762, r as currentAppInitialSharedMember0763, r_ as currentAppInitialSharedFunction0764, rc as currentAppInitialSharedMember0766, rd as currentAppInitialSharedMember0767, rf as currentAppInitialSharedMember0768, rg as currentAppInitialSharedMember0769, rh as currentAppInitialSharedMember0770, ri as currentAppInitialSharedMember0771, rn as currentAppInitialSharedMember0774, ro as currentAppInitialSharedMember0775, rp as currentAppInitialSharedMember0776, rr as currentAppInitialSharedMember0777, rt as currentAppInitialSharedMember0778 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { ru as currentAppInitialSharedMember0779, rv as currentAppInitialSharedMember0780, ry as currentAppInitialSharedMember0781, s as currentAppInitialSharedMember0782, s_ as currentAppInitialSharedFunction0783, sa as currentAppInitialSharedMember0784, sd as currentAppInitialSharedMember0786, sf as currentAppInitialSharedMember0787, sg as currentAppInitialSharedFunction0788, sh as onboardingMember0789, si as markdownColumnFunction, sn as currentAppInitialSharedMember0792, sp as currentAppInitialSharedMember0793, st as currentAppInitialSharedMember0796 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { su as currentAppInitialSharedMember0797, sv as currentAppInitialSharedMember0798, sy as currentAppInitialSharedMember0799, t as currentAppInitialSharedMember0800, t_ as currentAppInitialSharedFunction0801, tc as currentAppInitialSharedMember0802, td as currentAppInitialSharedMember0803, tf as currentAppInitialSharedMember0804, tg as currentAppInitialSharedMember0805, th as normalizeWindowsPathSeparators, ti as currentAppInitialSharedMember0806, tl as currentAppInitialSharedSrcFunction, tm as currentAppInitialSharedMember0808, to as currentAppInitialSharedMember0810 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { tp as currentAppInitialSharedMember0811, tr as currentAppInitialSharedMember0812, tt as currentAppInitialSharedMember0813, tu as currentAppInitialSharedMember0814, tv as currentAppInitialSharedMember0815, u as currentAppInitialSharedMember0817, ua as currentAppInitialSharedMember0819, uc as currentAppInitialSharedMember0820, ud as currentAppInitialSharedMember0821, uf as currentAppInitialSharedMember0822, ug as currentAppInitialSharedMember0823, ui as currentAppInitialSharedFunction0824, um as currentAppInitialSharedMember0826, un as currentAppInitialSharedMember0827 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { uo as currentAppInitialSharedMember0828, up as currentAppInitialSharedMember0829, ut as currentAppInitialSharedMember0832, uu as currentAppInitialSharedMember0833, uv as currentAppInitialSharedMember0834, uy as currentAppInitialSharedMember0835, v as currentAppInitialSharedMember0836, vc as helperSuppressedDeclarationsObjectsFunction, vd as currentAppInitialSharedMember0838, vf as currentAppInitialSharedMember0839, vi as analyticsMember0842, vm as currentAppInitialSharedFunction0844, vo as currentAppInitialSharedMember0846, vp as currentAppInitialSharedMember0847 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { vr as markdownFunction0848, vt as currentAppInitialSharedFunction0850, vu as currentAppInitialSharedMember0851, vv as currentAppInitialSharedMember0852, vy as currentAppInitialSharedMember0853, w as currentAppInitialSharedMember0854, wa as currentAppInitialSharedMember0856, wc as currentAppInitialSharedMember0857, wd as currentAppInitialSharedMember0858, wf as currentAppInitialSharedMember0859, wg as currentAppInitialSharedMember0860, wi as analyticsMember0862, wl as currentAppInitialSharedMember0863, wm as currentAppInitialSharedMember0864 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { wn as currentAppInitialSharedMember0865, wp as currentAppInitialSharedMember0867, wr as currentAppInitialSharedMember0868, ws as currentAppInitialSharedMember0869, wt as currentAppInitialSharedMember0870, wu as currentAppInitialSharedMember0871, wv as currentAppInitialSharedMember0872, x as currentAppInitialSharedMember0874, x_ as currentAppInitialSharedMember0875, xc as currentAppInitialSharedMember0876, xd as currentAppInitialSharedMember0877, xf as currentAppInitialSharedMember0878, xh as currentAppInitialSharedMember0879, xn as currentAppInitialSharedMember0882 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { xo as currentAppInitialSharedMember0883, xp as currentAppInitialSharedMember0884, xs as currentAppInitialSharedMember0885, xt as currentAppInitialSharedMember0886, xu as currentAppInitialSharedMember0887, y as currentAppInitialSharedMember0890, yf as currentAppInitialSharedMember0894, yg as currentAppInitialSharedFunction0895, yh as currentAppInitialSharedWorkbookRangeDesignFunction, yi as analyticsMember0897, yp as currentAppInitialSharedMember0902, ys as currentAppInitialSharedMember0903, yt as currentAppInitialSharedMember0904, yu as currentAppInitialSharedMember0905 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { yv as flattenTextContentAttachments, yy as currentAppInitialSharedMember0906, z as currentAppInitialSharedMember0907, za as currentAppInitialSharedMember0909, zd as currentAppInitialSharedMember0910, zf as currentAppInitialSharedMember0911, zi as currentAppInitialSharedMember0913, zm as currentAppInitialSharedMember0915, zo as currentAppInitialSharedMember0917, zp as currentAppInitialSharedMember0918, zr as currentAppInitialSharedMember0919, zs as statsigMember0920, zt as currentAppInitialSharedMember0921, zu as currentAppInitialSharedMember0922 } from "../../vendor/remote-projects-app-shared-current-bundle";
// prettier-ignore
export { zv as appActionFunction0923, zy as currentAppInitialSharedMember0924 } from "../../vendor/remote-projects-app-shared-current-bundle";
