// Restored from ref/webview/assets/iconResolver-DrMXO_qJ.js

export const fileNameIconTokens = {
  ".babelrc": "babel",
  ".babelrc.json": "babel",
  ".bash_profile": "bash",
  ".bashrc": "bash",
  ".browserslistrc": "browserslist",
  ".dockerignore": "docker",
  ".eslintignore": "eslint",
  ".eslintrc": "eslint",
  ".eslintrc.cjs": "eslint",
  ".eslintrc.js": "eslint",
  ".eslintrc.json": "eslint",
  ".eslintrc.yaml": "eslint",
  ".eslintrc.yml": "eslint",
  ".gitattributes": "git",
  ".gitignore": "git",
  ".gitkeep": "git",
  ".gitmodules": "git",
  ".oxlintrc.json": "oxc",
  ".postcssrc": "postcss",
  ".postcssrc.json": "postcss",
  ".postcssrc.yaml": "postcss",
  ".postcssrc.yml": "postcss",
  ".prettierignore": "prettier",
  ".prettierrc": "prettier",
  ".prettierrc.cjs": "prettier",
  ".prettierrc.js": "prettier",
  ".prettierrc.json": "prettier",
  ".prettierrc.mjs": "prettier",
  ".prettierrc.toml": "prettier",
  ".prettierrc.yaml": "prettier",
  ".prettierrc.yml": "prettier",
  ".stylelintignore": "stylelint",
  ".stylelintrc": "stylelint",
  ".stylelintrc.cjs": "stylelint",
  ".stylelintrc.js": "stylelint",
  ".stylelintrc.json": "stylelint",
  ".stylelintrc.mjs": "stylelint",
  ".stylelintrc.yaml": "stylelint",
  ".stylelintrc.yml": "stylelint",
  ".terraform.lock.hcl": "terraform",
  ".zprofile": "bash",
  ".zshenv": "bash",
  ".zshrc": "bash",
  "babel.config.cjs": "babel",
  "babel.config.js": "babel",
  "babel.config.json": "babel",
  "babel.config.mjs": "babel",
  "biome.json": "biome",
  "biome.jsonc": "biome",
  "bootstrap.bundle.js": "bootstrap",
  "bootstrap.bundle.min.js": "bootstrap",
  "bootstrap.css": "bootstrap",
  "bootstrap.js": "bootstrap",
  "bootstrap.min.css": "bootstrap",
  "bootstrap.min.js": "bootstrap",
  "bun.lock": "bun",
  "bun.lockb": "bun",
  "bunfig.toml": "bun",
  "claude.md": "claude",
  "compose.yaml": "docker",
  "compose.yml": "docker",
  "docker-compose.override.yml": "docker",
  "docker-compose.yaml": "docker",
  "docker-compose.yml": "docker",
  dockerfile: "docker",
  "eslint.config.cjs": "eslint",
  "eslint.config.js": "eslint",
  "eslint.config.mjs": "eslint",
  "eslint.config.mts": "eslint",
  "eslint.config.ts": "eslint",
  gemfile: "ruby",
  "next.config.js": "nextjs",
  "next.config.mjs": "nextjs",
  "next.config.mts": "nextjs",
  "next.config.ts": "nextjs",
  "postcss.config.cjs": "postcss",
  "postcss.config.js": "postcss",
  "postcss.config.mjs": "postcss",
  "postcss.config.ts": "postcss",
  "prettier.config.cjs": "prettier",
  "prettier.config.js": "prettier",
  "prettier.config.mjs": "prettier",
  rakefile: "ruby",
  "readme.md": "markdown",
  "stylelint.config.cjs": "stylelint",
  "stylelint.config.js": "stylelint",
  "stylelint.config.mjs": "stylelint",
  "svgo.config.cjs": "svgo",
  "svgo.config.js": "svgo",
  "svgo.config.mjs": "svgo",
  "svgo.config.ts": "svgo",
  "tailwind.config.cjs": "tailwind",
  "tailwind.config.js": "tailwind",
  "tailwind.config.mjs": "tailwind",
  "tailwind.config.ts": "tailwind",
  "vite.config.js": "vite",
  "vite.config.mjs": "vite",
  "vite.config.mts": "vite",
  "vite.config.ts": "vite",
  "webpack.config.babel.js": "webpack",
  "webpack.config.cjs": "webpack",
  "webpack.config.js": "webpack",
  "webpack.config.mjs": "webpack",
  "webpack.config.ts": "webpack",
} as const;

export const fileExtensionIconTokens = {
  "7z": "zip",
  astro: "astro",
  AUTHORS: "text",
  avif: "image",
  bash: "bash",
  bmp: "image",
  bz2: "zip",
  c: "c",
  cc: "cpp",
  cfg: "text",
  CHANGELOG: "text",
  cjs: "javascript",
  "code-workspace": "vscode",
  conf: "text",
  CONTRIBUTORS: "text",
  cpp: "cpp",
  csh: "bash",
  css: "css",
  csv: "table",
  cts: "typescript",
  cxx: "cpp",
  db: "database",
  editorconfig: "text",
  env: "text",
  "env.development": "text",
  "env.local": "text",
  "env.production": "text",
  eot: "font",
  erb: "ruby",
  fish: "bash",
  gemspec: "ruby",
  gif: "image",
  go: "go",
  gql: "graphql",
  graphql: "graphql",
  gz: "zip",
  h: "c",
  hh: "cpp",
  hpp: "cpp",
  htm: "html",
  html: "html",
  hxx: "cpp",
  icns: "image",
  ico: "image",
  ini: "text",
  inl: "cpp",
  jar: "zip",
  jpeg: "image",
  jpg: "image",
  js: "javascript",
  json: "json",
  json5: "json",
  jsonc: "json",
  jsonl: "json",
  jsx: "javascript",
  ksh: "bash",
  less: "css",
  LICENSE: "text",
  log: "text",
  markdown: "markdown",
  mcp: "mcp",
  md: "markdown",
  mdx: "markdown",
  "mdx.tsx": "markdown",
  mjs: "javascript",
  mm: "cpp",
  mts: "typescript",
  ods: "table",
  otf: "font",
  png: "image",
  postcss: "css",
  py: "python",
  pyi: "python",
  pyw: "python",
  pyx: "python",
  rake: "ruby",
  rar: "zip",
  rb: "ruby",
  rs: "rust",
  rst: "text",
  rtf: "text",
  sass: "css",
  scss: "css",
  sh: "bash",
  sql: "database",
  sqlite: "database",
  sqlite3: "database",
  styl: "css",
  svelte: "svelte",
  svg: "svg",
  swift: "swift",
  tar: "zip",
  tf: "terraform",
  tfstate: "terraform",
  tfvars: "terraform",
  tgz: "zip",
  tif: "image",
  tiff: "image",
  ts: "typescript",
  tsv: "table",
  tsx: "typescript",
  ttf: "font",
  txt: "text",
  vue: "vue",
  war: "zip",
  wasm: "wasm",
  wast: "wasm",
  wat: "wasm",
  webp: "image",
  woff: "font",
  woff2: "font",
  xhtml: "html",
  xls: "table",
  xlsx: "table",
  xz: "zip",
  yaml: "yml",
  yml: "yml",
  zig: "zig",
  zip: "zip",
  zsh: "bash",
} as const;

export const completeOnlyExtensionIconTokens = {
  jsx: "react",
  sass: "sass",
  scss: "sass",
  tsx: "react",
} as const;

export const standardFileIconTokens = new Set([
  "bash",
  "c",
  "cpp",
  "css",
  "database",
  "default",
  "font",
  "git",
  "go",
  "html",
  "image",
  "javascript",
  "json",
  "markdown",
  "mcp",
  "python",
  "ruby",
  "rust",
  "swift",
  "table",
  "text",
  "typescript",
  "zip",
]);

export const spriteSetsWithCompleteBuiltins = new Set(["complete"]);
