// Restored from ref/webview/assets/data-controls-CwyuAPUl.js
// Semantic implementation module for data controls settings runtime wiring.

import {
  once as rolldownRuntimeN,
  toEsModule as rolldownRuntimeS,
} from "../../runtime/commonjs-interop";
import {
  currentAppInitialSharedCompatSlotDollarLowerS as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  currentAppInitialSharedCompatSlotUpperD as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  currentAppInitialSharedCompatSlotUpperE as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  currentAppInitialSharedCompatSlotUpperELowerI as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEi,
  currentAppInitialSharedCompatSlotUpperKLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  currentAppInitialSharedCompatSlotUpperO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  currentAppInitialSharedCompatSlotUpperVLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  currentAppInitialSharedCompatSlotUnderscoreLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerA as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wA,
  currentAppInitialSharedCompatSlotLowerALowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wAc,
  currentAppInitialSharedCompatSlotLowerC as _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerCLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  currentAppInitialSharedCompatSlotLowerD as _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  currentAppInitialSharedCompatSlotLowerELowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEc,
  currentAppInitialSharedCompatSlotLowerGLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  currentAppInitialSharedCompatSlotLowerH as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH,
  currentAppInitialSharedCompatSlotLowerI as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  currentAppInitialSharedCompatSlotLowerLLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  currentAppInitialSharedCompatSlotLowerM as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wM,
  currentAppInitialSharedCompatSlotLowerP as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wP,
  currentAppInitialSharedCompatSlotLowerQLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  currentAppInitialSharedCompatSlotLowerTLowerA as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTa,
  currentAppInitialSharedCompatSlotLowerTLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
} from "../../runtime/current-app-initial/current-app-initial-shared-runtime";
import {
  worktreeNewThreadOrchestratorCompatSlotDollarLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsR,
  worktreeNewThreadOrchestratorCompatSlotUpperFLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsFr,
  worktreeNewThreadOrchestratorCompatSlotUpperILowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsIr,
  worktreeNewThreadOrchestratorCompatSlotLowerELowerI as AppInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsEi,
} from "../../runtime/current-app-initial/worktree-new-thread-orchestrator-runtime";
import {
  worktreeNewThreadQueryCompatSlotUpperCLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa,
  worktreeNewThreadQueryCompatSlotUpperDLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo,
  worktreeNewThreadQueryCompatSlotUpperELowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  worktreeNewThreadQueryCompatSlotUpperJLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwJa,
  worktreeNewThreadQueryCompatSlotUpperJLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwJr,
  worktreeNewThreadQueryCompatSlotUpperOLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  worktreeNewThreadQueryCompatSlotUpperSLowerF as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSf,
  worktreeNewThreadQueryCompatSlotUpperTLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  worktreeNewThreadQueryCompatSlotUpperULowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUr,
  worktreeNewThreadQueryCompatSlotUpperYLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  worktreeNewThreadQueryCompatSlotUpperYLowerR as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYr,
  worktreeNewThreadQueryCompatSlotUnderscoreLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwA,
  worktreeNewThreadQueryCompatSlotLowerBLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBa,
  worktreeNewThreadQueryCompatSlotLowerELowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  worktreeNewThreadQueryCompatSlotLowerGLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  worktreeNewThreadQueryCompatSlotLowerKLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  worktreeNewThreadQueryCompatSlotLowerLLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLo,
  worktreeNewThreadQueryCompatSlotLowerMLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  worktreeNewThreadQueryCompatSlotLowerNLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  worktreeNewThreadQueryCompatSlotLowerOLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  worktreeNewThreadQueryCompatSlotLowerTLowerI as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTi,
  worktreeNewThreadQueryCompatSlotLowerULowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo,
  worktreeNewThreadQueryCompatSlotLowerVLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwVa,
  worktreeNewThreadQueryCompatSlotLowerWLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwWo,
  worktreeNewThreadQueryCompatSlotLowerXLowerF as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwXf,
  worktreeNewThreadQueryCompatSlotLowerXLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwXp,
  worktreeNewThreadQueryCompatSlotLowerYLowerA as _appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  worktreeNewThreadQueryCompatSlotLowerYLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYp,
} from "../../runtime/current-app-initial/worktree-new-thread-query-runtime";
import {
  parseWorkspaceRootPathList as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFa,
  createScopedSignalAtom as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  intlFormatDateTimeRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  createWhamApiRequestClient as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dJ,
  currentAppInitialSharedMember0178 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dK,
  currentAppInitialSharedMember0195 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dLc,
  appServerDisconnectedAppServerSignal as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dN,
  currentAppInitialSharedMember0240 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNv,
  currentAppInitialSharedDisplayRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  unarchivedConversationLoadErrorSchema as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRc,
  currentAppInitialSharedRuntime0307 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRv,
  currentAppInitialSharedFunction0375 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  currentAppInitialSharedFunction0450 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dH,
  schemaMethodFoundVariantSchema as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBl,
  currentAppInitialSharedMember0542 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dEm,
  currentAppInitialSharedRuntime0574 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dGh,
  currentAppInitialSharedRuntime0840 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg,
  openAiNativeAppDefinition as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  currentAppInitialSharedFunction0895 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYg,
  schemaSchema0898 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYl,
  currentAppInitialSharedMember0924 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
} from "../../runtime/current-app-initial/remote-projects-app-shared-runtime";
import {
  pullRequestNewThreadCompatSlotLowerDLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn,
  pullRequestNewThreadCompatSlotLowerGLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkGn,
} from "../../runtime/current-app-initial/pull-request-new-thread-runtime";
import {
  appMainCurrentCompatSlotUpperALowerU as AppInitialAppMainOnboardingPageAu,
  appMainCurrentCompatSlotUpperFLowerN as appInitialAppMainOnboardingPageFn,
  appMainCurrentCompatSlotUpperILowerN as AppInitialAppMainOnboardingPageIn,
  appMainCurrentCompatSlotUpperMLowerU as appInitialAppMainOnboardingPageMu,
  appMainCurrentCompatSlotUpperNLowerU as AppInitialAppMainOnboardingPageNu,
  appMainCurrentCompatSlotUpperPLowerU as AppInitialAppMainOnboardingPagePu,
  appMainCurrentCompatSlotUpperXLowerT as appInitialAppMainOnboardingPageXt,
  appMainCurrentCompatSlotUpperXLowerU as appInitialAppMainOnboardingPageXu,
  appMainCurrentCompatSlotUpperZLowerT as appInitialAppMainOnboardingPageZt,
  AppShellOverlayOutlet as appInitialAppMainOnboardingPageZu,
  appMainCurrentCompatSlotLowerALowerD as appInitialAppMainOnboardingPageAd,
  appMainCurrentCompatSlotLowerALowerM as appInitialAppMainOnboardingPageAm,
  appMainCurrentCompatSlotLowerILowerD as appInitialAppMainOnboardingPageId,
  appMainCurrentCompatSlotLowerOLowerM as appInitialAppMainOnboardingPageOm,
} from "../../vendor/app-main-current-runtime/index";
import {
  appgenLibraryHotDjo67r4nCompatSlotDollarLowerN as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nN,
  appgenLibraryHotDjo67r4nCompatSlotUpperH as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appgenLibraryHotDjo67r4nCompatSlotUpperQLowerN as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nQn,
  appgenLibraryHotDjo67r4nCompatSlotUpperR as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appgenLibraryHotDjo67r4nCompatSlotUpperV as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
} from "../../runtime/current-app-initial/appgen-library-hot-djo67r4n-runtime";
import {
  generalAppearanceCurrentCompatSlotUpperJ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  generalAppearanceCurrentCompatSlotLowerD as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  generalAppearanceCurrentCompatSlotLowerF as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  generalAppearanceCurrentCompatSlotLowerQ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
} from "../../runtime/current-app-initial/general-appearance-current-runtime";
import {
  initSettingsContentLayoutChunk as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  SettingsContentLayout as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
} from "../../runtime/current-app-initial/settings-section-layout-runtime";
import {
  initInfiniteScrollPaginationSpinnerChunk as infiniteScrollPaginationSpinnerN,
  InfiniteScrollPaginationSpinner as infiniteScrollPaginationSpinnerT,
} from "../../ui/infinite-scroll-pagination-spinner";
import {
  initFilterIconChunk as filterN,
  FilterIcon as filterT,
} from "../../icons/filter-icon";
import {
  initControlGroupChunk as controlGroupN,
  ControlGroup as controlGroupT,
} from "../../utils/control-group";
var archivedChatActionMessages,
  initArchivedChatActionMessages = rolldownRuntimeN(() => {
    (appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      (archivedChatActionMessages =
        appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy(
          {
            delete: {
              id: `settings.dataControls.archivedChats.delete`,
              defaultMessage: `Delete`,
              description: `Button label to permanently delete an archived chat`,
            },
            deleteAll: {
              id: `settings.dataControls.archivedChats.deleteAll`,
              defaultMessage: `Delete all`,
              description: `Button label to permanently delete all archived local chats`,
            },
            deleteAllError: {
              id: `settings.dataControls.archivedChats.deleteAllError`,
              defaultMessage: `Failed to delete archived chats`,
              description: `Error message when deleting all archived chats fails`,
            },
            deleteError: {
              id: `settings.dataControls.archivedChats.deleteError`,
              defaultMessage: `Failed to delete archived chat`,
              description: `Error message when deleting an archived chat fails`,
            },
            deleteUnsupported: {
              id: `settings.dataControls.archivedChats.deleteUnsupported`,
              defaultMessage: `This host doesn’t support deleting chats. Update Codex on the host and try again.`,
              description: `Error message when a Codex host does not support deleting archived chats`,
            },
            deleteSuccessPlain: {
              id: `settings.dataControls.archivedChats.deleteSuccessPlain`,
              defaultMessage: `Deleted archived chat`,
              description: `Success toast after deleting an archived chat`,
            },
            deleting: {
              id: `settings.dataControls.archivedChats.deleting`,
              defaultMessage: `Deleting archived chat…`,
              description: `Toast shown while deleting an archived chat`,
            },
            deletingAll: {
              id: `settings.dataControls.archivedChats.deletingAll`,
              defaultMessage: `Deleting archived chats…`,
              description: `Toast shown while deleting all archived chats`,
            },
            unarchiveError: {
              id: `settings.dataControls.archivedChats.unarchiveError`,
              defaultMessage: `Failed to unarchive chat`,
              description: `Error message when unarchiving a chat`,
            },
            openError: {
              id: `settings.dataControls.archivedChats.openError`,
              defaultMessage: `Unarchived chat, but failed to open it`,
              description: `Error message when an archived chat was unarchived but could not be opened`,
            },
            unarchiveSuccessPlain: {
              id: `settings.dataControls.archivedChats.unarchiveSuccessPlain`,
              defaultMessage: `Unarchived chat`,
              description: `Success toast after unarchiving a chat`,
            },
            viewNow: {
              id: `settings.dataControls.archivedChats.viewNow`,
              defaultMessage: `View now`,
              description: `Action label to open an unarchived chat from the success toast`,
            },
            unarchive: {
              id: `settings.dataControls.archivedChats.unarchive`,
              defaultMessage: `Unarchive`,
              description: `Button label to unarchive a chat`,
            },
          },
        )));
  });
var automationsArchiveGroupId,
  projectlessArchiveGroupId,
  initArchivedChatGroupingRuntime = rolldownRuntimeN(() => {
    (appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSf(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dGh(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nN(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRv(),
      (automationsArchiveGroupId = `special:automations`),
      (projectlessArchiveGroupId = `special:none`));
  });
var archivedCloudTaskRuntimeInit,
  archivedCloudTaskElementFactory,
  initArchivedCloudTaskRowRuntime = rolldownRuntimeN(() => {
    ((archivedCloudTaskRuntimeInit =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS(),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa(),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm(),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp(),
      appInitialAppMainOnboardingPageZt(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dGh(),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dJ(),
      initArchivedChatActionMessages(),
      (archivedCloudTaskElementFactory =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()));
  });
var archivedCloudTasksRuntimeInit,
  initArchivedCloudTasksQueryRuntime = rolldownRuntimeN(() => {
    ((archivedCloudTasksRuntimeInit =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS(),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dJ(),
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wP());
  });
var dataControlsRuntimeInit,
  dataControlsReactRuntime,
  dataControlsElementFactory,
  archivedChatFilterMessages,
  allArchivedProjectsFilter,
  automationInboxFetchLimit;
rolldownRuntimeN(() => {
  ((dataControlsRuntimeInit =
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO(),
    (dataControlsReactRuntime = rolldownRuntimeS(
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
      1,
    )),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dN(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRc(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYl(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo(),
    infiniteScrollPaginationSpinnerN(),
    appInitialAppMainOnboardingPageZu(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwXp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsIr(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp(),
    appInitialAppMainOnboardingPageOm(),
    filterN(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo(),
    appInitialAppMainOnboardingPageAd(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dGh(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn(),
    controlGroupN(),
    appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF(),
    AppInitialAppMainOnboardingPageAu(),
    AppInitialAppMainOnboardingPagePu(),
    AppInitialAppMainOnboardingPageIn(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUr(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nN(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRv(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsR(),
    _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
    initArchivedChatActionMessages(),
    initArchivedChatGroupingRuntime(),
    initArchivedCloudTaskRowRuntime(),
    initArchivedCloudTasksQueryRuntime(),
    (dataControlsElementFactory =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()),
    (archivedChatFilterMessages =
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy(
        {
          searchArchivedChats: {
            id: `settings.dataControls.archivedChats.search.placeholder`,
            defaultMessage: `Search archived chats`,
            description: `Placeholder for the archived chats search input`,
          },
          filterArchivedChats: {
            id: `settings.dataControls.archivedChats.filter.ariaLabel`,
            defaultMessage: `Filter archived chats`,
            description: `Accessible label for the archived chats filter dropdown`,
          },
          groupArchivedChats: {
            id: `settings.dataControls.archivedChats.group.ariaLabel`,
            defaultMessage: `Group archived chats`,
            description: `Accessible label for the archived chats grouping dropdown`,
          },
          filterArchivedChatsByProject: {
            id: `settings.dataControls.archivedChats.projectFilter.ariaLabel`,
            defaultMessage: `Filter archived chats by project`,
            description: `Accessible label for the archived chats project dropdown`,
          },
          allProjects: {
            id: `settings.dataControls.archivedChats.projectFilter.allProjects`,
            defaultMessage: `All projects`,
            description: `Project filter option showing archived chats from all projects`,
          },
          chats: {
            id: `settings.dataControls.archivedChats.projectFilter.chats`,
            defaultMessage: `Chats`,
            description: `Project filter option showing projectless archived chats`,
          },
          automations: {
            id: `settings.dataControls.archivedChats.projectFilter.automations`,
            defaultMessage: `Scheduled tasks`,
            description: `Project filter option showing archived scheduled task chats`,
          },
          type: {
            id: `settings.dataControls.archivedChats.filter.section.type`,
            defaultMessage: `Type`,
            description: `Section label for archived chat type filter options`,
          },
          sortBy: {
            id: `settings.dataControls.archivedChats.filter.section.sort`,
            defaultMessage: `Sort by`,
            description: `Section label for archived chat sort options`,
          },
          allChats: {
            id: `settings.dataControls.archivedChats.filter.all`,
            defaultMessage: `All chats`,
            description: `Filter option showing every archived chat`,
          },
          local: {
            id: `settings.dataControls.archivedChats.filter.local`,
            defaultMessage: `Local`,
            description: `Filter option showing local archived chats`,
          },
          cloud: {
            id: `settings.dataControls.archivedChats.filter.cloud`,
            defaultMessage: `Cloud`,
            description: `Filter option showing cloud archived chats`,
          },
          project: {
            id: `settings.dataControls.archivedChats.group.project`,
            defaultMessage: `Project`,
            description: `Grouping option that groups archived chats by project`,
          },
          none: {
            id: `settings.dataControls.archivedChats.group.none`,
            defaultMessage: `None`,
            description: `Grouping option that shows archived chats in one list`,
          },
          updated: {
            id: `settings.dataControls.archivedChats.sort.updated`,
            defaultMessage: `Updated`,
            description: `Sort option for archived chats by last updated time`,
          },
          created: {
            id: `settings.dataControls.archivedChats.sort.created`,
            defaultMessage: `Created`,
            description: `Sort option for archived chats by creation time`,
          },
          alphabetical: {
            id: `settings.dataControls.archivedChats.sort.alphabetical`,
            defaultMessage: `Alphabetical`,
            description: `Sort option for archived chats by title`,
          },
          deleteProjectChats: {
            id: `settings.dataControls.archivedChats.deleteProjectChats`,
            defaultMessage: `Delete all in project`,
            description: `Menu item label for deleting local archived chats in a project`,
          },
        },
      )),
    (allArchivedProjectsFilter = {
      kind: `all`,
    }),
    (automationInboxFetchLimit = 1e5));
})();
export default {
  AppInitialAppMainOnboardingPageAu,
  AppInitialAppMainOnboardingPageIn,
  AppInitialAppMainOnboardingPageNu,
  AppInitialAppMainOnboardingPagePu,
  AppInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsEi,
  _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  _appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  allArchivedProjectsFilter,
  appInitialAppMainOnboardingPageAd,
  appInitialAppMainOnboardingPageAm,
  appInitialAppMainOnboardingPageFn,
  appInitialAppMainOnboardingPageId,
  appInitialAppMainOnboardingPageMu,
  appInitialAppMainOnboardingPageOm,
  appInitialAppMainOnboardingPageXt,
  appInitialAppMainOnboardingPageXu,
  appInitialAppMainOnboardingPageZt,
  appInitialAppMainOnboardingPageZu,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wA,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wAc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wEi,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wH,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wM,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wP,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTa,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nN,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nQn,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dBl,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dEm,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dGh,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dH,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dJ,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dK,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dLc,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dN,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dNv,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRc,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRv,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVg,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYg,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dYl,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsFr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsIr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKg2pu5rsR,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwA,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwJa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwJr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwLo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwSf,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTi,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwUr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwVa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwWo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwXf,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwXp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYr,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkDn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkGn,
  archivedChatActionMessages,
  archivedChatFilterMessages,
  archivedCloudTaskElementFactory,
  archivedCloudTaskRuntimeInit,
  archivedCloudTasksRuntimeInit,
  automationInboxFetchLimit,
  automationsArchiveGroupId,
  controlGroupN,
  controlGroupT,
  dataControlsElementFactory,
  dataControlsReactRuntime,
  dataControlsRuntimeInit,
  filterN,
  filterT,
  infiniteScrollPaginationSpinnerN,
  infiniteScrollPaginationSpinnerT,
  initArchivedChatActionMessages,
  initArchivedChatGroupingRuntime,
  initArchivedCloudTaskRowRuntime,
  initArchivedCloudTasksQueryRuntime,
  projectlessArchiveGroupId,
  rolldownRuntimeN,
  rolldownRuntimeS,
};
