// Restored from ref/webview/assets/local-environments-utils-CkypnJBW.js
// TOML serialization helpers for local environment config files.

import { LOCAL_ENVIRONMENT_PLATFORMS } from "./defaults";
import type {
  LocalEnvironmentAction,
  LocalEnvironmentConfigForSerialization,
  LocalEnvironmentPlatform,
  PlatformScripts,
} from "./types";

export function normalizePlatformScripts(
  platformScripts?: Partial<
    Record<
      LocalEnvironmentPlatform,
      | {
          script?: string;
        }
      | undefined
    >
  >,
): Record<LocalEnvironmentPlatform, string> {
  return {
    darwin: platformScripts?.darwin?.script ?? "",
    linux: platformScripts?.linux?.script ?? "",
    win32: platformScripts?.win32?.script ?? "",
  };
}

export function serializeLocalEnvironmentConfig({
  version,
  name,
  setupScript,
  setupPlatformScripts,
  cleanupScript,
  cleanupPlatformScripts,
  actions,
}: LocalEnvironmentConfigForSerialization): string {
  const sanitizedActions = sanitizeLocalEnvironmentActions(actions);
  const lines: string[] = [
    "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY",
    `version = ${version}`,
    `name = ${formatTomlString(name)}`,
  ];
  const trimmedCleanupScript = cleanupScript.trim();
  appendScriptSection(lines, "setup", setupScript, setupPlatformScripts);
  appendScriptSection(
    lines,
    "cleanup",
    trimmedCleanupScript,
    cleanupPlatformScripts,
  );
  if (sanitizedActions.length > 0) {
    lines.push("");
  }
  for (const action of sanitizedActions) {
    lines.push("[[actions]]");
    lines.push(`name = ${formatTomlString(action.name)}`);
    if (action.icon) {
      lines.push(`icon = ${formatTomlString(action.icon)}`);
    }
    lines.push(`command = ${formatTomlString(action.command)}`);
    if (action.platform) {
      lines.push(`platform = ${formatTomlString(action.platform)}`);
    }
    lines.push("");
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function sanitizeLocalEnvironmentActions(actions: LocalEnvironmentAction[]) {
  const sanitizedActions: LocalEnvironmentAction[] = [];
  for (const action of actions) {
    const name = action.name.trim();
    const command = action.command.trim();
    if (name.length === 0 || command.length === 0) {
      continue;
    }
    sanitizedActions.push({
      ...action,
      name,
      command,
    });
  }
  return sanitizedActions;
}

function appendScriptSection(
  lines: string[],
  sectionName: "setup" | "cleanup",
  script: string,
  platformScripts: PlatformScripts,
) {
  const nonEmptyPlatformScripts = getNonEmptyPlatformScripts(platformScripts);
  if (
    sectionName === "setup" ||
    script.length > 0 ||
    nonEmptyPlatformScripts.length > 0
  ) {
    lines.push("");
    lines.push(`[${sectionName}]`);
    lines.push(`script = ${formatTomlString(script)}`);
  }
  if (nonEmptyPlatformScripts.length === 0) {
    return;
  }
  lines.push("");
  for (const [index, platformScript] of nonEmptyPlatformScripts.entries()) {
    lines.push(`[${sectionName}.${platformScript.platform}]`);
    lines.push(`script = ${formatTomlString(platformScript.script)}`);
    if (index < nonEmptyPlatformScripts.length - 1) {
      lines.push("");
    }
  }
}

function getNonEmptyPlatformScripts(platformScripts: PlatformScripts) {
  const nonEmptyPlatformScripts: Array<{
    platform: LocalEnvironmentPlatform;
    script: string;
  }> = [];
  for (const platform of LOCAL_ENVIRONMENT_PLATFORMS) {
    const script = platformScripts[platform];
    if (!script || script.length === 0) {
      continue;
    }
    nonEmptyPlatformScripts.push({
      platform,
      script,
    });
  }
  return nonEmptyPlatformScripts;
}

function formatTomlString(value: string): string {
  const normalizedValue = value.replace(/\r\n/g, "\n");
  if (!normalizedValue.includes("\n")) {
    return JSON.stringify(normalizedValue);
  }
  if (normalizedValue.includes("'''")) {
    return `"""\n${normalizedValue.replace(/\\/g, "\\\\").replace(/"""/g, '\\"""')}\n"""`;
  }
  return `'''\n${normalizedValue}\n'''`;
}
