// Restored from ref/webview/assets/computer-use-settings-BIYkni3c.js
// Semantic implementation module for computer use settings runtime wiring.

import {
  once as rolldownRuntimeN,
  toEsModule as rolldownRuntimeS,
} from "../../runtime/commonjs-interop";
import {
  currentAppInitialSharedCompatSlotDollarLowerS as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  currentAppInitialSharedCompatSlotUpperD as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  currentAppInitialSharedCompatSlotUpperE as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  currentAppInitialSharedCompatSlotUpperGLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGo,
  currentAppInitialSharedCompatSlotUpperKLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  currentAppInitialSharedCompatSlotUpperLLowerI as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLi,
  currentAppInitialSharedCompatSlotUpperO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  currentAppInitialSharedCompatSlotUpperVLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  currentAppInitialSharedCompatSlotUnderscoreLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerA as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wA,
  currentAppInitialSharedCompatSlotLowerC as _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  currentAppInitialSharedCompatSlotLowerCLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  currentAppInitialSharedCompatSlotLowerGLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  currentAppInitialSharedCompatSlotLowerI as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  currentAppInitialSharedCompatSlotLowerLLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  currentAppInitialSharedCompatSlotLowerQLowerO as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  currentAppInitialSharedCompatSlotLowerTLowerC as appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
} from "../../runtime/current-app-initial/current-app-initial-shared-runtime";
import {
  worktreeNewThreadQueryCompatSlotDollarLowerU as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwU,
  worktreeNewThreadQueryCompatSlotUpperALowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn,
  worktreeNewThreadQueryCompatSlotUpperCLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa,
  worktreeNewThreadQueryCompatSlotUpperDLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDm,
  worktreeNewThreadQueryCompatSlotUpperDLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo,
  worktreeNewThreadQueryCompatSlotUpperDLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDp,
  worktreeNewThreadQueryCompatSlotUpperELowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  worktreeNewThreadQueryCompatSlotUpperELowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEp,
  worktreeNewThreadQueryCompatSlotUpperKLowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKc,
  worktreeNewThreadQueryCompatSlotUpperNLowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNc,
  worktreeNewThreadQueryCompatSlotUpperOLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOm,
  worktreeNewThreadQueryCompatSlotUpperOLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  worktreeNewThreadQueryCompatSlotUpperTLowerM as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  worktreeNewThreadQueryCompatSlotUnderscoreLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwA,
  worktreeNewThreadQueryCompatSlotLowerBLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBa,
  worktreeNewThreadQueryCompatSlotLowerBLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBs,
  worktreeNewThreadQueryCompatSlotLowerELowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEc,
  worktreeNewThreadQueryCompatSlotLowerELowerD as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEd,
  worktreeNewThreadQueryCompatSlotLowerELowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEl,
  worktreeNewThreadQueryCompatSlotLowerELowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  worktreeNewThreadQueryCompatSlotLowerGLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  worktreeNewThreadQueryCompatSlotLowerHLowerH as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwHh,
  worktreeNewThreadQueryCompatSlotLowerILowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIc,
  worktreeNewThreadQueryCompatSlotLowerILowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIs,
  worktreeNewThreadQueryCompatSlotLowerKLowerN as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKn,
  worktreeNewThreadQueryCompatSlotLowerKLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  worktreeNewThreadQueryCompatSlotLowerMLowerH as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMh,
  worktreeNewThreadQueryCompatSlotLowerMLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  worktreeNewThreadQueryCompatSlotLowerNLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNl,
  worktreeNewThreadQueryCompatSlotLowerNLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  worktreeNewThreadQueryCompatSlotLowerNLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs,
  worktreeNewThreadQueryCompatSlotLowerOLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  worktreeNewThreadQueryCompatSlotLowerQLowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwQc,
  worktreeNewThreadQueryCompatSlotLowerRLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwRl,
  worktreeNewThreadQueryCompatSlotLowerTLowerL as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTl,
  worktreeNewThreadQueryCompatSlotLowerVLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwVa,
  worktreeNewThreadQueryCompatSlotLowerWLowerO as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwWo,
  worktreeNewThreadQueryCompatSlotLowerYLowerA as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  worktreeNewThreadQueryCompatSlotLowerYLowerS as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYs,
  worktreeNewThreadQueryCompatSlotLowerZLowerC as appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwZc,
} from "../../runtime/current-app-initial/worktree-new-thread-query-runtime";
import {
  currentAppInitialSharedMember0011 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dP,
  currentAppInitialSharedMember0084 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dEa,
  parseWorkspaceRootPathList as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFa,
  createScopedSignalAtom as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  intlFormatDateTimeRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  currentAppInitialSharedMember0262 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dPa,
  currentAppInitialSharedDisplayRuntime as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  currentAppInitialSharedFunction0375 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  currentAppInitialSharedMember0781 as AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRy,
  currentAppInitialSharedRuntime0816 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy,
  openAiNativeAppDefinition as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  currentAppInitialSharedMember0924 as appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
} from "../../runtime/current-app-initial/remote-projects-app-shared-runtime";
import {
  pullRequestNewThreadCompatSlotLowerF as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkF,
  pullRequestNewThreadCompatSlotLowerP as appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkP,
} from "../../runtime/current-app-initial/pull-request-new-thread-runtime";
import {
  appMainCurrentCompatSlotUpperALowerU as AppInitialAppMainOnboardingPageAu,
  appMainCurrentCompatSlotUpperFLowerN as appInitialAppMainOnboardingPageFn,
  appMainCurrentCompatSlotUpperILowerN as AppInitialAppMainOnboardingPageIn,
  appMainCurrentCompatSlotUpperKLowerU as appInitialAppMainOnboardingPageKu,
  appMainCurrentCompatSlotUpperMLowerU as appInitialAppMainOnboardingPageMu,
  appMainCurrentCompatSlotUpperRLowerU as AppInitialAppMainOnboardingPageRu,
  initCodexLinksChunk as appInitialAppMainOnboardingPageSc,
  appMainCurrentCompatSlotLowerALowerD as appInitialAppMainOnboardingPageAd,
  appMainCurrentCompatSlotLowerGLowerC as appInitialAppMainOnboardingPageGc,
  appMainCurrentCompatSlotLowerILowerD as appInitialAppMainOnboardingPageId,
  appMainCurrentCompatSlotLowerZLowerU as appInitialAppMainOnboardingPageZu,
} from "../../vendor/app-main-current-runtime/index";
import {
  appgenLibraryHotDjo67r4nCompatSlotUpperFLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nFt,
  appgenLibraryHotDjo67r4nCompatSlotUpperH as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appgenLibraryHotDjo67r4nCompatSlotUpperILowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nIt,
  appgenLibraryHotDjo67r4nCompatSlotUpperLLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nLt,
  appgenLibraryHotDjo67r4nCompatSlotUpperR as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appgenLibraryHotDjo67r4nCompatSlotUpperRLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nRt,
  appgenLibraryHotDjo67r4nCompatSlotUpperV as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
  appgenLibraryHotDjo67r4nCompatSlotUpperXLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nXt,
  appgenLibraryHotDjo67r4nCompatSlotUpperYLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nYt,
  appgenLibraryHotDjo67r4nCompatSlotUnderscoreLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nT,
  appgenLibraryHotDjo67r4nCompatSlotLowerFLowerT as _appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nFt,
  appgenLibraryHotDjo67r4nCompatSlotLowerGLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nGt,
  appgenLibraryHotDjo67r4nCompatSlotLowerHLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nHt,
  appgenLibraryHotDjo67r4nCompatSlotLowerMLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nMt,
  appgenLibraryHotDjo67r4nCompatSlotLowerPLowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nPt,
  appgenLibraryHotDjo67r4nCompatSlotLowerULowerT as appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nUt,
} from "../../runtime/current-app-initial/appgen-library-hot-djo67r4n-runtime";
import {
  initPrimaryRuntimeOfficePluginConstantsChunk as appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btD,
  isSpreadsheetPlugin as appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btO,
  APPGEN_SETTINGS_PUBLICATION_GATE_ID as appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btT,
  isPresentationPlugin as appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btK,
} from "../../runtime/current-app-initial/appgen-settings-publication-runtime";
import {
  generalAppearanceCurrentCompatSlotUpperJ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  generalAppearanceCurrentCompatSlotLowerD as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  generalAppearanceCurrentCompatSlotLowerF as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  generalAppearanceCurrentCompatSlotLowerQ as appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
} from "../../runtime/current-app-initial/general-appearance-current-runtime";
import {
  initSettingsContentLayoutChunk as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  SettingsContentLayout as appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
} from "../../runtime/current-app-initial/settings-section-layout-runtime";
import {
  useHomeDirectory as useHomeDirectoryN,
  initUseHomeDirectoryChunk as useHomeDirectoryT,
} from "../../utils/use-home-directory";
import {
  useAppsAvailability as appsAvailabilityN,
  initAppsAvailabilityChunk as appsAvailabilityT,
} from "../../utils/apps-availability";
import {
  initializePluginControlList as browserUseSettingsUnderscore,
  BrowserUsePermissionSections as browserUseSettingsC,
  PluginControlList as browserUseSettingsG,
  findPreferredBrowserUsePlugin as browserUseSettingsH,
  initializePreferredBrowserUsePluginHelpers as browserUseSettingsM,
  initializeBrowserUseSettingsChunk as browserUseSettingsP,
  BrowserUseApprovalModeRow as browserUseSettingsS,
  BrowserUseHistoryApprovalModeRow as browserUseSettingsU,
  FullCdpDeveloperModeSection as browserUseSettingsV,
  initializeFullCdpDeveloperModeSection as browserUseSettingsY,
} from "../../browser/browser-use-settings/index";
var excelIconUrl,
  initExcelIconUrl = rolldownRuntimeN(() => {
    excelIconUrl =
      `` + new URL(`microsoft-excel-large-CY0bRHcJ.png`, import.meta.url).href;
  }),
  powerPointIconUrl,
  initPowerPointIconUrl = rolldownRuntimeN(() => {
    powerPointIconUrl =
      `` +
      new URL(`microsoft-powerpoint-large-DlJg6gsJ.png`, import.meta.url).href;
  });
var computerUseBinding5,
  computerUseBinding6,
  computerUseBinding7 = rolldownRuntimeN(() => {
    ((computerUseBinding5 =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      (computerUseBinding6 =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()));
  });
var computerUseBinding8,
  computerUseBinding9,
  browserExtensionStatusMessages,
  initBrowserExtensionStatusMessages = rolldownRuntimeN(() => {
    ((computerUseBinding8 =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
      appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwHh(),
      appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      (computerUseBinding9 =
        appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()),
      (browserExtensionStatusMessages =
        appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy(
          {
            connected: {
              id: `plugins.browserExtension.connected`,
              defaultMessage: `Connected to browser extension for additional control`,
              description: `Status text shown when the Chrome browser extension is installed`,
            },
            disconnected: {
              id: `plugins.browserExtension.disconnected`,
              defaultMessage: `Browser extension not connected`,
              description: `Status text shown when the Chrome browser extension is not installed`,
            },
            loading: {
              id: `plugins.browserExtension.loading`,
              defaultMessage: `Use the browser extension for additional control`,
              description: `Status text shown while the Chrome browser extension install state is loading`,
            },
          },
        )));
  }),
  computerUseSettingsMessages,
  initComputerUseMessages = rolldownRuntimeN(() => {
    (appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
      (computerUseSettingsMessages =
        appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy(
          {
            control: {
              id: `settings.computerUse.install.title`,
              defaultMessage: `Control`,
              description: `Title for computer use plugin install settings section`,
            },
            anyApp: {
              id: `settings.computerUse.anyApp.title`,
              defaultMessage: `Any App`,
              description: `Label for the Computer Use plugin row that lets Codex control 'Any App' computerUsePluginSlug the user's computer`,
            },
            googleChrome: {
              id: `settings.computerUse.chrome.pluginTitle`,
              defaultMessage: `Google Chrome`,
              description: `Title for the Google Chrome plugin control row`,
            },
            microsoftExcel: {
              id: `settings.computerUse.microsoftExcel.pluginTitle`,
              defaultMessage: `Microsoft Excel`,
              description: `Title for the Microsoft Excel plugin control row`,
            },
            microsoftExcelDescription: {
              id: `settings.computerUse.microsoftExcel.description`,
              defaultMessage: `Let Codex use Microsoft Excel add-in for additional control`,
              description: `Description for the Microsoft Excel plugin control row`,
            },
            microsoftExcelToggleAria: {
              id: `settings.computerUse.microsoftExcel.appToggleAria`,
              defaultMessage: `Toggle Microsoft Excel live control`,
              description: `Accessible label for toggling Microsoft Excel live control from Computer Use settings`,
            },
            microsoftExcelDisableTooltip: {
              id: `settings.computerUse.microsoftExcel.disableToggleTooltip`,
              defaultMessage: `Disable Microsoft Excel live control`,
              description: `Tooltip label for disabling Microsoft Excel live control`,
            },
            microsoftExcelEnableTooltip: {
              id: `settings.computerUse.microsoftExcel.enableToggleTooltip`,
              defaultMessage: `Enable Microsoft Excel live control`,
              description: `Tooltip label for enabling Microsoft Excel live control`,
            },
            microsoftPowerPoint: {
              id: `settings.computerUse.microsoftPowerPoint.pluginTitle`,
              defaultMessage: `Microsoft PowerPoint`,
              description: `Title for the Microsoft PowerPoint plugin control row`,
            },
            microsoftPowerPointDescription: {
              id: `settings.computerUse.microsoftPowerPoint.description`,
              defaultMessage: `Let Codex use Microsoft PowerPoint add-in for additional control`,
              description: `Description for the Microsoft PowerPoint plugin control row`,
            },
            microsoftPowerPointToggleAria: {
              id: `settings.computerUse.microsoftPowerPoint.appToggleAria`,
              defaultMessage: `Toggle Microsoft PowerPoint live control`,
              description: `Accessible label for toggling Microsoft PowerPoint live control from Computer Use settings`,
            },
            microsoftPowerPointDisableTooltip: {
              id: `settings.computerUse.microsoftPowerPoint.disableToggleTooltip`,
              defaultMessage: `Disable Microsoft PowerPoint live control`,
              description: `Tooltip label for disabling Microsoft PowerPoint live control`,
            },
            microsoftPowerPointEnableTooltip: {
              id: `settings.computerUse.microsoftPowerPoint.enableToggleTooltip`,
              defaultMessage: `Enable Microsoft PowerPoint live control`,
              description: `Tooltip label for enabling Microsoft PowerPoint live control`,
            },
            alwaysAllowedApps: {
              id: `settings.computerUse.allowedApps.title`,
              defaultMessage: `Always-allowed apps`,
              description: `Title for computer use always allowed apps list`,
            },
            foregroundClickSounds: {
              id: `settings.computerUse.sounds.foregroundClicks`,
              defaultMessage: `Play sounds for foreground clicks`,
              description: `Computer use sound setting option for foreground click sounds`,
            },
            foregroundAndBackgroundClickSounds: {
              id: `settings.computerUse.sounds.foregroundAndBackgroundClicks`,
              defaultMessage: `Play sounds for foreground and background clicks`,
              description: `Computer use sound setting option for foreground and background click sounds`,
            },
            noClickSounds: {
              id: `settings.computerUse.sounds.off`,
              defaultMessage: `Don’t play sounds`,
              description: `Computer use sound setting option for no sounds`,
            },
          },
        )));
  }),
  chromeIconUrl,
  initChromeIconUrl = rolldownRuntimeN(() => {
    chromeIconUrl =
      `` +
      new URL(`chrome-production-large-BLPyHeGg.png`, import.meta.url).href;
  });
var computerUseBinding16,
  computerUseReactRuntime,
  computerUseElementFactory,
  computerUseSettingsSlug,
  computerUsePluginSlug,
  chromePluginSlug,
  chromeDevPluginSlug,
  chromeInternalPluginSlug,
  documentControlAppId,
  chromeComputerUseSettingsPath,
  defaultComputerUseSoundMode,
  computerUseSoundModeOptions;
rolldownRuntimeN(() => {
  ((computerUseBinding16 =
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc()),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwHh(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO(),
    (computerUseReactRuntime = rolldownRuntimeS(
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
      1,
    )),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa(),
    appsAvailabilityT(),
    initExcelIconUrl(),
    initPowerPointIconUrl(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs(),
    computerUseBinding7(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOm(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn(),
    appInitialAppMainOnboardingPageSc(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nXt(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNl(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEl(),
    useHomeDirectoryT(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkF(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBs(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDp(),
    appInitialAppMainOnboardingPageAd(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nLt(),
    initBrowserExtensionStatusMessages(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nFt(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEd(),
    appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btD(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNc(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIc(),
    appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD(),
    appInitialAppMainOnboardingPageZu(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nMt(),
    appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR(),
    browserUseSettingsY(),
    browserUseSettingsP(),
    initComputerUseMessages(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF(),
    AppInitialAppMainOnboardingPageAu(),
    browserUseSettingsUnderscore(),
    browserUseSettingsM(),
    AppInitialAppMainOnboardingPageIn(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH(),
    appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp(),
    appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy(),
    appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwQc(),
    _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC(),
    initChromeIconUrl(),
    (computerUseElementFactory =
      appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc()),
    (computerUseSettingsSlug = `computer-use`),
    (computerUsePluginSlug = `computer-use`),
    (chromePluginSlug = `chrome`),
    (chromeDevPluginSlug = `chrome-dev`),
    (chromeInternalPluginSlug = `chrome-internal`),
    (documentControlAppId = `connector_openai_codex_document_control`),
    (chromeComputerUseSettingsPath = `/settings/computer-use/google-chrome`),
    (defaultComputerUseSoundMode = `foregroundClicks`),
    (computerUseSoundModeOptions = [
      {
        value: `foregroundClicks`,
        label: computerUseSettingsMessages.foregroundClickSounds,
      },
      {
        value: `foregroundAndBackgroundClicks`,
        label: computerUseSettingsMessages.foregroundAndBackgroundClickSounds,
      },
      {
        value: `off`,
        label: computerUseSettingsMessages.noClickSounds,
      },
    ]));
})();
export default {
  AppInitialAppMainOnboardingPageAu,
  AppInitialAppMainOnboardingPageIn,
  AppInitialAppMainOnboardingPageRu,
  AppInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dRy,
  _appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  _appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nFt,
  appInitialAppMainOnboardingPageAd,
  appInitialAppMainOnboardingPageFn,
  appInitialAppMainOnboardingPageGc,
  appInitialAppMainOnboardingPageId,
  appInitialAppMainOnboardingPageKu,
  appInitialAppMainOnboardingPageMu,
  appInitialAppMainOnboardingPageSc,
  appInitialAppMainOnboardingPageZu,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsD,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsF,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsJ,
  appInitialAppMainPetsSettingsAppearanceSettingsGeneralSettingsQ,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wA,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wC,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wCc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wD,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wE,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wGo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wI,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wKo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wLi,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wO,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wQo,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wS,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wTc,
  appInitialAppMainRemoteConversationPageHotkeyWindowThreadPageAutomationsPageThBnlvjk3wVo,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nFt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nGt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nH,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nHt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nIt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nLt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nMt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nPt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nR,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nRt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nT,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nUt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nV,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nXt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageAppgenLibraryPageHotDjo67r4nYt,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dEa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dFy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dIy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dP,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dPa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dQp,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dTy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dVy,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dXa,
  appInitialAppMainRemoteConversationPageNewThreadPanelPageProjectsIndexPageAppIy8s9c2dZy,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcR,
  appInitialAppMainSettingsPageOpenSourceLicensesPageSkillsSettingsPluginsSettinCxbtmbfcT,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btD,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btK,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btO,
  appInitialAppMainWorktreeInitV2PageAppgenSettingsPageAppgenPublicationTermsRoG0k1g2btT,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwA,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwAn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwBs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwCa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwDp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEd,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwEp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwGp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwHh,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwIs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKn,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwKp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMh,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwMp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwNs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwOp,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwQc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwRl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTl,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwTm,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwU,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwVa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwWo,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYa,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwYs,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPageNewThreadPanelPageOKo8xg8gwZc,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkF,
  appInitialAppMainWorktreeInitV2PageRemoteConversationPagePullRequestsPageNewOzr5a6hkP,
  appsAvailabilityN,
  appsAvailabilityT,
  browserExtensionStatusMessages,
  browserUseSettingsC,
  browserUseSettingsG,
  browserUseSettingsH,
  browserUseSettingsM,
  browserUseSettingsP,
  browserUseSettingsS,
  browserUseSettingsU,
  browserUseSettingsUnderscore,
  browserUseSettingsV,
  browserUseSettingsY,
  chromeComputerUseSettingsPath,
  chromeDevPluginSlug,
  chromeIconUrl,
  chromeInternalPluginSlug,
  chromePluginSlug,
  computerUseBinding16,
  computerUseBinding5,
  computerUseBinding6,
  computerUseBinding7,
  computerUseBinding8,
  computerUseBinding9,
  computerUseElementFactory,
  computerUsePluginSlug,
  computerUseReactRuntime,
  computerUseSettingsMessages,
  computerUseSettingsSlug,
  computerUseSoundModeOptions,
  defaultComputerUseSoundMode,
  documentControlAppId,
  excelIconUrl,
  initBrowserExtensionStatusMessages,
  initChromeIconUrl,
  initComputerUseMessages,
  initExcelIconUrl,
  initPowerPointIconUrl,
  powerPointIconUrl,
  rolldownRuntimeN,
  rolldownRuntimeS,
  useHomeDirectoryN,
  useHomeDirectoryT,
};
