// Restored from ref/.vite/build/main-Cfnoc8EH.js
// Environment constants for node_repl browser/computer-use host services.

export const NODE_REPL_HOST_SERVICES_PIPE_PATH_ENV =
  "NODE_REPL_HOST_SERVICES_PIPE_PATH";

export const NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS_ENV =
  "NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS";
export const NODE_REPL_NODE_MODULE_DIRS_ENV = "NODE_REPL_NODE_MODULE_DIRS";
export const NODE_REPL_NODE_PATH_ENV = "NODE_REPL_NODE_PATH";
export const NODE_REPL_REQUEST_META_ENV = "NODE_REPL_REQUEST_META";
export const NODE_REPL_SENTRY_USER_ID_ENV = "NODE_REPL_SENTRY_USER_ID";
export const NODE_REPL_TRACE_META_ENV = "NODE_REPL_TRACE_META";
export const NODE_REPL_TRUST_ALL_CODE_ENV = "NODE_REPL_TRUST_ALL_CODE";
export const NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S_ENV =
  "NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S";

export const CODEX_CLI_PATH_ENV = "CODEX_CLI_PATH";
export const CODEX_BROWSER_USE_NODE_PATH_ENV = "CODEX_BROWSER_USE_NODE_PATH";
export const CODEX_NODE_REPL_PATH_ENV = "CODEX_NODE_REPL_PATH";

export const BROWSER_USE_AVAILABLE_BACKENDS_ENV =
  "BROWSER_USE_AVAILABLE_BACKENDS";
export const BROWSER_USE_CODEX_APP_BUILD_FLAVOR_ENV =
  "BROWSER_USE_CODEX_APP_BUILD_FLAVOR";
export const BROWSER_USE_CODEX_APP_VERSION_ENV =
  "BROWSER_USE_CODEX_APP_VERSION";
export const BROWSER_USE_DISABLE_AMBIENT_NETWORK_ENV =
  "BROWSER_USE_DISABLE_AMBIENT_NETWORK";
export const BROWSER_USE_DISABLE_API_MEMBERS_ENV =
  "BROWSER_USE_DISABLE_API_MEMBERS";
export const BROWSER_USE_DISABLE_BROWSER_CAPABILITIES_ENV =
  "BROWSER_USE_DISABLE_BROWSER_CAPABILITIES";
export const BROWSER_USE_DISABLE_TAB_CAPABILITIES_ENV =
  "BROWSER_USE_DISABLE_TAB_CAPABILITIES";
export const BROWSER_USE_SECURITY_MODE_ENV = "BROWSER_USE_SECURITY_MODE";

export const CODEX_CHROME_USER_DATA_DIR_ENV = "CODEX_CHROME_USER_DATA_DIR";
export const NODE_REPL_DISABLE_ANALYTICS_ENV = "NODE_REPL_DISABLE_ANALYTICS";
export const NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER_ENV =
  "NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER";
export const NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME_ENV =
  "NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME";
export const NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE_ENV =
  "NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE";
export const NODE_REPL_UNTRUSTED_ENV_ALLOWLIST_ENV =
  "NODE_REPL_UNTRUSTED_ENV_ALLOWLIST";

export const NODE_REPL_MCP_SERVER_NAME = "node_repl";
export const NODE_REPL_MCP_SERVER_KEY = `mcp_servers.${NODE_REPL_MCP_SERVER_NAME}`;
export const COMPUTER_USE_MCP_SERVER_KEY = "mcp_servers.computer-use";

export const BROWSER_USE_IN_APP_INSTRUCTIONS =
  "Control the in-app browser in conjunction with the Browser Plugin.";
export const CHROME_BROWSER_USE_INSTRUCTIONS =
  "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative.";
export const COMPUTER_USE_NODE_REPL_INSTRUCTIONS =
  "Control desktop apps on macOS through Computer Use.";

export const COMPUTER_USE_MAC_MCP_CONFIG = {
  [COMPUTER_USE_MCP_SERVER_KEY]: {
    args: ["mcp"],
    command:
      "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
    cwd: ".",
    enabled: false,
  },
} as const;

export const NODE_REPL_DISABLED_JS_REPL_CONFIG = {
  "features.js_repl": false,
} as const;

export const NODE_REPL_JS_REPL_FEATURE_KEY = "features.js_repl";

export const BROWSER_USE_ENV_PASSTHROUGH = [
  CODEX_CHROME_USER_DATA_DIR_ENV,
  BROWSER_USE_DISABLE_AMBIENT_NETWORK_ENV,
  BROWSER_USE_DISABLE_API_MEMBERS_ENV,
  BROWSER_USE_DISABLE_BROWSER_CAPABILITIES_ENV,
  BROWSER_USE_DISABLE_TAB_CAPABILITIES_ENV,
] as const;

export const DEV_ONLY_ENV_PASSTHROUGH = [
  BROWSER_USE_SECURITY_MODE_ENV,
  NODE_REPL_DISABLE_ANALYTICS_ENV,
] as const;
