// Restored from ref/webview/assets/app-initial~app-main~remote-conversation-page~pull-requests-page~onboarding-page~projects-i~easvi6ps-Cs84X9Ip.js
// Focused RRULE parser for automation schedules generated by the app.

import {
  AUTOMATION_BUSINESS_DAYS,
  AUTOMATION_WEEKDAYS,
  type AutomationScheduleMode,
  type AutomationWeekday,
} from "./types";
import {
  DEFAULT_AUTOMATION_TIME,
  DEFAULT_AUTOMATION_WEEKDAY,
  formatAutomationTime,
  normalizeIntervalHours,
  normalizeIntervalMinutes,
  parseAutomationTime,
} from "./schedule-time";

export type RruleFrequency =
  | "SECONDLY"
  | "MINUTELY"
  | "HOURLY"
  | "DAILY"
  | "WEEKLY"
  | "MONTHLY"
  | "YEARLY";

export type ParsedAutomationRrule = {
  freq: RruleFrequency;
  hasMultipleTimeValues: boolean;
  interval: number;
  minute: number | null;
  options: Map<string, string>;
  rruleText: string;
  time: string;
  weekdays: AutomationWeekday[];
};

const HOUR_INTERVAL_OPTIONS = new Set([
  "FREQ",
  "INTERVAL",
  "DTSTART",
  "TZID",
  "BYDAY",
  "BYMINUTE",
]);
const DATE_INTERVAL_OPTIONS = new Set([...HOUR_INTERVAL_OPTIONS, "BYHOUR"]);

export function parseAutomationRrule(
  rruleText: string,
): ParsedAutomationRrule | null {
  const normalized = normalizeRruleText(rruleText);
  if (!normalized) return null;

  const options = parseRruleOptions(normalized);
  const freq = options.get("FREQ") as RruleFrequency | undefined;
  if (!isRruleFrequency(freq)) return null;

  const byHour = parseNumberList(options.get("BYHOUR"));
  const byMinute = parseNumberList(options.get("BYMINUTE"));
  const interval =
    normalizeIntervalHours(Number(options.get("INTERVAL") ?? 1)) ?? 1;
  const time = resolveScheduleTime(byHour, byMinute, options);
  const weekdays = parseWeekdays(options.get("BYDAY")) ?? [
    ...AUTOMATION_WEEKDAYS,
  ];

  return {
    freq,
    hasMultipleTimeValues:
      (byHour?.length ?? 0) > 1 || (byMinute?.length ?? 0) > 1,
    interval,
    minute: byMinute?.[0] ?? null,
    options,
    rruleText: normalized,
    time,
    weekdays,
  };
}

export function parseAutomationRruleForAnalytics(
  rrule?: string | null,
): RruleFrequency | null {
  return rrule ? (parseAutomationRrule(rrule)?.freq ?? null) : null;
}

export function inferScheduleMode(
  parsed: ParsedAutomationRrule,
): AutomationScheduleMode {
  if (parsed.hasMultipleTimeValues) return "custom";

  if (
    parsed.freq === "HOURLY" &&
    hasOnlyOptions(parsed.options, HOUR_INTERVAL_OPTIONS) &&
    parsed.interval === 1 &&
    parsed.minute === 0 &&
    sameWeekdays(parsed.weekdays, AUTOMATION_WEEKDAYS)
  ) {
    return "hourly";
  }

  if (
    (parsed.freq === "DAILY" || parsed.freq === "WEEKLY") &&
    hasOnlyOptions(parsed.options, DATE_INTERVAL_OPTIONS) &&
    parsed.interval === 1
  ) {
    if (sameWeekdays(parsed.weekdays, AUTOMATION_WEEKDAYS)) return "daily";
    if (sameWeekdays(parsed.weekdays, AUTOMATION_BUSINESS_DAYS)) {
      return "weekdays";
    }
    if (parsed.weekdays.length === 1) return "weekly";
  }

  return "custom";
}

export function getHeartbeatIntervalMinutes(
  parsed: ParsedAutomationRrule,
): number | null {
  if (parsed.hasMultipleTimeValues) return null;

  if (
    parsed.freq === "MINUTELY" &&
    hasOnlyOptions(parsed.options, HOUR_INTERVAL_OPTIONS)
  ) {
    return normalizeIntervalMinutes(parsed.interval) ?? 30;
  }

  if (
    parsed.freq === "HOURLY" &&
    hasOnlyOptions(parsed.options, HOUR_INTERVAL_OPTIONS) &&
    (parsed.minute == null || parsed.minute === 0) &&
    sameWeekdays(parsed.weekdays, AUTOMATION_WEEKDAYS)
  ) {
    return (normalizeIntervalHours(parsed.interval) ?? 1) * 60;
  }

  return null;
}

export function serializeHourlyRrule(intervalHours: number): string {
  return [
    "RRULE:FREQ=HOURLY",
    `INTERVAL=${normalizeIntervalHours(intervalHours) ?? 1}`,
    "BYMINUTE=0",
    `BYDAY=${AUTOMATION_WEEKDAYS.join(",")}`,
  ].join(";");
}

export function serializeMinutelyRrule(intervalMinutes: number): string {
  return [
    "RRULE:FREQ=MINUTELY",
    `INTERVAL=${normalizeIntervalMinutes(intervalMinutes) ?? 30}`,
  ].join(";");
}

export function serializeWeeklyRrule({
  time,
  weekdays,
}: {
  time: string;
  weekdays: AutomationWeekday[];
}): string {
  const parsedTime =
    parseAutomationTime(time) ?? parseAutomationTime(DEFAULT_AUTOMATION_TIME);

  return [
    "RRULE:FREQ=WEEKLY",
    `BYHOUR=${parsedTime?.hour ?? 9}`,
    `BYMINUTE=${parsedTime?.minute ?? 0}`,
    `BYDAY=${sortAutomationWeekdays(weekdays).join(",")}`,
  ].join(";");
}

export function sameWeekdays(
  weekdays: readonly AutomationWeekday[],
  expectedWeekdays: readonly AutomationWeekday[],
): boolean {
  return (
    weekdays.length === expectedWeekdays.length &&
    expectedWeekdays.every((weekday) => weekdays.includes(weekday))
  );
}

export function sortAutomationWeekdays(
  weekdays: readonly AutomationWeekday[],
): AutomationWeekday[] {
  return AUTOMATION_WEEKDAYS.filter((weekday) => weekdays.includes(weekday));
}

export function firstAutomationWeekday(
  weekdays: readonly AutomationWeekday[],
): AutomationWeekday {
  return sortAutomationWeekdays(weekdays)[0] ?? DEFAULT_AUTOMATION_WEEKDAY;
}

function normalizeRruleText(rruleText: string): string | null {
  const trimmed = rruleText.trim();
  if (!trimmed) return null;

  const ruleLine =
    trimmed
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find((line) => line.toUpperCase().startsWith("RRULE:")) ?? trimmed;

  return ruleLine.replace(/^RRULE:/i, "").trim();
}

function parseRruleOptions(rrule: string): Map<string, string> {
  const options = new Map<string, string>();

  for (const part of rrule.split(";")) {
    const [key, ...valueParts] = part.split("=");
    const value = valueParts.join("=");

    if (key && value) {
      options.set(key.trim().toUpperCase(), value.trim());
    }
  }

  return options;
}

function isRruleFrequency(value: unknown): value is RruleFrequency {
  return (
    value === "SECONDLY" ||
    value === "MINUTELY" ||
    value === "HOURLY" ||
    value === "DAILY" ||
    value === "WEEKLY" ||
    value === "MONTHLY" ||
    value === "YEARLY"
  );
}

function parseNumberList(value: string | undefined): number[] | null {
  if (!value) return null;
  const numbers = value
    .split(",")
    .map((item) => Number(item.trim()))
    .filter((item) => Number.isFinite(item));

  return numbers.length ? numbers : null;
}

function resolveScheduleTime(
  byHour: number[] | null,
  byMinute: number[] | null,
  options: Map<string, string>,
): string {
  const hour = byHour?.[0];
  const minute = byMinute?.[0];

  if (hour != null && minute != null) {
    return formatAutomationTime(hour, minute);
  }

  const dtstart = options.get("DTSTART");
  const dtstartTime = dtstart?.match(/T(\d{2})(\d{2})(\d{2})?Z?$/);
  if (dtstartTime) {
    return `${dtstartTime[1]}:${dtstartTime[2]}`;
  }

  return DEFAULT_AUTOMATION_TIME;
}

function parseWeekdays(value: string | undefined): AutomationWeekday[] | null {
  if (!value) return null;

  const weekdays = value
    .split(",")
    .map((item) =>
      item
        .trim()
        .toUpperCase()
        .replace(/^[+-]?\d+/, ""),
    )
    .filter((item): item is AutomationWeekday =>
      AUTOMATION_WEEKDAYS.includes(item as AutomationWeekday),
    );

  return weekdays.length ? sortAutomationWeekdays(weekdays) : null;
}

function hasOnlyOptions(
  options: Map<string, string>,
  allowedOptions: Set<string>,
): boolean {
  return [...options.keys()].every((key) => allowedOptions.has(key));
}
